/* Crystal names and correspondences are traditional; the descriptions are original Ishtar Insights copy. */
(function(root, factory) { const data = factory(); if (typeof module === 'object' && module.exports) module.exports = data; else root.CrystalData = data; })(typeof globalThis !== 'undefined' ? globalThis : this, () => {
  const chakras = [
    {key: 'root', name: 'Root'}, {key: 'sacral', name: 'Sacral'}, {key: 'solar-plexus', name: 'Solar plexus'},
    {key: 'heart', name: 'Heart'}, {key: 'throat', name: 'Throat'}, {key: 'third-eye', name: 'Third eye'}, {key: 'crown', name: 'Crown'}
  ];
  const crystals = [
    {slug: 'agate', name: 'Agate', aka: ['banded agate'], colours: ['#b98b6a', '#e8d8c4', '#7a8fa0'], signs: ['Gemini', 'Virgo'], chakras: ['root'], element: 'Earth', planet: 'Mercury', cards: ['the-hermit']},
    {slug: 'alexandrite', name: 'Alexandrite', aka: ['color-change chrysoberyl'], colours: ['#2e7d5b', '#7a2e5b'], signs: ['Gemini', 'Scorpio'], chakras: ['heart', 'crown'], element: 'Fire', planet: 'Mercury', cards: ['temperance']},
    {slug: 'amazonite', name: 'Amazonite', aka: [], colours: ['#5fb8a8', '#8fd4c4'], signs: ['Virgo', 'Aquarius'], chakras: ['heart', 'throat'], element: 'Water', planet: 'Uranus', cards: ['the-star']},
    {slug: 'amber', name: 'Amber', aka: ['resin amber'], colours: ['#e0952f', '#c9761c'], signs: ['Leo', 'Aquarius'], chakras: ['solar-plexus'], element: 'Fire', planet: 'Sun', cards: ['the-sun']},
    {slug: 'amethyst', name: 'Amethyst', aka: ['purple quartz'], colours: ['#8a5cb0', '#5b2e7d'], signs: ['Pisces', 'Aquarius', 'Virgo'], chakras: ['third-eye', 'crown'], element: 'Water', planet: 'Jupiter', cards: ['temperance']},
    {slug: 'ametrine', name: 'Ametrine', aka: [], colours: ['#8a5cb0', '#e8c547'], signs: ['Libra', 'Sagittarius'], chakras: ['solar-plexus', 'crown'], element: 'Fire', planet: 'Venus', cards: ['temperance']},
    {slug: 'angelite', name: 'Angelite', aka: [], colours: ['#a9c9e0', '#cfe3f0'], signs: ['Aquarius'], chakras: ['throat', 'crown'], element: 'Air', planet: 'Uranus', cards: ['the-star']},
    {slug: 'apache-tears', name: 'Apache tears', aka: ['Apache tear obsidian'], colours: ['#3a2a20', '#5c4433'], signs: ['Scorpio'], chakras: ['root'], element: 'Earth', planet: 'Saturn', cards: ['the-star']},
    {slug: 'apatite', name: 'Apatite', aka: [], colours: ['#3fa0a0', '#2e7d7d'], signs: ['Gemini'], chakras: ['throat', 'third-eye'], element: 'Air', planet: 'Mercury', cards: ['the-magician']},
    {slug: 'apophyllite', name: 'Apophyllite', aka: [], colours: ['#e8f0e8', '#cfe8cf'], signs: ['Gemini', 'Libra'], chakras: ['crown', 'third-eye'], element: 'Air', planet: 'Uranus', cards: ['the-star']},
    {slug: 'aquamarine', name: 'Aquamarine', aka: [], colours: ['#7fc4c4', '#a9dede'], signs: ['Pisces'], chakras: ['throat'], element: 'Water', planet: 'Neptune', cards: ['ace-of-cups']},
    {slug: 'aragonite', name: 'Aragonite', aka: [], colours: ['#c9a877', '#a8845a'], signs: ['Capricorn'], chakras: ['root'], element: 'Earth', planet: 'Saturn', cards: ['the-hermit']},
    {slug: 'azurite', name: 'Azurite', aka: [], colours: ['#1f3f8c', '#2e5aa8'], signs: ['Sagittarius', 'Capricorn'], chakras: ['third-eye'], element: 'Water', planet: 'Jupiter', cards: ['the-high-priestess']},
    {slug: 'black-tourmaline', name: 'Black tourmaline', aka: [], colours: ['#1a1a1a', '#2b2b2b'], signs: ['Capricorn', 'Scorpio'], chakras: ['root'], element: 'Earth', planet: 'Saturn', cards: ['the-emperor']},
    {slug: 'bloodstone', name: 'Bloodstone', aka: [], colours: ['#2e5c3a', '#a83232'], signs: ['Aries'], chakras: ['root', 'heart'], element: 'Fire', planet: 'Mars', cards: ['the-chariot']},
    {slug: 'blue-calcite', name: 'Blue calcite', aka: [], colours: ['#a9c9e0', '#cfe3f0'], signs: ['Cancer'], chakras: ['throat'], element: 'Water', planet: 'Moon', cards: ['the-high-priestess']},
    {slug: 'blue-lace-agate', name: 'Blue lace agate', aka: [], colours: ['#b8d4e8', '#e0eef5'], signs: ['Gemini', 'Pisces'], chakras: ['throat'], element: 'Air', planet: 'Mercury', cards: ['the-star']},
    {slug: 'carnelian', name: 'Carnelian', aka: [], colours: ['#d9541f', '#e07a3f'], signs: ['Leo', 'Taurus'], chakras: ['sacral'], element: 'Fire', planet: 'Sun', cards: ['the-sun']},
    {slug: 'cavansite', name: 'Cavansite', aka: [], colours: ['#2e6fae', '#3f8cc9'], signs: ['Pisces'], chakras: ['third-eye', 'crown'], element: 'Water', planet: 'Neptune', cards: ['the-moon']},
    {slug: 'celestite', name: 'Celestite', aka: [], colours: ['#cfe3f0', '#a9c9e0'], signs: ['Gemini'], chakras: ['throat', 'crown'], element: 'Air', planet: 'Uranus', cards: ['the-star']},
    {slug: 'chalcedony', name: 'Chalcedony', aka: [], colours: ['#c9d4dc', '#a9b8c4'], signs: ['Cancer', 'Sagittarius'], chakras: ['throat'], element: 'Water', planet: 'Moon', cards: ['the-empress']},
    {slug: 'charoite', name: 'Charoite', aka: [], colours: ['#6b3f8c', '#8a5cb0'], signs: ['Scorpio', 'Sagittarius'], chakras: ['third-eye', 'crown'], element: 'Fire', planet: 'Pluto', cards: ['death']},
    {slug: 'chiastolite', name: 'Chiastolite', aka: ['cross stone'], colours: ['#8a6a4a', '#5c4433'], signs: ['Libra', 'Pisces'], chakras: ['root'], element: 'Earth', planet: 'Saturn', cards: ['justice']},
    {slug: 'chrysocolla', name: 'Chrysocolla', aka: [], colours: ['#3f9c8c', '#5fb8a8'], signs: ['Gemini', 'Virgo', 'Taurus'], chakras: ['throat', 'heart'], element: 'Water', planet: 'Venus', cards: ['the-empress']},
    {slug: 'chrysoprase', name: 'Chrysoprase', aka: [], colours: ['#8fd47a', '#6fae5c'], signs: ['Libra', 'Taurus'], chakras: ['heart'], element: 'Earth', planet: 'Venus', cards: ['the-star']},
    {slug: 'cinnabar', name: 'Cinnabar', aka: [], colours: ['#a8241f', '#c0392b'], signs: ['Scorpio', 'Leo'], chakras: ['root', 'sacral'], element: 'Fire', planet: 'Mars', cards: ['the-magician']},
    {slug: 'citrine', name: 'Citrine', aka: [], colours: ['#e8c547', '#f0d878'], signs: ['Leo', 'Gemini'], chakras: ['solar-plexus'], element: 'Fire', planet: 'Sun', cards: ['the-sun']},
    {slug: 'clear-quartz', name: 'Clear quartz', aka: ['rock crystal'], colours: ['#f5f5f0', '#ffffff'], signs: ['Aries'], chakras: ['crown'], element: 'Air', planet: 'Sun', cards: ['the-magician']},
    {slug: 'dalmatian-jasper', name: 'Dalmatian jasper', aka: [], colours: ['#d9d0b8', '#3a2a20'], signs: ['Leo', 'Sagittarius'], chakras: ['root', 'sacral'], element: 'Earth', planet: 'Jupiter', cards: ['the-fool']},
    {slug: 'desert-rose', name: 'Desert rose', aka: ['gypsum rose'], colours: ['#c9a877', '#e8d8c4'], signs: ['Virgo', 'Capricorn'], chakras: ['root', 'third-eye'], element: 'Earth', planet: 'Saturn', cards: ['the-hermit']},
    {slug: 'diamond', name: 'Diamond', aka: [], colours: ['#f5f5f0', '#ffffff'], signs: ['Aries', 'Leo'], chakras: ['crown'], element: 'Fire', planet: 'Sun', cards: ['the-sun']},
    {slug: 'dumortierite', name: 'Dumortierite', aka: [], colours: ['#2e3f8c', '#3f4fae'], signs: ['Virgo'], chakras: ['third-eye', 'throat'], element: 'Air', planet: 'Mercury', cards: ['the-hermit']},
    {slug: 'emerald', name: 'Emerald', aka: [], colours: ['#2e7d5b', '#3f9c6b'], signs: ['Taurus', 'Gemini'], chakras: ['heart'], element: 'Earth', planet: 'Venus', cards: ['ace-of-pentacles']},
    {slug: 'fire-agate', name: 'Fire agate', aka: [], colours: ['#a8541f', '#c97a3f'], signs: ['Aries', 'Scorpio'], chakras: ['root', 'sacral'], element: 'Fire', planet: 'Mars', cards: ['the-chariot']},
    {slug: 'fluorite', name: 'Fluorite', aka: [], colours: ['#7a5cae', '#4a8f5c'], signs: ['Pisces', 'Capricorn'], chakras: ['third-eye', 'crown'], element: 'Air', planet: 'Neptune', cards: ['justice']},
    {slug: 'fuchsite', name: 'Fuchsite', aka: [], colours: ['#5c8f5c', '#7aae7a'], signs: ['Aries', 'Taurus'], chakras: ['heart'], element: 'Earth', planet: 'Venus', cards: ['the-star']},
    {slug: 'garnet', name: 'Garnet', aka: [], colours: ['#8c1f2b', '#a8324a'], signs: ['Capricorn', 'Aquarius', 'Virgo'], chakras: ['root'], element: 'Fire', planet: 'Mars', cards: ['strength']},
    {slug: 'green-aventurine', name: 'Green aventurine', aka: [], colours: ['#5c9c6b', '#7ec48a'], signs: ['Aries', 'Virgo'], chakras: ['heart'], element: 'Earth', planet: 'Venus', cards: ['wheel-of-fortune']},
    {slug: 'halite', name: 'Halite', aka: ['rock salt'], colours: ['#e8d8d0', '#f0c9d4'], signs: ['Cancer'], chakras: ['sacral', 'solar-plexus'], element: 'Water', planet: 'Moon', cards: ['the-star']},
    {slug: 'hematite', name: 'Hematite', aka: [], colours: ['#3a3a3a', '#5c5c5c'], signs: ['Aries', 'Aquarius'], chakras: ['root'], element: 'Earth', planet: 'Mars', cards: ['strength']},
    {slug: 'herkimer-diamond', name: 'Herkimer diamond', aka: ['Herkimer quartz'], colours: ['#f0f0e8', '#ffffff'], signs: ['Gemini', 'Sagittarius'], chakras: ['crown', 'third-eye'], element: 'Air', planet: 'Uranus', cards: ['the-star']},
    {slug: 'howlite', name: 'Howlite', aka: [], colours: ['#e8e4dc', '#c9c4b8'], signs: ['Gemini', 'Cancer'], chakras: ['crown'], element: 'Air', planet: 'Moon', cards: ['the-hanged-man']},
    {slug: 'iolite', name: 'Iolite', aka: ['water sapphire'], colours: ['#5c6fae', '#4a5c8c'], signs: ['Sagittarius', 'Libra'], chakras: ['third-eye'], element: 'Air', planet: 'Jupiter', cards: ['the-star']},
    {slug: 'jade', name: 'Jade', aka: [], colours: ['#4a8f5c', '#6fae7a'], signs: ['Taurus', 'Gemini', 'Pisces'], chakras: ['heart'], element: 'Earth', planet: 'Venus', cards: ['the-world']},
    {slug: 'jet', name: 'Jet', aka: [], colours: ['#1a1a1a', '#2b2b2b'], signs: ['Capricorn', 'Scorpio'], chakras: ['root'], element: 'Earth', planet: 'Saturn', cards: ['death']},
    {slug: 'kunzite', name: 'Kunzite', aka: [], colours: ['#e0a8c4', '#d88ca3'], signs: ['Taurus', 'Scorpio', 'Leo'], chakras: ['heart'], element: 'Water', planet: 'Venus', cards: ['the-lovers']},
    {slug: 'kyanite', name: 'Kyanite', aka: [], colours: ['#3f6fae', '#4a7cc4'], signs: ['Libra', 'Aries', 'Taurus'], chakras: ['throat', 'third-eye'], element: 'Air', planet: 'Mercury', cards: ['justice']},
    {slug: 'labradorite', name: 'Labradorite', aka: [], colours: ['#4a5c6b', '#3f6fae', '#5c9c8c'], signs: ['Scorpio', 'Sagittarius', 'Leo'], chakras: ['third-eye', 'throat'], element: 'Water', planet: 'Neptune', cards: ['the-moon']},
    {slug: 'lapis-lazuli', name: 'Lapis lazuli', aka: [], colours: ['#1f3f8c', '#c9a227'], signs: ['Libra', 'Sagittarius'], chakras: ['third-eye', 'throat'], element: 'Water', planet: 'Jupiter', cards: ['the-high-priestess']},
    {slug: 'larimar', name: 'Larimar', aka: [], colours: ['#a9d4e0', '#cfe8f0'], signs: ['Pisces', 'Leo'], chakras: ['throat', 'heart'], element: 'Water', planet: 'Neptune', cards: ['the-star']},
    {slug: 'lepidolite', name: 'Lepidolite', aka: [], colours: ['#c9a8d4', '#e0c9e8'], signs: ['Libra', 'Sagittarius'], chakras: ['heart', 'third-eye'], element: 'Water', planet: 'Neptune', cards: ['the-star']},
    {slug: 'lodestone', name: 'Lodestone', aka: ['magnetite'], colours: ['#2b2b2b', '#4a4a4a'], signs: ['Scorpio', 'Capricorn'], chakras: ['root'], element: 'Earth', planet: 'Mars', cards: ['the-magician']},
    {slug: 'malachite', name: 'Malachite', aka: [], colours: ['#1f5c3a', '#2e7d4a'], signs: ['Scorpio', 'Capricorn'], chakras: ['heart', 'solar-plexus'], element: 'Earth', planet: 'Pluto', cards: ['the-devil']},
    {slug: 'moldavite', name: 'Moldavite', aka: [], colours: ['#4a5c2e', '#3a4a20'], signs: ['Scorpio', 'Sagittarius'], chakras: ['heart', 'third-eye'], element: 'Fire', planet: 'Uranus', cards: ['the-tower']},
    {slug: 'mookaite', name: 'Mookaite', aka: ['mookaite jasper'], colours: ['#a8541f', '#8a6a8c'], signs: ['Scorpio', 'Sagittarius'], chakras: ['root', 'sacral'], element: 'Earth', planet: 'Saturn', cards: ['wheel-of-fortune']},
    {slug: 'moonstone', name: 'Moonstone', aka: [], colours: ['#e0e4e8', '#c9d4dc'], signs: ['Cancer', 'Libra', 'Scorpio'], chakras: ['third-eye', 'sacral'], element: 'Water', planet: 'Moon', cards: ['the-high-priestess']},
    {slug: 'morganite', name: 'Morganite', aka: [], colours: ['#e8b8c9', '#f0d0dc'], signs: ['Taurus', 'Libra'], chakras: ['heart'], element: 'Water', planet: 'Venus', cards: ['ace-of-cups']},
    {slug: 'moss-agate', name: 'Moss agate', aka: [], colours: ['#5c8f5c', '#e8e4dc'], signs: ['Virgo', 'Taurus'], chakras: ['heart'], element: 'Earth', planet: 'Venus', cards: ['the-empress']},
    {slug: 'obsidian', name: 'Obsidian', aka: [], colours: ['#1a1a1a', '#2b2b2b'], signs: ['Sagittarius', 'Scorpio'], chakras: ['root'], element: 'Fire', planet: 'Pluto', cards: ['the-tower']},
    {slug: 'ocean-jasper', name: 'Ocean jasper', aka: ['orbicular jasper'], colours: ['#8fd4c4', '#e8d0c9'], signs: ['Pisces', 'Cancer'], chakras: ['heart', 'solar-plexus'], element: 'Water', planet: 'Neptune', cards: ['the-star']},
    {slug: 'onyx', name: 'Onyx', aka: [], colours: ['#1a1a1a', '#2b2b2b'], signs: ['Leo', 'Capricorn', 'Aries'], chakras: ['root'], element: 'Earth', planet: 'Saturn', cards: ['the-emperor']},
    {slug: 'opal', name: 'Opal', aka: [], colours: ['#e8d8e0', '#c9d4e0', '#f0c9d4'], signs: ['Libra', 'Scorpio', 'Pisces'], chakras: ['crown', 'third-eye'], element: 'Water', planet: 'Venus', cards: ['the-star']},
    {slug: 'orange-calcite', name: 'Orange calcite', aka: [], colours: ['#e08e45', '#f0a860'], signs: ['Leo', 'Cancer'], chakras: ['sacral'], element: 'Fire', planet: 'Sun', cards: ['the-sun']},
    {slug: 'peacock-ore', name: 'Peacock ore', aka: ['bornite'], colours: ['#5c3f8c', '#2e7d8c', '#c9a227'], signs: ['Sagittarius', 'Pisces'], chakras: ['heart', 'third-eye'], element: 'Fire', planet: 'Uranus', cards: ['the-fool']},
    {slug: 'pearl', name: 'Pearl', aka: [], colours: ['#f0ece0', '#e8e0d4'], signs: ['Cancer', 'Gemini'], chakras: ['heart', 'sacral'], element: 'Water', planet: 'Moon', cards: ['the-moon']},
    {slug: 'peridot', name: 'Peridot', aka: [], colours: ['#8fae3f', '#a8c453'], signs: ['Leo', 'Virgo', 'Scorpio'], chakras: ['heart', 'solar-plexus'], element: 'Earth', planet: 'Sun', cards: ['queen-of-pentacles']},
    {slug: 'petrified-wood', name: 'Petrified wood', aka: [], colours: ['#6b4a2f', '#8a6240'], signs: ['Virgo', 'Capricorn'], chakras: ['root'], element: 'Earth', planet: 'Saturn', cards: ['the-hermit']},
    {slug: 'picture-jasper', name: 'Picture jasper', aka: [], colours: ['#a8845a', '#8a6a4a'], signs: ['Virgo', 'Taurus'], chakras: ['root', 'third-eye'], element: 'Earth', planet: 'Saturn', cards: ['the-world']},
    {slug: 'prehnite', name: 'Prehnite', aka: [], colours: ['#c4d4a8', '#a8c48a'], signs: ['Libra', 'Virgo'], chakras: ['heart', 'solar-plexus'], element: 'Earth', planet: 'Venus', cards: ['the-high-priestess']},
    {slug: 'pyrite', name: 'Pyrite', aka: ["fool's gold"], colours: ['#c9a227', '#e8c547'], signs: ['Leo', 'Aries'], chakras: ['solar-plexus'], element: 'Fire', planet: 'Mars', cards: ['king-of-pentacles']},
    {slug: 'red-jasper', name: 'Red jasper', aka: [], colours: ['#a8321f', '#8c2b1a'], signs: ['Scorpio', 'Aries'], chakras: ['root'], element: 'Earth', planet: 'Mars', cards: ['strength']},
    {slug: 'rhodochrosite', name: 'Rhodochrosite', aka: [], colours: ['#e08ca0', '#c9607a'], signs: ['Leo', 'Scorpio'], chakras: ['heart'], element: 'Fire', planet: 'Venus', cards: ['queen-of-cups']},
    {slug: 'rhodonite', name: 'Rhodonite', aka: [], colours: ['#c96b8c', '#2b2b2b'], signs: ['Taurus', 'Leo'], chakras: ['heart'], element: 'Fire', planet: 'Mars', cards: ['the-star']},
    {slug: 'rose-quartz', name: 'Rose quartz', aka: [], colours: ['#f0c9d4', '#e8b8c9'], signs: ['Taurus', 'Libra'], chakras: ['heart'], element: 'Water', planet: 'Venus', cards: ['the-empress']},
    {slug: 'ruby', name: 'Ruby', aka: [], colours: ['#8c1f2b', '#a8243a'], signs: ['Cancer', 'Leo', 'Scorpio'], chakras: ['root', 'heart'], element: 'Fire', planet: 'Sun', cards: ['queen-of-wands']},
    {slug: 'rutilated-quartz', name: 'Rutilated quartz', aka: ['angel hair quartz'], colours: ['#e8e0d0', '#c9a227'], signs: ['Gemini', 'Leo'], chakras: ['solar-plexus', 'crown'], element: 'Air', planet: 'Sun', cards: ['the-star']},
    {slug: 'sapphire', name: 'Sapphire', aka: [], colours: ['#1f3f8c', '#2e5aa8'], signs: ['Virgo', 'Libra', 'Sagittarius'], chakras: ['throat', 'third-eye'], element: 'Air', planet: 'Saturn', cards: ['the-hierophant']},
    {slug: 'selenite', name: 'Selenite', aka: [], colours: ['#f0ece0', '#e8e4dc'], signs: ['Cancer', 'Taurus'], chakras: ['crown'], element: 'Air', planet: 'Moon', cards: ['the-moon']},
    {slug: 'septarian', name: 'Septarian', aka: ['dragon stone'], colours: ['#8a6a4a', '#c9c4b8'], signs: ['Gemini', 'Capricorn'], chakras: ['root', 'throat'], element: 'Earth', planet: 'Saturn', cards: ['wheel-of-fortune']},
    {slug: 'serpentine', name: 'Serpentine', aka: [], colours: ['#4a6b4a', '#6b8c5c'], signs: ['Gemini', 'Virgo'], chakras: ['heart', 'root'], element: 'Earth', planet: 'Mercury', cards: ['death']},
    {slug: 'shungite', name: 'Shungite', aka: [], colours: ['#1a1a1a', '#2b2b2b'], signs: ['Scorpio', 'Capricorn'], chakras: ['root'], element: 'Earth', planet: 'Saturn', cards: ['the-devil']},
    {slug: 'smoky-quartz', name: 'Smoky quartz', aka: ['cairngorm'], colours: ['#5c4a3a', '#7a6a5a'], signs: ['Capricorn', 'Scorpio'], chakras: ['root'], element: 'Earth', planet: 'Saturn', cards: ['ten-of-pentacles']},
    {slug: 'snowflake-obsidian', name: 'Snowflake obsidian', aka: [], colours: ['#1a1a1a', '#e8e4dc'], signs: ['Virgo', 'Capricorn'], chakras: ['root', 'third-eye'], element: 'Earth', planet: 'Saturn', cards: ['temperance']},
    {slug: 'sodalite', name: 'Sodalite', aka: [], colours: ['#2e3f8c', '#3f4fae'], signs: ['Sagittarius', 'Virgo'], chakras: ['throat', 'third-eye'], element: 'Air', planet: 'Mercury', cards: ['justice']},
    {slug: 'spinel', name: 'Spinel', aka: [], colours: ['#a8243a', '#8c1f2b'], signs: ['Leo', 'Scorpio'], chakras: ['root', 'heart'], element: 'Fire', planet: 'Mars', cards: ['strength']},
    {slug: 'spirit-quartz', name: 'Spirit quartz', aka: [], colours: ['#c9a8d4', '#e8c547'], signs: ['Pisces', 'Aquarius'], chakras: ['crown'], element: 'Water', planet: 'Neptune', cards: ['the-star']},
    {slug: 'stilbite', name: 'Stilbite', aka: [], colours: ['#e8c4b8', '#f0d8c9'], signs: ['Cancer', 'Pisces'], chakras: ['heart', 'third-eye'], element: 'Water', planet: 'Moon', cards: ['the-moon']},
    {slug: 'sugilite', name: 'Sugilite', aka: [], colours: ['#7a4fa0', '#8a5cb0'], signs: ['Pisces', 'Virgo'], chakras: ['third-eye', 'crown'], element: 'Water', planet: 'Neptune', cards: ['the-hanged-man']},
    {slug: 'sunstone', name: 'Sunstone', aka: [], colours: ['#e08e45', '#c9761c'], signs: ['Leo', 'Libra'], chakras: ['sacral', 'solar-plexus'], element: 'Fire', planet: 'Sun', cards: ['the-sun']},
    {slug: 'tanzanite', name: 'Tanzanite', aka: [], colours: ['#4a3f8c', '#5c4fae'], signs: ['Sagittarius', 'Scorpio'], chakras: ['third-eye', 'crown'], element: 'Water', planet: 'Jupiter', cards: ['the-world']},
    {slug: 'tigers-eye', name: "Tiger's eye", aka: [], colours: ['#a8741f', '#c9a227'], signs: ['Gemini', 'Leo', 'Capricorn'], chakras: ['solar-plexus', 'root'], element: 'Fire', planet: 'Mercury', cards: ['the-chariot']},
    {slug: 'topaz', name: 'Topaz', aka: [], colours: ['#e8c547', '#4a7cc4'], signs: ['Sagittarius', 'Scorpio'], chakras: ['solar-plexus', 'throat'], element: 'Fire', planet: 'Jupiter', cards: ['the-sun']},
    {slug: 'tourmalinated-quartz', name: 'Tourmalinated quartz', aka: [], colours: ['#e8e4dc', '#1a1a1a'], signs: ['Capricorn', 'Scorpio'], chakras: ['root', 'crown'], element: 'Earth', planet: 'Saturn', cards: ['temperance']},
    {slug: 'tourmaline', name: 'Tourmaline', aka: [], colours: ['#2b2b2b', '#c9607a', '#4a8f5c'], signs: ['Libra', 'Capricorn'], chakras: ['root', 'heart'], element: 'Earth', planet: 'Mercury', cards: ['the-star']},
    {slug: 'turquoise', name: 'Turquoise', aka: [], colours: ['#3f9c9c', '#5fb8b8'], signs: ['Sagittarius', 'Aries'], chakras: ['throat'], element: 'Water', planet: 'Venus', cards: ['the-star']},
    {slug: 'unakite', name: 'Unakite', aka: [], colours: ['#6b8c5c', '#c9607a'], signs: ['Scorpio', 'Taurus'], chakras: ['heart', 'root'], element: 'Earth', planet: 'Venus', cards: ['temperance']},
    {slug: 'vanadinite', name: 'Vanadinite', aka: [], colours: ['#c9481f', '#a8321f'], signs: ['Scorpio', 'Virgo'], chakras: ['sacral', 'root'], element: 'Fire', planet: 'Mars', cards: ['the-chariot']},
    {slug: 'variscite', name: 'Variscite', aka: [], colours: ['#8fc48a', '#a8d4a0'], signs: ['Taurus', 'Virgo'], chakras: ['heart'], element: 'Earth', planet: 'Venus', cards: ['the-star']},
    {slug: 'watermelon-tourmaline', name: 'Watermelon tourmaline', aka: [], colours: ['#e08ca0', '#4a8f5c'], signs: ['Libra', 'Taurus'], chakras: ['heart'], element: 'Earth', planet: 'Venus', cards: ['the-lovers']},
    {slug: 'zircon', name: 'Zircon', aka: [], colours: ['#cfe3f0', '#e8c547'], signs: ['Capricorn', 'Virgo'], chakras: ['root', 'crown'], element: 'Earth', planet: 'Saturn', cards: ['the-world']}
  ];
  return {chakras, crystals};
});
