/* Traditional symbol names; original Ishtar Insights interpretations and prompts. */
(function(root, factory) { const data = factory(); if (typeof module === 'object' && module.exports) module.exports = data; else root.DivinationData = data; })(typeof globalThis !== 'undefined' ? globalThis : this, () => {
  const parse = text => text.trim().split(/\r?\n/).map((line, id) => { const [name, symbol, keyword, meaning, prompt] = line.split('|'); return {id, name, symbol, keyword, meaning, prompt}; });
  const lenormand = parse(`
Rider|rider|News|Something is arriving: a message, visitor or fresh piece of information. Make room to receive it before deciding what it means.|What news needs a thoughtful response rather than an immediate reaction?
Clover|clover|Opportunity|A small opening may be easy to overlook. This card invites a modest experiment rather than a gamble on a guaranteed outcome.|What low-stakes opportunity could I try while it is available?
Ship|ship|Distance|Travel, trade and longing widen the horizon. Distance can offer perspective, but moving away does not automatically resolve what travels with you.|What am I moving toward, and what would I carry with me?
House|house|Home|Home represents your base: routines, belonging and the structures that make life feel held. Look at the quality of that foundation.|What would make my everyday environment more supportive?
Tree|tree|Roots|Slow development asks for steady care. Think about habits and connections that grow over time, without reading the tree as a medical diagnosis.|Which small habit would I like to see take root?
Clouds|clouds|Uncertainty|Visibility is limited. Separate what you know from what you are guessing, and avoid turning a temporary lack of clarity into a fixed conclusion.|What information would help clear this confusion?
Snake|snake|Complexity|A situation may have a winding route or competing interests. Attend to boundaries and observable behavior rather than assuming hidden betrayal.|Where would a more careful route serve me?
Coffin|coffin|Ending|A chapter may need closure, rest or release. Treat this as a symbolic ending, never a prediction of physical death.|What has run its course, and how can I close it with care?
Bouquet|bouquet|Appreciation|Kindness, welcome and beauty can change the tone of an exchange. Notice what is offered freely and what you can genuinely appreciate.|Who or what deserves a specific expression of thanks?
Scythe|scythe|Decision|A clean cut can separate what is useful from what is no longer workable. Precision matters more than speed or dramatic gestures.|What boundary or decision needs a clear edge?
Whip|whip|Repetition|Repeated effort can become practice or friction. Notice whether returning to the same issue is developing skill or deepening a difficult pattern.|What repeated interaction needs a different approach?
Birds|birds|Conversation|Exchanges, chatter and shared concern fill the air. A direct conversation may be more useful than interpreting fragments or rehearsing worries.|What could I ask plainly instead of speculating about?
Child|child|Beginning|Something new needs room to learn. Simplicity, curiosity and small steps are useful; inexperience also benefits from support.|What would a beginner's first step look like here?
Fox|fox|Discernment|Practical intelligence helps you notice incentives and details. Check the fit between appearances and evidence without treating everyone as a threat.|What assumption should I verify before committing?
Bear|bear|Resources|Strength may appear through protection, authority or material support. Consider how power is held and whether your resources are being used sustainably.|Where can I be firm without becoming controlling?
Stars|stars|Direction|An orienting idea can help scattered efforts form a pattern. Inspiration becomes useful when translated into a concrete next step.|What guiding aim can I put into practice this week?
Stork|stork|Change|A shift is taking shape through movement, adjustment or renewal. Look for what can change gradually instead of expecting instant transformation.|Which change is ready for practical support?
Dog|dog|Trust|Dependability grows through consistent action. Consider friendship, mutual help and the difference between loyalty and losing your own boundaries.|Where is trust supported by what people actually do?
Tower|tower|Structure|Institutions, boundaries and solitude create distance. Structure can protect your time, while excessive separation may make support harder to reach.|Which boundary helps me, and which one isolates me?
Garden|garden|Community|Public spaces, networks and shared interests bring encounters. Choose where and how you participate rather than trying to belong everywhere.|Which community would benefit from my presence and contribution?
Mountain|mountain|Obstacle|A substantial difficulty calls for pacing, preparation or another route. Delay can be real without making the whole journey impossible.|What is the obstacle, and what is one workable way around it?
Crossroads|crossroads|Choice|Several routes deserve consideration. Clarify your criteria before treating indecision as a sign that there is no good choice.|Which value should guide the next decision?
Mice|mice|Erosion|Small drains on time, attention or resources can accumulate. Find the manageable leak rather than treating worry as proof of disaster.|What small loss of energy can I address today?
Heart|heart|Affection|Care, attraction and emotional investment deserve honesty. Let warmth coexist with the practical conditions a relationship or project needs.|How can I express care without ignoring my needs?
Ring|ring|Commitment|An agreement gains meaning through repetition and follow-through. Examine the promises being made, including the ones you have made to yourself.|What am I agreeing to, and is that agreement still clear?
Book|book|Knowledge|There is more to learn. Study and patient inquiry can help, while privacy reminds you that not every unanswered question is yours to resolve.|What can I learn responsibly before drawing a conclusion?
Letter|letter|Message|Written words make an exchange concrete. Look closely at the wording, context and practical response a message requires.|What needs to be written clearly or read more carefully?
Man|man|Person|Traditionally a male significator. Here it may represent you or another relevant person of any gender, chosen by context rather than assumed identity.|Whose perspective am I considering, and what do I actually know about it?
Woman|woman|Person|Traditionally a female significator. Here it may represent you or another relevant person of any gender; the card does not identify a stranger or predict a partner.|What would help me understand this person's stated needs?
Lily|lily|Maturity|Patience, peace and considered experience can soften urgency. Look for the response that respects both desire and longer-term values.|What would a calmer, more experienced response look like?
Sun|sun|Vitality|Visibility and energy can make progress easier to recognize. Let confidence support action without becoming a promise that nothing will go wrong.|Where can I put my available energy to good use?
Moon|moon|Recognition|Feeling, imagination and recognition color the situation. Notice the difference between meaningful appreciation and depending entirely on outside approval.|What contribution do I value even when it is not applauded?
Key|key|Opening|An important insight may make a next step more accessible. An opening still needs your judgment about whether and how to enter.|What practical action becomes possible with what I now understand?
Fish|fish|Flow|Money, exchange and movement of resources come into focus. Consider circulation and stewardship rather than reading this as a financial forecast.|Where would a clearer exchange of time or resources help?
Anchor|anchor|Stability|A steady point can support sustained work. Check whether staying put is giving you security or keeping you attached to an exhausted arrangement.|What is worth maintaining, and what could become more flexible?
Cross|cross|Responsibility|A burden, duty or matter of meaning asks to be acknowledged. Responsibility becomes more workable when chosen commitments are separated from unnecessary guilt.|Which responsibility is mine, and where could I ask for help?
`);
  const runes = parse(`
Fehu|ᚠ|Stewardship|Resources become useful through care and circulation. Notice what you have, what it costs to maintain, and how it can support a meaningful effort.|What resource can I use more deliberately?
Uruz|ᚢ|Strength|Strength includes endurance and the ability to work within your limits. Build capacity through manageable effort rather than proving yourself through exhaustion.|What would sustainable strength look like today?
Thurisaz|ᚦ|Boundary|A threshold asks for attention before action. Pause long enough to distinguish a useful protective boundary from an impulsive defensive response.|Where would a pause protect what matters?
Ansuz|ᚨ|Expression|Listen for language that clarifies rather than impresses. Learning, conversation and careful expression can change how a problem is understood.|What needs to be said or heard more clearly?
Raidho|ᚱ|Journey|Movement becomes a journey when direction and rhythm work together. Review your route and the agreements that help you travel with others.|What adjustment would make the next stage more workable?
Kenaz|ᚲ|Illumination|A focused light reveals detail. Craft, study and curiosity can make a vague idea easier to shape into something useful.|What skill or question would illuminate this situation?
Gebo|ᚷ|Exchange|A gift changes a relationship through the way it is offered and received. Look for reciprocity that leaves both people free.|What would a fair and freely chosen exchange involve?
Wunjo|ᚹ|Belonging|Joy can emerge from shared purpose and small satisfactions. Notice the relationships and practices in which you do not need to perform belonging.|Where do I feel both welcome and able to be myself?
Hagalaz|ᚺ|Disruption|An interruption may expose what needs protection or repair. Work with the actual conditions rather than demanding that everything continue as planned.|What can I stabilize while conditions change?
Nauthiz|ᚾ|Necessity|A constraint can clarify essentials. Start with what is needed, and avoid confusing a temporary limitation with your whole identity.|What is necessary now, and what can wait?
Isa|ᛁ|Stillness|A pause may preserve energy or reveal a stuck pattern. Give stillness a purpose, then decide what would signal readiness to move.|What can I notice when I stop pushing?
Jera|ᛃ|Season|Effort and outcome unfold on different schedules. Attend to repetition, timing and what can be tended now without forcing the harvest.|What cycle am I in, and what work belongs to it?
Eihwaz|ᛇ|Continuity|A dependable inner structure can help you meet transitions. Flexibility and persistence need not cancel one another.|What steady value can support me through this change?
Perthro|ᛈ|Uncertainty|Not everything is visible in advance. Leave room for discovery while taking responsibility for the choices you can make now.|What uncertainty can I allow without surrendering my judgment?
Algiz|ᛉ|Protection|Protection can be active and relational: asking for support, noticing limits and creating room to respond. It is a practice, not invulnerability.|What support or boundary would help me feel better resourced?
Sowilo|ᛊ|Clarity|A clear aim can gather scattered effort. Let confidence grow from what you can observe and practice rather than an expectation of guaranteed success.|What is the clearest useful action available to me?
Tiwaz|ᛏ|Integrity|A principle becomes real through a choice that honors it. Consider fairness, accountability and the cost you are actually willing to carry.|What would acting fairly require of me?
Berkano|ᛒ|Nurture|New growth benefits from shelter and repeated care. This is an invitation to cultivate, not a prediction of pregnancy or family events.|What emerging part of my life needs gentle attention?
Ehwaz|ᛖ|Cooperation|Shared movement depends on trust, communication and compatible pace. Discuss the route rather than assuming everyone wants the same destination.|Which agreement would improve our cooperation?
Mannaz|ᛗ|Humanity|Self-understanding develops alongside other people. Make room for your limits, contributions and the perspectives that challenge your assumptions.|What can I learn about myself through an honest exchange?
Laguz|ᛚ|Flow|Feelings can carry useful information without deciding every action. Give them room, then choose a channel that supports you.|What feeling needs acknowledgment before I act?
Ingwaz|ᛜ|Potential|Some efforts need a protected interval before they are shared. Gather resources and let development have its own pace.|What am I preparing that is not ready for display?
Dagaz|ᛞ|Perspective|A change in light can reveal another way to understand familiar circumstances. Try a new frame without dismissing what you already know.|What becomes possible if I reconsider the frame?
Othala|ᛟ|Inheritance|What you inherit may include place, stories, skills and expectations. Choose what to carry forward and what no longer fits your values.|Which inherited pattern do I want to preserve or revise?
`);
  const oracle = parse(`
The Lantern|1|Attention|You do not need to illuminate the entire road. Bring your attention to the part close enough to meet with care, and let that be sufficient for this step.|What deserves my full attention for ten minutes?
The Threshold|2|Readiness|An opening does not require an immediate crossing. Feel the difference between hesitation that protects you and delay that has become a habit.|What would help me enter this next chapter willingly?
The Well|3|Replenishment|Giving from a depleted place can make even meaningful work feel heavy. Return to something that restores capacity without asking you to earn the rest.|What reliably replenishes me?
The Thread|4|Connection|A small contact can hold a larger story together. Follow one thread of interest, care or unfinished conversation before seeking a complete pattern.|Which connection would I like to tend?
The Seed|5|Possibility|Potential asks for conditions, not applause. Choose a small beginning and give it light, time and a realistic place in your life.|What can I begin at a scale I can sustain?
The Mirror|6|Honesty|Look without rushing to praise or condemn. A useful reflection lets you see a pattern while remembering that you are more than that pattern.|What can I acknowledge without judging myself?
The Shore|7|Boundary|A boundary can be a place of meeting as well as separation. Decide what comes in, what goes out and where you need firmer ground.|What boundary would allow more ease?
The Ember|8|Devotion|A quiet interest may need tending rather than a dramatic reinvention. Protect a little time for what continues to matter when novelty fades.|What small act would keep this interest alive?
The Garden|9|Cultivation|Your attention shapes the conditions around you. Notice what you are feeding through repetition, and choose what deserves continued care.|What am I cultivating through my everyday choices?
The Vessel|10|Capacity|You cannot hold everything equally well at once. Choosing what belongs in your hands now can be a form of care for everything else.|What can I set down to hold this well?
The Window|11|Perspective|A wider view need not invalidate your experience. Invite a different angle and see which part of the picture becomes more understandable.|Whose perspective could broaden my own?
The Bridge|12|Repair|Connection may be rebuilt through a specific, proportionate action. A bridge requires willing ground on both sides; you need not construct it alone.|What repair is both possible and mutual?
The Nest|13|Shelter|Safety often grows from ordinary arrangements: a place to rest, a trusted person, a dependable routine. Honor the conditions that help you soften.|What makes rest feel more possible?
The Compass|14|Values|When every option has tradeoffs, a value can orient the choice. Choose a direction you can explain to yourself with honesty.|Which value should guide this decision?
The Rain|15|Release|Some feelings need room to pass through before they can be organized. Let expression be simple, and postpone the demand to make it meaningful.|What am I ready to let move through me?
The Mountain Path|16|Pacing|A worthwhile journey can include switchbacks. Break the effort into stages and measure progress by the ground you can actually cover.|What is the next manageable stretch?
The Loom|17|Integration|Different parts of your life may be asking to work together. Try combining two existing strengths before searching for a completely new answer.|What could I bring together in a useful way?
The Bell|18|Awakening|Something ordinary may be calling your attention again. Respond to the specific signal rather than waiting for certainty about the whole story.|What have I been noticing but not responding to?
The Hearth|19|Welcome|Warmth does not need to be elaborate. An invitation, a meal or an unhurried conversation can make care tangible.|How could I make someone, including myself, feel welcome?
The Open Hand|20|Allowance|Holding too tightly can make adjustment difficult. Release one demand about how the process must unfold while keeping your values in view.|Where could I allow more room?
The Orchard|21|Receiving|You may be more practiced at effort than receiving its results. Notice what has become available and let appreciation be part of the work.|What good thing can I receive without minimizing it?
The Still Lake|22|Presence|A quieter surface can help you notice what is already there. Give yourself a brief interval without needing it to solve anything.|What do I notice when I stop adding more input?
The Returning Bird|23|Renewal|Returning is not always going backward. You can revisit a place, practice or relationship with new information and different boundaries.|What would I like to return to differently?
The Morning Door|24|Choice|A fresh start can be a small decision made inside an ordinary day. Choose one action that makes the next hour more aligned with your intentions.|What would a beginning look like right now?
`);
  const figures = parse(`
Via|1111|Movement|The Way emphasizes change and passage. A flexible route may suit this situation better than an attempt to make every condition permanent.|Where can I allow a useful change of direction?
Populus|2222|Collective|The People emphasizes the surrounding group and its rhythms. Listen to shared experience while keeping your own judgment available.|What belongs to the group, and what is my own response?
Fortuna Major|2211|Lasting support|Greater Fortune suggests strength developed through sustained foundations. Look for the resources that remain useful after immediate enthusiasm passes.|What dependable support can I build upon?
Fortuna Minor|1122|Passing support|Lesser Fortune suggests help tied to a particular moment or condition. Use the opening thoughtfully while preparing to carry your own momentum.|How can I make good use of temporary support?
Conjunctio|2112|Meeting|Conjunction brings paths into contact. An exchange or combination may be useful if the terms and intentions are made clear.|What connection would make this situation more workable?
Carcer|1221|Containment|Prison points to restriction or a firm container. A limit may focus effort, but examine whether it is protective, chosen or ready to change.|Which limit needs acceptance, and which needs revision?
Acquisitio|2121|Gathering|Gain invites attention to what you are taking in. More is useful only when it serves a purpose you can sustain.|What is worth adding to my life now?
Amissio|1212|Letting go|Loss asks what can be released or spent. A chosen letting-go may create room, while an unwanted change deserves acknowledgment.|What can I release with care?
Laetitia|1222|Uplift|Joy brings an upward movement of spirit. Let encouragement support a real action rather than treating a good feeling as proof of an outcome.|What lifts my attention toward possibility?
Tristitia|2221|Grounding|Sorrow brings weight and stillness. Meet disappointment gently and look for practical support rather than forcing optimism.|What support would make this heaviness easier to carry?
Albus|2212|Composure|White suggests calm observation and measured response. A quieter approach can reveal distinctions that urgency has obscured.|What becomes clearer when I slow my response?
Rubeus|2122|Intensity|Red brings heat, appetite and agitation. Strong feeling asks for a constructive channel, especially before making an irreversible choice.|How can I give this intensity a useful outlet?
Puer|1121|Initiative|The Boy emphasizes directness and forceful beginnings. Courage works best when it includes awareness of consequences.|Where can I act decisively without rushing?
Puella|1211|Harmony|The Girl emphasizes attraction, ease and relationship. Seek an honest peace that does not require avoiding a necessary conversation.|What would make harmony more than an appearance?
Caput Draconis|2111|Entry|The Dragon's Head marks an opening and a movement inward. Consider what conditions would make a beginning welcome and sustainable.|What am I ready to let into my life?
Cauda Draconis|1112|Departure|The Dragon's Tail marks completion and a movement outward. Finish what needs finishing before carrying it into a new setting.|What ending would allow a cleaner beginning?
`);
  const parseHexagrams = text => text.trim().split(/\r?\n/).map((line, id) => { const [number, character, name, symbol, gloss, keyword, meaning, prompt] = line.split('|'); return {id, number:Number(number), character, name, symbol, gloss, keyword, meaning, prompt}; });
  const hexagrams = parseHexagrams(`
1|乾|Qián|111111|Six unbroken lines rising|Initiative|Heaven repeated beneath Heaven describes motion that renews itself without an outside push. Sustained effort, not a single burst, is what this image asks you to notice.|What sustained effort could I begin today without waiting for permission?
2|坤|Kūn|000000|Earth resting beneath earth|Receptivity|Earth doubled describes a capacity to hold and carry, not to initiate on its own. Strength here looks like patience, support, and the willingness to let another force lead first.|Where could steady support matter more than being first?
3|屯|Zhūn|100010|Seedling breaking through soil|Emergence|Beneath a covering of Water, Thunder stirs and pushes upward like a seedling in damp ground. Early growth can be slow and tangled without that meaning it will fail.|What early stage deserves patience rather than a verdict?
4|蒙|Méng|010001|A spring still finding shape|Inexperience|Near the foot of a Mountain, a spring rises with its course not yet cut into the rock. Not knowing the way yet is simply where learning starts, not a verdict on your ability.|What am I willing to learn slowly instead of pretending I already know?
5|需|Xū|111010|Clouds gathering, rain pending|Patience|Heaven waits beneath gathering Water, like clouds that have not yet released their rain. Preparation can continue even when the outcome cannot be hurried into view.|What preparation can continue while I wait for the right moment?
6|訟|Sòng|010111|Currents moving opposite ways|Contention|Heaven moves upward while Water beneath it flows down, two directions pulling apart from the start. Where interests diverge this sharply, a fair hearing matters more than winning.|What would a fair hearing of this disagreement actually require?
7|師|Shī|010000|Many currents held together|Discipline|Water collects beneath the surface of Earth, numerous and hidden until it is drawn on with purpose. Shared effort holds together only when its direction stays clear to everyone involved.|What shared effort needs clearer direction to stay coordinated?
8|比|Bǐ|000010|Earth drawing water close|Alliance|Water rests directly on Earth, filling every low place it can reach. Closeness like this forms around a shared center, and it thins wherever that center goes missing.|What shared center is holding this group together?
9|小畜|Xiǎo Chù|111011|A gentle, small restraint|Restraint|Above Heaven, Wind applies a gentle, persistent pressure instead of an outright stop. Small, repeated adjustments can shape a large momentum better than one dramatic correction.|What small, repeated adjustment could redirect this without forcing a stop?
10|履|Lǚ|110111|Treading carefully beneath heaven|Conduct|Careful footing matters when a Lake’s joy sits directly beneath Heaven’s vast reach. Attentive conduct, mindful of what is genuinely at stake, lets you move through a demanding situation without stumbling.|What careful step would let me move through this without losing my footing?
11|泰|Tài|111000|Heaven and earth exchanging|Exchange|Heaven’s energy settles below while Earth’s rises above it, so the two forces meet rather than pass each other by. Real exchange between different parties keeps a shared project alive.|Where would real exchange, not just proximity, help two sides meet?
12|否|Pǐ|000111|Earth and heaven apart|Separation|Earth settles low while Heaven rises further away, and the two no longer meet in the middle. When contact has thinned this much, small honest gestures matter more than large plans.|What small, honest gesture could open contact that has gone quiet?
13|同人|Tóng Rén|101111|Fire climbing toward heaven|Fellowship|Rising to meet Heaven’s wide reach, Fire here is a small light joining a much larger field. Genuine fellowship needs a shared aim broad enough to hold real differences within it.|What shared aim could hold our differences instead of erasing them?
14|大有|Dà Yǒu|111101|Fire held high above|Abundance|Fire burns high above Heaven, visible from every direction, holding a great deal in clear view. What you have gathered asks to be used generously rather than simply guarded.|What have I gathered that is meant to be shared, not just kept?
15|謙|Qiān|001000|A mountain kept low|Modesty|A Mountain, usually the tallest presence, sits here beneath Earth instead of above it. Real modesty is substance choosing not to announce itself, not an absence of worth.|Where could real substance speak instead of announcing itself?
16|豫|Yù|000100|Thunder rousing quiet earth|Momentum|Earth’s stillness breaks open as Thunder surges above it, releasing energy that had been building underneath. Shared enthusiasm can carry a group a long way, provided excitement is matched by real preparation.|Is the excitement here matched by preparation, or running ahead of it?
17|隨|Suí|100110|Thunder settling into lake|Following|Thunder, usually assertive, comes to rest beneath the openness of a Lake. Following well means adjusting your pace to real circumstances without losing track of your own direction.|Where am I adjusting to circumstances without losing my own direction?
18|蠱|Gǔ|011001|Wind stalled at mountain|Repair|Meeting a Mountain that will not yield, Wind gathers instead into something stagnant that needs attention. Old neglect rarely repairs itself, though it responds to patient, deliberate work.|What old neglect is ready for patient, deliberate attention?
19|臨|Lín|110000|Waters rising to meet|Approach|Drawing closer to Earth, a Lake rises toward what it will eventually reach. Influence that grows this gradually needs the same patience the water shows on its way up.|What influence is growing gradually and deserves patience rather than a push?
20|觀|Guān|000011|Wind moving over earth|Observation|Passing over Earth’s surface, Wind touches everything without settling anywhere in particular. A wide, unhurried view can reveal a pattern that closer inspection would miss.|What pattern becomes visible only from a wider view?
21|噬嗑|Shì Kè|100101|Thunder and fire biting|Resolve|Thunder’s force and Fire’s clarity combine like a decisive bite through something obstructing. Cutting through an obstacle works best when firmness and clear judgment are present together.|What obstacle needs both firmness and clear judgment to move through it?
22|賁|Bì|101001|Firelight against still mountain|Adornment|Fire’s light plays across a still Mountain, decorating its surface without changing what the mountain is underneath. Presentation can add real warmth, though substance still sits beneath the decoration.|Where does presentation matter less than what sits underneath it?
23|剝|Bō|000001|A mountain worn to earth|Erosion|A Mountain here rests almost directly on Earth, worn down until little holds its shape above the ground. When a structure has eroded this far, protecting what remains matters more than defending the whole.|What remaining part is worth protecting now that the whole has changed?
24|復|Fù|100000|Thunder waking beneath earth|Return|Small and already in motion, a single Thunder line stirs beneath a wide field of Earth. A turning point often starts this quietly, well before it becomes visible from the outside.|What quiet turning point might already be underway, even if unseen?
25|無妄|Wú Wàng|100111|Thunder moving under open sky|Spontaneity|Thunder moves freely beneath the open expanse of Heaven, acting without a hidden agenda behind it. Acting from a genuine motive, rather than calculation, changes how people experience your involvement.|What would acting from a genuine motive, without calculation, look like here?
26|大畜|Dà Chù|111001|Heaven contained by mountain|Accumulation|Holding back the vast energy of Heaven, a Mountain stores that force instead of releasing it. Great capacity, kept in check for a while, can be gathered into something more deliberate.|What capacity am I gathering that is not ready for release yet?
27|頤|Yí|100001|An open mouth, feeding|Nourishment|An open mouth takes shape here, Thunder moving at the base while a Mountain rests unmoving above it. What you take in, whether food, words, or influence, shapes you as surely as what you produce.|What am I taking in that shapes me as much as what I produce?
28|大過|Dà Guò|011110|A beam bowed by weight|Strain|A Lake’s weight bears down on Wind and Wood beneath it, like a beam sagging near its middle. When ordinary support is asked to carry more than usual, reinforcing the center matters most.|Where does the center need reinforcing before it carries any more weight?
29|坎|Kǎn|010010|Water repeated, depth doubled|Persistence|Water repeats beneath Water, one deep place opening into another below it. Moving through a genuinely difficult stretch works best one honest step at a time, trusting your footing rather than the whole distance.|What is the one honest next step, even without seeing the whole way through?
30|離|Lí|101101|Fire clinging to fire|Clarity|Fire needs something to cling to in order to burn, and here it repeats, brightness attached to brightness. Clarity, like flame, depends on what it has caught hold of and keeps alight.|What am I holding onto that keeps my thinking clear right now?
31|咸|Xián|001110|Stillness drawn toward openness|Resonance|A still Mountain and an open Lake sit close together, each affecting the other simply through presence. Mutual influence like this grows through genuine attention, not persuasion or pressure.|Where is genuine attention doing more than persuasion could?
32|恆|Héng|011100|Wind and thunder, steady|Constancy|Wind and Thunder move continuously, yet their pairing here describes something durable rather than erratic. What lasts is rarely still; it renews its own motion in a consistent direction.|What steady, renewing motion has kept this going so far?
33|遯|Dùn|001111|A mountain beneath open sky|Withdrawal|Heaven draws away above a Mountain that stays fixed in place, the distance between them widening. A timely, deliberate withdrawal can protect what matters more than contesting ground that is already shifting.|What would a timely, deliberate withdrawal protect right now?
34|大壯|Dà Zhuàng|111100|Thunder charging over heaven|Vigor|Thunder rides above the full strength of Heaven, considerable power moving with real momentum. Strength this available still needs a clear aim, since force without direction tends to break what it meets.|What clear aim would keep this strength from breaking what it meets?
35|晉|Jìn|000101|Fire rising over earth|Advancement|Fire rises above the level ground of Earth, like a light climbing steadily into view. Visible advancement here comes from consistent effort meeting a moment ready to recognize it.|What consistent effort is ready to be seen, if the moment allows it?
36|明夷|Míng Yí|101000|Light buried under earth|Concealment|Fire’s brightness sits beneath Earth here, its light held in rather than shown outward. Some understanding is better kept quiet for a while, protected until conditions can receive it.|What understanding might be safer kept quiet for now?
37|家人|Jiā Rén|101011|Fire tended by wind|Kinship|Wind feeds the Fire beneath it, each depending on the other to keep going. A household or close circle holds together through this same steady, mutual tending rather than through rules alone.|What mutual tending, not just rules, keeps this circle together?
38|睽|Kuí|110101|Fire climbing, lake settling|Divergence|Fire rises while the Lake beneath it settles downward, two natural movements heading in opposite directions. Real differences can still leave room for cooperation on the specific point where interests overlap.|Where do our different directions still overlap enough to cooperate?
39|蹇|Jiǎn|001010|Water blocked by mountain|Impasse|Water meets a Mountain squarely in its path and cannot continue straight ahead. A route that requires a detour is still a route, and finding allies for the crossing matters more than forcing it alone.|Who could help with this crossing instead of attempting it alone?
40|解|Xiè|010100|Thunder breaking over water|Release|After the charge of Thunder breaks loose above it, Water finally finds a way to move again. Once a difficulty starts to loosen, the next task is simply not to grip what has already let go.|What has already loosened that I could stop gripping so tightly?
41|損|Sǔn|110001|A lake feeding the mountain|Reduction|Giving up some of its depth, a Lake nourishes the Mountain rising above it. A deliberate reduction in one place, chosen rather than forced, can add real strength somewhere else.|What deliberate reduction here would add strength somewhere else?
42|益|Yì|100011|Wind lifting thunder higher|Growth|Reinforcing each other, Wind and Thunder amplify what each contributes on its own. Genuine increase tends to flow from what is shared generously rather than what is claimed for one side alone.|What shared benefit could grow if it were not claimed by one side alone?
43|夬|Guài|111110|A lake perched on heaven|Breakthrough|A Lake sits high above the great strength of Heaven, a small remaining obstacle held up by considerable pressure beneath it. A clear, well-supported decision can resolve what has lingered too long.|What lingering matter is ready for a clear, well-supported decision?
44|姤|Gòu|011111|Wind meeting open heaven|Encounter|Wind moves in beneath the full strength of Heaven, an unplanned meeting between very different forces. An unexpected encounter deserves clear attention, since its influence can spread further than its size suggests.|What unexpected encounter deserves closer attention than I have given it?
45|萃|Cuì|000110|A lake gathering over earth|Convergence|Collecting above the level ground of Earth, a Lake draws many small streams into one shared body. What gathers people together needs tending, or the shared purpose that formed it can quietly disperse.|What tending would keep this shared purpose from quietly dispersing?
46|升|Shēng|011000|Wind climbing through earth|Ascent|Pushing gradually upward through Earth, Wind and Wood advance without needing to force their way. Steady upward movement, like a growing tree, rarely announces itself loudly while it is happening.|What steady upward movement is happening quietly, without announcement?
47|困|Kùn|010110|A lake drained to water|Depletion|A Lake here has lost its water down into what lies beneath it, left with less than it needs to hold. When resources have thinned this much, honest acknowledgment matters more than pretending reserves remain.|What honest acknowledgment is overdue about thinning reserves?
48|井|Jǐng|011010|Wind drawing up water|Renewal|Wind and Wood reach down to draw Water up from below, a resource that renews itself as long as it is properly maintained. What supports many people works only if its upkeep is not neglected.|What shared resource needs maintenance before it can keep supporting people?
49|革|Gé|101110|Fire meeting standing water|Transformation|Fire and Lake stand in direct tension, heat against water, each capable of changing the other. Real transformation asks for timing and readiness, not just the wish that something old give way.|What would genuine readiness for this change actually look like?
50|鼎|Dǐng|011101|Wind feeding a flame|Refinement|Wind feeds Fire from below, the two together doing the work of a vessel that turns raw material into something nourishing. Refinement here takes deliberate heat and time, not a single quick change.|What deliberate process, given enough time, could refine this into something more useful?
51|震|Zhèn|100100|Thunder answering its echo|Alertness|Thunder repeats above Thunder, one shock followed closely by another. A sudden jolt can be unsettling and still leave you standing, provided you notice how quickly steadiness returns afterward.|How quickly does my steadiness tend to return after a sudden jolt?
52|艮|Gèn|001001|Two mountains, both still|Stillness|Resting upon a Mountain, stillness here is doubled, not divided. Genuine stillness is not the absence of activity around you but the choice to stay unmoved by it for a while.|What could I stay unmoved by for just a little longer?
53|漸|Jiàn|001011|Wind easing over mountain|Gradualness|Growing slowly up the side of a Mountain, Wind and Wood take the shape the slope allows rather than rushing past it. Progress made at this pace tends to hold its ground better than progress made in haste.|What is developing at its own pace that does not need to be rushed?
54|歸妹|Guī Mèi|110100|Thunder stirring a lake|Circumstance|Thunder moves above the openness of a Lake, a pairing shaped as much by circumstance as by choice. Entering a situation on someone else’s terms still calls for clear eyes about what you are agreeing to.|What terms, set by someone else, am I agreeing to without fully naming them?
55|豐|Fēng|101100|Thunder amplifying bright fire|Fullness|Thunder and Fire combine into something bright and considerable, a fullness near its own high point. Give full attention to what is genuinely present now, rather than assuming a peak like this holds itself in place.|What deserves full attention while this fullness is actually here?
56|旅|Lǚ|001101|Fire flickering over mountain|Transience|Fire moves across the surface of a Mountain without settling into any one place on it, the way a traveler passes through unfamiliar ground. Adaptability and courtesy serve you well when you are somewhere you do not yet belong.|Where am I still learning the customs of unfamiliar ground?
57|巽|Xùn|011011|Wind repeating, gentle pressure|Persistence|Wind repeats above Wind, the same gentle pressure applied twice over. What resists a direct approach can sometimes still be reached through patience that simply does not stop.|What could patience reach here that force could not?
58|兌|Duì|110110|Two lakes, shared joy|Openness|A Lake mirrors a Lake, openness meeting openness in both directions. Shared enjoyment deepens when it stays honest, rather than becoming a performance for whoever happens to be watching.|Where could shared enjoyment stay honest instead of becoming a performance?
59|渙|Huàn|010011|Wind scattering standing water|Dispersal|Wind moves across Water and scatters what had gathered into a single mass. Something rigid can be softened and redistributed this way, but the pieces still need somewhere useful to land.|Where do the scattered pieces of this need somewhere useful to land?
60|節|Jié|110010|Water contained by lake|Measure|Water rests within the bounds of a Lake that gives it shape rather than letting it spread without limit. A workable limit, chosen deliberately, tends to hold better than one imposed only after things went too far.|What deliberate limit would serve better than one imposed after the fact?
61|中孚|Zhōng Fú|110011|Wind over an open lake|Sincerity|Wind moves easily over the open surface of a Lake, nothing hidden between them. Trust this genuine tends to reach even people who are difficult to persuade by argument alone.|Where would genuine sincerity reach further than argument could?
62|小過|Xiǎo Guò|001100|Thunder passing a small mountain|Small measures|Thunder moves above a modest Mountain, a small and careful action better suited to this moment than a grand gesture. Attending to small details now matters more than reaching for something larger than the moment calls for.|What small, careful action fits this moment better than a grand gesture would?
63|既濟|Jì Jì|101010|Fire and water in balance|Equilibrium|Fire and Water sit in careful balance, each keeping the other in check rather than one overwhelming the other. A settled arrangement like this still needs ongoing attention, since balance is a practice and not a fixed achievement.|What ongoing attention does this settled arrangement still need?
64|未濟|Wèi Jì|010101|Fire above unsettled water|Threshold|Fire rises above Water here, close to the balance found in the previous image but not yet arranged the same way. Being unfinished is not a failure; it is simply where the next careful step still needs to be placed.|What careful next step would move this closer to its own balance?
`);
  const trigrams = [["Qián","乾","Heaven","111"],["Duì","兌","Lake","110"],["Lí","離","Fire","101"],["Zhèn","震","Thunder","100"],["Xùn","巽","Wind","011"],["Kǎn","坎","Water","010"],["Gèn","艮","Mountain","001"],["Kūn","坤","Earth","000"]].map(([name,character,image,symbol],id)=>({id,name,character,image,symbol}));
  const linePositions = [
    {id:0,title:"The beginning",text:"A hexagram’s lowest line marks a first, tentative movement that often goes unnoticed by anyone but you. What matters here is honest direction, not size or immediate recognition from other people."},
    {id:1,title:"The inner position",text:"The second line sits at the center of the lower trigram, close to home and away from outside pressure. Quiet, well-placed effort in familiar territory tends to matter more here than a visible, outward gesture."},
    {id:2,title:"The threshold",text:"The third line stands at the boundary between the lower and upper trigrams, an unsettled place neither fully inside nor outside. Transitions like this ask for caution and flexibility rather than a fixed plan."},
    {id:3,title:"Entering the outer",text:"The fourth line has just crossed into the upper trigram, closer now to influence and consequence beyond the immediate circle. Working carefully within someone else’s structure matters more here than asserting independence."},
    {id:4,title:"The position of authority",text:"The fifth line occupies the place of central authority within the upper trigram, the position a ruling figure classically holds. Responsibility exercised from here affects other people more than any other position in the hexagram."},
    {id:5,title:"The end, and excess",text:"The sixth and highest line has moved past the position of authority into a place where a quality can tip into its own extreme. Completion here calls for restraint, since what worked at the center can overreach at the summit."}
  ];
  // Grand Tableau: one sentence per house (position), index-aligned with lenormand. Each must
  // hold for any card that lands there, since it names the house's own domain, not the card's.
  const tableauHouses = [
    'In the house of the Rider — news, messages and things arriving from outside.',
    'In the house of the Clover — small opportunities and brief, easy interludes.',
    'In the house of the Ship — what is at a distance, or on the move.',
    'In the house of the House — home, family and the foundations a life rests on.',
    'In the house of the Tree — the body, and whatever grows or develops slowly.',
    'In the house of the Clouds — uncertainty, confusion and matters not yet clear.',
    'In the house of the Snake — complications, detours and other people’s influence.',
    'In the house of the Coffin — endings, rest and what has run its course.',
    'In the house of the Bouquet — invitations, kindness and small gestures of appreciation.',
    'In the house of the Scythe — quick decisions and clean, deliberate cuts.',
    'In the house of the Whip — repetition, friction and effort returned to again and again.',
    'In the house of the Birds — conversation, exchange and the chatter surrounding a matter.',
    'In the house of the Child — beginnings, small things and matters still learning their shape.',
    'In the house of the Fox — practical caution, discernment and the workplace.',
    'In the house of the Bear — strength, protection and how resources are held.',
    'In the house of the Stars — orientation, inspiration and a sense of wider direction.',
    'In the house of the Stork — change, transition and a shift already under way.',
    'In the house of the Dog — loyalty, friendship and dependable support.',
    'In the house of the Tower — institutions, structure and necessary distance.',
    'In the house of the Garden — public life, gatherings and shared spaces.',
    'In the house of the Mountain — obstacles, delay and ground that asks for patience.',
    'In the house of the Crossroads — choices, options and a decision still open.',
    'In the house of the Mice — small losses, wear and what quietly drains attention.',
    'In the house of the Heart — affection, feeling and emotional investment.',
    'In the house of the Ring — agreements, commitments and matters that repeat.',
    'In the house of the Book — study, hidden information and what is still to be learned.',
    'In the house of the Letter — documents, written words and the details they carry.',
    'In the house of the Man — a person of significance, considered here through their actions rather than an assumed identity.',
    'In the house of the Woman — a person of significance, considered here through their actions rather than an assumed identity.',
    'In the house of the Lily — maturity, patience and long experience.',
    'In the house of the Sun — vitality, visibility and energy that is easy to recognise.',
    'In the house of the Moon — recognition, feeling and the wish to be appreciated.',
    'In the house of the Key — openings, insight and a step that becomes possible.',
    'In the house of the Fish — money, exchange and the movement of resources.',
    'In the house of the Anchor — stability, steady work and what is worth maintaining.',
    'In the house of the Cross — duty, responsibility and matters that carry real weight.'
  ];
  // Geomantic house chart: reflective notes on the matters traditionally assigned to each house.
  const houseMatters = [
    {name: 'The Querent', matter: 'The querent themselves, and the shape of their present situation.'},
    {name: 'Resources', matter: 'Money, possessions and the resources the querent can draw on.'},
    {name: 'Siblings and Messages', matter: 'Siblings, neighbours, short journeys and the messages that pass between them.'},
    {name: 'Home and Foundations', matter: 'Home, land, family history and matters drawing towards their close.'},
    {name: 'Children and Pleasure', matter: 'Children, creative pleasure and the news that arrives.'},
    {name: 'Routines and Service', matter: 'Daily routines, working conditions and care freely given or received.'},
    {name: 'Partners and Agreements', matter: 'Partners, agreements and dealings with the other party in a matter.'},
    {name: 'Shared Resources', matter: 'Shared resources, debts and matters reaching their natural end.'},
    {name: 'Journeys and Belief', matter: 'Long journeys, study and the beliefs that give a life its wider shape.'},
    {name: 'Career and Standing', matter: 'Career, reputation and the exercise of authority.'},
    {name: 'Friends and Hopes', matter: 'Friends, hopes and the patrons who support them.'},
    {name: 'Retreat and Hidden Matters', matter: 'Hidden matters, retreat and the quieter difficulties a life holds.'}
  ];
  return {lenormand, runes, oracle, figures, hexagrams, trigrams, linePositions, tableauHouses, houseMatters};
});
