/* Original reflections for the six lines of each I Ching hexagram, bottom line first, keyed by
   King Wen number. Written for this site; not a translation. Conventions: docs/DIVINATION.md. */
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.IChingLines = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  const lines = {
    1: [
      'A dragon still hidden in the deep water has real strength with no stage yet to use it on. If your idea or ability has not found its moment, let it gather quietly instead of forcing a debut. Timing is part of the work here.',
      'Here the dragon surfaces in an open field, where it can be seen and met. Where your capacity is starting to show, look for someone whose experience could help you shape it. Being visible now is a chance to learn from others as much as to be recognised.',
      'Steady work, with a regular honest review of how it is going, suits this threshold where effort begins to be seen. If you are pushing forward, keep checking your footing as you go. Diligence without reflection can carry you past where you meant to stop.',
      'Picture a dragon that rises from the depths and hesitates before taking flight. At this edge of a wider world, both advancing and holding back are open to you, and either can be chosen in good faith. Let your own readiness, not outside pressure, settle which way you move.',
      'The dragon in open flight shows creative force at its fullest and most visible. From a place of real influence, your clarity can help others find their own direction. Consider who might benefit from what you can now see from above.',
      'A dragon that has climbed too high has left behind the ground that gave it strength. When momentum keeps pushing past the point of usefulness, a pause can restore what excess wears away. Ask whether going further serves the aim or only the habit of rising.',
    ],
    2: [
      'Frost underfoot hints that deeper cold is on its way. Small signs of a turning season tend to point to where things are heading. Notice what the early details are telling you before they become harder to change.',
      'The earth at this central place is plain and steady, content simply to be ground. When you act from your own settled nature, effort can feel lighter. Trust what comes naturally to you in territory you know well.',
      'Hidden brightness describes quality that does not need to be displayed to be real. If you are serving a larger effort, you can contribute fully without claiming the credit. Let the work carry its own weight for now.',
      'A sack tied shut keeps its contents safe and out of view. As you step into a wider circle, some discretion may protect what is still forming. Consider what is better held back for the moment rather than said aloud.',
      'A yellow lower garment, the colour of the centre worn modestly below, suggests authority held without show. Where you have real standing, a quiet and grounded manner can carry more weight than display. How might you lead in a way that keeps the focus on what matters?',
      'Dragons meeting in open country picture a receptive force that has pushed until it clashes with the active one. When yielding turns into rivalry, both sides tend to be worn down. Look at where holding your ground has become a contest nobody needs.',
    ],
    3: [
      'At the very start, hesitation can be a sensible response to tangled ground. Staying steady in your intention while gathering helpers gives an early effort somewhere firm to stand. Who could you ask to share the first stretch with you?',
      'A cart standing still with its horse unhitched pictures a start that keeps stalling. An offer that looks like an intrusion may turn out to be something else, and there is no need to accept or refuse in haste. Waiting for clarity is a legitimate choice at this central point.',
      'Chasing a deer into the forest without a guide leads deeper into unfamiliar thickets. If you are at a threshold without the knowledge you need, stopping is a form of wisdom rather than defeat. Consider what guidance would make the next move a sound one.',
      'Once more the horse and cart stand apart, and this time the line points towards finding a companion for the road. Asking for help is fitting when you are stepping into a wider sphere. Where could a partnership ease what you cannot move alone?',
      'Even with real influence, you may find generosity blocked by early conditions. Small, patient gestures may accomplish more here than a large push that the moment cannot hold. What modest step is possible even if the grand one is not?',
      'The horse and cart part again, and the image is one of weeping. When difficulties seem endless after a hard beginning, it may help to step back rather than keep straining. Grief over a stalled start is understandable, and it need not be the last word.',
    ],
    4: [
      'Early learning often needs some structure to take shape. Clear boundaries can help, provided they do not tighten into restriction for its own sake. Where would a light, fair framework help you or someone you guide begin?',
      'Patience with those who are still learning becomes a strength. Treating inexperience with kindness can let others grow into their own capability. How could you hold space for someone who does not yet know the way?',
      'The image here is of someone who loses their footing when dazzled by status or wealth. At a threshold, it is worth asking whether you are drawn to substance or to appearances. What would you choose if the shine were taken away?',
      'When you are lost in a tangle with no one near enough to help, learning can stall. The way ahead is harder without guidance nearby. Consider whether it is time to seek a teacher, a mentor or a trusted voice.',
      'Childlike openness, the inexperience that asks honest questions, is never out of place. Even when you hold authority, a willingness to learn keeps you receptive to what others know. Where could a beginner’s question serve you well?',
      'At the peak, the image turns to correcting folly with firmness. What is a boundary for, if not to keep growth possible? If you are setting one, ask whether it protects that growth or only expresses frustration.',
    ],
    5: [
      'Waiting in a distant meadow, far from the source of difficulty, allows ordinary life to continue. If what you are waiting for is still far off, keep to your steady routines. There is no need to spend energy on a problem that has not yet arrived.',
      'Waiting on sand, closer to the water, may bring a little gossip or friction. Staying calm and centred lets small disturbances pass without drawing you in. What would help you stay patient even when others are restless?',
      'Waiting in the mud at the water’s edge leaves you exposed and easily caught off balance. You may have moved closer than conditions allow. Consider whether a step back would give you firmer footing while you wait.',
      'A pit ringed by strife is the image here, and it calls for stepping out rather than enduring. As you enter a wider world, it is sensible to remove yourself from conflict you cannot resolve. Where might withdrawing be a wiser form of waiting?',
      'Waiting at a table of food and wine pictures rest and nourishment during an interval. From a settled place of influence, it can be fitting to recover strength while the outcome ripens. How could you use this pause to restore yourself?',
      'At the close of waiting come visitors nobody sent for. Rather than guarding against them, consider how you might receive them with respect and hear what they bring.',
    ],
    6: [
      'Early in a dispute, letting the matter drop after a few words can save much trouble. If a disagreement is only beginning, consider whether it is worth pursuing at all. Small concessions now can keep a minor issue from hardening.',
      'The image here is of someone who cannot win the contest and returns home to a small town. Retreating from a struggle you cannot sustain protects the people who depend on you. Where might stepping back be the stronger choice?',
      'Living on what you have long earned, and serving without seeking recognition, keeps a quiet dignity. If you are tempted to press for more, consider holding to what is already yours. Old, steady foundations can carry you through a tense moment.',
      'Picture a quarrel set down on the ground and left there. Taking up a different stance can matter more than holding your position. What would change if you let this contest go?',
      'Bringing the dispute before a fair arbiter sits well in this central place of authority. When you are in a position to judge or to seek judgement, fairness serves everyone involved. Who could offer an impartial hearing here?',
      'A leather belt awarded and then taken away three times in a day pictures a win that does not last. At the peak of contention, pressing a dispute to the end can leave little that holds. Ask whether the victory you seek would still feel worth it tomorrow.',
    ],
    7: [
      'Before any march, the ranks of an army are set in order. Clear structure and purpose give everyone something to follow. What agreements need to be in place before you begin?',
      'The commander who stays close to the ranks is the one trusted to lead. If you are guiding others, being present among them matters as much as your authority. How could your leadership stay grounded in the people you work with?',
      'Here a campaign bringing home its losses pictures command taken up without the fitness or authority to hold it. Notice whether whoever is leading has real readiness. Consider whether roles and responsibilities are clear enough.',
      'Withdrawing the troops to a safer position is a sensible choice when conditions do not favour advancing. When you move into a wider sphere, a strategic retreat can protect what you have built. Where might stepping back be wiser than pressing on?',
      'Game in the field calls for a response, and the task is to choose the right person to lead it. Entrusting the effort to someone experienced, rather than to whoever is eager, keeps the undertaking sound. Who is truly ready to carry this responsibility?',
      'Once the fighting is over, rewards and roles are handed out and a new order is set up. It matters here that those given lasting responsibility are suited to it. As one effort closes, consider who should shape what comes next.',
    ],
    8: [
      'An earthen bowl filled to the brim pictures sincerity that needs no decoration. In any alliance, honest intention is the first thing to offer. What would it look like to approach this connection with plain good faith?',
      'Holding together from within means a bond that grows from your own centre rather than from outside pressure. Loyalty that arises naturally tends to be steadier than one that is performed. Where does your sense of belonging come from?',
      'This line asks about the fit between you and the company you keep. At a threshold, it is worth asking whether a connection supports your direction or pulls you off it. Consider which of your current alliances truly suit you.',
      'Holding together outwardly means turning openly towards someone worthy of support in the wider world. Showing your loyalty clearly can strengthen a bond that matters. Who deserves your visible support now?',
      'A ruler hunting on three sides leaves the fourth open, so whatever wishes to go may go. A connection built on free choice holds better than one enforced. How could you invite closeness without pressing for it?',
      'A gathering with no shared centre is the image. When the moment for joining has passed, a union formed too late can struggle to hold. Ask whether this bond still has a centre worth rallying to.',
    ],
    9: [
      'Returning to your own path is the natural first move when you meet a gentle check. If something small is holding you back, going back to basics can restore your footing. Feel free to retrace a step you know well.',
      'Turning homeward in company with others who share your aim gives the return a quiet strength. At this central place, you need not push forward alone. Who is turning back with you, and what might you learn together?',
      'Spokes breaking loose from a cart’s wheels picture a vehicle that cannot move, and at home a quarrel between partners. Forcing progress against small resistance can damage what carries you. Consider whether a pause would prevent a larger breakdown.',
      'Honesty can ease a tense exchange where pressure has been building. As you step into a wider sphere, a plain word may do what force cannot. What would change if you said openly what you want?',
      'Bonds of trust, shared generously with neighbours, turn a small store into common wealth. From a place of influence, openness with those around you can multiply what you hold. How could you share your resources in a way that strengthens connection?',
      'The long-gathering clouds have finally broken into rain. When an effort of restraint reaches its aim, this is a time to let things settle rather than press further. What would it mean to leave a finished effort as it is?',
    ],
    10: [
      'Simple, unadorned conduct is enough to take a first step. If you are beginning something, going forward in your own plain way needs no justification. Let your intentions stay clear and uncomplicated.',
      'An easy, even path suits someone who walks quietly and independently. At this central place, keeping your own counsel can let you move without entanglement. What would it mean to travel your path without needing anyone’s approval?',
      'The image here is of someone who sees with one eye and walks with a limp yet treads on a tiger’s tail. Overestimating your readiness can provoke a sharp response. Consider whether your confidence matches your actual footing.',
      'A foot set on a tiger’s tail is the image at this step outward. When the ground is this demanding, small, deliberate steps are what the moment asks for. Where might a measured pace be your best protection?',
      'Decisions taken from the seat of authority carry weight, and their cost deserves a clear look. Confidence is useful here as long as it does not become careless. How can you remain decisive while keeping the risks in view?',
      'Looking back along the road you have travelled shows where your steps have led. That trail is worth studying. What does the path behind you suggest about the path ahead?',
    ],
    11: [
      'A clump of grass lifted with its tangled roots draws up more than a single blade. When a favourable time opens, others who share your aim may move with you naturally. Who might be ready to begin alongside you?',
      'At the inner centre, the line asks for a patience wide enough to hold both the rough and the distant. Generosity that includes everyone keeps a good time from narrowing into a clique. Where could you widen your circle without losing your balance?',
      'Even level ground eventually tilts, and settled conditions can turn. Awareness that good times shift can steady you rather than worry you. How might you stay faithful to what matters while conditions change?',
      'Birds settling side by side on a branch picture people meeting as equals. An unguarded manner invites trust. What could you share simply, without making it a show?',
      'A ruler giving a daughter in marriage to someone of lower rank shows authority that bends willingly for the sake of union. From a place of influence, stepping down to meet others can deepen harmony. Where could you set aside status to honour a connection?',
      'With the city’s wall sinking back into its own moat, the season for open exchange is closing. It may be wiser to tend what lies nearest than to reach far. What could you quietly strengthen in the meantime?',
    ],
    12: [
      'A handful of grass pulled from the ground, roots still clinging together, pictures kindred spirits withdrawing as one. When the time is not open, stepping back with your allies can keep your aim intact. Who might you quietly align with while waiting?',
      'Putting up with the closed season, while others seek favour from those in power, is a real choice. Accepting a standstill without compromising yourself preserves your integrity. How can you stay true while the moment is closed?',
      'If a position has come before the substance to fill it, a private unease may be the first honest signal. Recognising that feeling can be a step towards change. What would it take to grow into such a place?',
      'Serving a purpose larger than your own interest can begin to turn a stalled time. Working alongside others towards that aim can open what was closed. Where might a wider purpose call on you?',
      'At this seat of influence, a new gain is best tied firmly to something deep-rooted, like a mulberry that holds its ground. Remembering how fragile an opening can be helps steady it. What would keep this turn from slipping back?',
      'A blockage overturned by effort brings the relief of things moving again. After a long closed time, change can arrive when it is actively sought. What could you do now to help things clear?',
    ],
    13: [
      'Fellowship at the gate means meeting others openly in a shared, public space. Openness without hidden aims gives a connection good ground. How could you welcome others without drawing lines too early?',
      'Fellowship confined to your own clan can turn into partiality. Loyalty to a familiar group may narrow your view. Consider whether your circle is open enough to include people who differ from you.',
      'Hiding weapons in the thicket and watching from a hill describes a group held apart by mistrust. Suspicion can keep a promised union from ever forming. What would it take to set down your defences?',
      'Climbing the wall but not attacking pictures someone who reconsiders a conflict before it starts. As you enter a wider sphere, recognising that a quarrel serves no one can turn you back towards fellowship. Where might a second thought open a better path?',
      'Here tears turn to laughter. From a place of influence, it may be worth persisting through a separation from people who belong with you. Who would you reach across a difficulty for?',
      'Fellowship in the open country, far from any settlement, is a connection that asks little and gives little. At the edge of a group, you may belong loosely without a strong shared aim. Consider whether this distance suits you or keeps you from something deeper.',
    ],
    14: [
      'When abundance is only beginning, a watchful simplicity protects it better than any display. What early care would suit what is starting to gather?',
      'A large wagon, able to carry a heavy load, pictures resources that can be put to real use. A wide capacity is best spent on moving things forward. Where could your means carry something worthwhile?',
      'Offering your means to a larger good gives abundance its fullest meaning. How could your resources contribute to something beyond yourself?',
      'Wealth that stays out of the spotlight draws less envy. As abundance becomes visible in a wider circle, a measured, unshowy manner can keep what you hold from becoming a burden. Consider where modesty might protect your position.',
      'Here, influence rests on warmth that keeps its bearing. Openness can draw others in while a quiet composure keeps order. How might you be both warm and steady?',
      'Abundance blessed from above is the image. Having much while staying humble can let that fullness be welcomed rather than resented. What would it mean to hold your plenty lightly?',
    ],
    15: [
      'Humility that does not notice itself can carry you across difficult ground. At the very start, a light and unassuming manner can take you further than a claim to importance. Where could quiet humility open a way forward?',
      'Modesty is simply part of a person’s bearing, with no effort spent on displaying it. Genuine humility needs no announcement. How might your manner speak for itself?',
      'Steady work that goes on without thanks pictures someone who does not trade on what they have done. Continuing without seeking praise keeps the work honest. What could you keep doing even if nobody noticed?',
      'Being modest in how you act, not only in how you speak, suits this step into a wider circle. Humility is not passivity; it can be the way you engage. Where might an open, unassuming move serve you well?',
      'Quiet influence can still act firmly when the moment needs it. Modesty and decisiveness can stand side by side. When is it right for a humble person to take a clear stand?',
      'A humble reputation is best put to work on setting your own house in order. Discipline applied first to yourself and your closest circle keeps humility from becoming mere talk. What in your own sphere needs attention before you look outward?',
    ],
    16: [
      'Enthusiasm that announces itself too loudly can draw attention before there is substance behind it. If you are excited about something new, let your energy build quietly first. What would it mean to let your work speak before your words do?',
      'Like a keel holding a boat steady, this central line marks the right moment and moves on it at once. Steadiness here helps you tell when to act and when to stop. Where might a clear, grounded response serve you better than being swept along?',
      'Taking your cue from those above can leave you stalled. If you are waiting for outside momentum, your own may go unused. Consider whether it is time to move under your own power.',
      'A clasp gathering loose strands of hair pictures the one who draws others together here. Confidence and sincerity can bring people in without any need to press. How could your steady conviction help others join in?',
      'A long-standing strain that continues without giving way marks this line. From a position of influence, pressure that never lets up can keep you from fully enjoying the moment, yet it may also keep you alert. What steady pressure might be worth understanding rather than simply resisting?',
      'Enthusiasm that has fooled itself can still change course. Seeing through the illusion, even late, allows a new direction. Where might an honest reassessment free you from misplaced excitement?',
    ],
    17: [
      'When the usual reference points shift, stepping beyond your familiar circle can be a way of finding who is worth following. An open gate invites conversation with people outside your habits. Notice whose company widens your view rather than simply confirming it.',
      'Holding on to the small and near can quietly cost you something larger and more lasting. Where an easy attachment pulls at you, ask what it asks you to give up. Choosing well here is less about loyalty than about proportion.',
      'Moving towards what is more substantial may mean letting a lesser attachment go. What you reach for can come within range, so keep your motive clear as you reach. A considered choice now shapes the kind of following that comes next.',
      'Once others begin to follow you, it is worth checking what they are really following. If gain starts to colour the connection, honesty about your aims keeps the path clear. Let sincerity, rather than advantage, set the terms.',
      'Trust placed in what is genuinely good becomes a steady guide. Consider where you can commit to excellence in others and let that commitment lead. Following at its best looks like faithfulness to a worthy aim.',
      'A bond grown so firm that it holds on by itself, like a devotion offered at a mountain shrine, closes this figure. Where a commitment has become this strong, ask how to honour it without letting it bind you rigidly. Loyalty this deep deserves both respect and occasional review.',
    ],
    18: [
      'Early repair of an inherited pattern, something handed down by those before you, tends to be the most workable kind. Where a habit or structure came to you already slightly spoiled, attentive work now can set it right. Care and alertness belong together.',
      'Some old neglect asks for a gentle hand rather than a firm correction. If the problem sits close to home, among people you care for, consider how to mend it without forcing the pace. Tact here is part of the repair.',
      'Pressing hard to correct an inherited fault can overshoot a little, leaving some friction behind. Where you feel the urge to fix everything at once, notice the cost of haste. The effort remains worthwhile, even if its edges are rough.',
      'Letting an old problem slide can feel kind or convenient for a while. At the entry to the outer world, tolerance of neglect tends to let it spread. Ask what gentle but real step would stop the drift.',
      'Repairing what was inherited, from this central place of authority, can draw support and recognition from others. Consider who might help carry this work, and where shared effort would make it lighter. Repair done openly often gathers allies.',
      'Stepping back from the business of the world to pursue a higher aim is the image. Where the repair work is done or no longer yours to do, a quieter, more personal purpose may call. Ask what you are serving when you are no longer serving the task.',
    ],
    19: [
      'Approaching together with others, from a shared intention, gives this beginning its strength. Where influence is starting to grow, keep your steps aligned with what is right rather than what is quick. A good start here is a joint one.',
      'The central line of the lower trigram meets growing influence with confidence and warmth. When conditions seem to welcome you, move forward while remembering that seasons change. Practise openness paired with foresight.',
      'An easy, sweet-talking approach can feel pleasant while offering little of substance. If you notice yourself relying on charm or comfort, a moment of honest concern can put things right. Care matters more here than ease.',
      'A complete and wholehearted approach meets people where they are. Consider where you can show up fully, without reservation or calculation. Genuine presence is its own kind of fitness.',
      'Wise approach suits the position of authority, knowing whom to trust and letting capable people do their work. Where you lead, ask how much you need to hold and how much to delegate. Discernment here is quieter than control.',
      'Generous, open-hearted approach reaches out even from a place of completion. Where your own work feels finished, consider what experience you can offer others who are still on their way. Notice where magnanimity can still be practised.',
    ],
    20: [
      'A child’s way of looking sees surfaces without grasping the pattern beneath. Seeing that way is natural enough in someone young, though anyone responsible for others may need a wider view. Notice where you are looking only at what is closest.',
      'Glimpsing the world through a narrow gap in a door gives a partial picture. If your view feels limited by where you stand, consider what lies beyond the frame. A small opening is a start, not the whole scene.',
      'Ask what your recent conduct suggests about going on or holding back. Consider what your recent choices reveal about the direction you are really taking. Honest self-observation steadies the next move.',
      'Here you can observe how a larger community is ordered and what it offers. Where you have a chance to contribute, weigh whether the setting welcomes your gifts. Being a good guest means watching before acting.',
      'The effects of your life on others become the clearest measure of it. Look at the people around you and what your example shows them. Contemplation here turns outward into responsibility.',
      'Seeing your own life almost from the outside, free of the need for position, is the vantage of the top line. Where you stand apart from the action, ask what your conduct looks like to a detached observer. This distance can bring a calm, clear accounting.',
    ],
    21: [
      'A small check early on, like feet held in stocks, keeps a first misstep from growing. If a minor correction arrives, consider it a kindness rather than a setback. Little limits now can save larger trouble later.',
      'Biting through tender meat so easily that the nose sinks in shows force that overshoots what was needed. Where the obstacle is soft, a lighter touch may be enough. Notice when zeal outpaces the task.',
      'Old, dried meat can leave a bad taste when bitten, much as an old grievance does when finally addressed. Some unpleasantness may come with resolving a long-held issue. It is still worth working through, with patience for the aftertaste.',
      'Gristly dried meat with a metal arrowhead inside describes a hard obstacle that also yields something of value. As you enter the outer world, firmness and steady effort through difficulty matter. Keep the hardness of the task in view without losing heart.',
      'Biting through lean dried meat and finding yellow gold suggests a measured, central firmness. Fairness combined with resolve can cut through what remains. Stay alert, and let judgement rather than temper guide the bite.',
      'Picture someone so fixed in their course that they no longer hear, their ears hidden by a wooden collar. When warnings stop getting through, it is worth pausing to listen again. Excessive hardness can close off the very information needed.',
    ],
    22: [
      'Adorning your feet and choosing to walk rather than ride is a modest beginning. Where an easier, more showy path is on offer, consider whether walking suits your purpose better. Simplicity keeps you honest.',
      'Grooming a beard is decoration that follows the shape of the face beneath it. Adornment works best when it serves the substance it rests on. Ask what your presentation is really following.',
      'Something glows and gleams with ornament, pleasant and even a little intoxicating. If charm is carrying you along, keep a steady hold on what is lasting. Grace remains useful when it does not replace substance.',
      'A white horse arrives, and its rider comes courting, not raiding. At the entry to the outer world, plainness can be more welcoming than elaborate display. Consider whether simplicity would say what you mean more clearly.',
      'A garden on the hills, offered with only a modest roll of silk, describes a gift that looks small beside its setting. Sincerity can outweigh the size of what you give. Let the honesty of the gesture carry it.',
      'Adornment becomes plain white, ornament stripped back to its simplest form. Where decoration has run its course, notice what remains when it falls away. Simplicity here is a finish, not an absence.',
    ],
    23: [
      'The leg of a bed splitting shows erosion starting at the foundation. Notice where support is wearing away quietly beneath you. Where the undermining belongs to the season, noticing it matters more than insisting against it.',
      'Erosion now reaches the frame of the bed, closer to where you rest. Where support feels scarce, caution and patience are wiser than bold moves. Hold on to what is still sound.',
      'Stepping away from a group that is wearing things down can be right, even if it leaves you somewhat alone. Consider where you are being carried along by a decline you do not endorse. Separating from it can keep your integrity intact.',
      'Erosion reaches the skin in this line, close to the body rather than the surroundings. If the wearing-away reaches you personally, focus on protecting what is essential. There is little to gain from pretending the change has not arrived.',
      'A string of fish, orderly and led from the front, suggests a way of bringing order to what is receding. You can guide a decline towards something constructive. Grace in how things wind down is itself a form of leadership.',
      'One large fruit remains uneaten on the bare branch, holding the seed of what comes next. Where most has fallen away, look for the kernel still worth keeping. Renewal often begins with what the erosion could not reach.',
    ],
    24: [
      'Turning back after only a short distance is the gentlest kind of return. If you notice you have strayed a little, a quick correction costs very little. Early recognition keeps the path simple.',
      'A quiet, gracious return is made easier by good company. Consider whose example helps you come back to yourself. Humility makes the turning lighter.',
      'Returning again and again, after drifting away each time, is how some turnings go. Where a pattern of lapses and recoveries repeats, notice the effort each turning costs. Each return still counts, even if it is not the last.',
      'Leaving the group’s path on your own suggests a return guided by your own sense of what is right. Consider where you might need to part from the crowd. Going your own way here is steadiness, not rebellion.',
      'A wholehearted return means examining yourself honestly and without excuse. Consider where a sincere look inward would clarify what to change. Generosity towards yourself and others steadies the turning.',
      'The moment for returning has been missed, and confusion follows, like an army setting out without a clear road. If you feel lost, pause before pushing further in the same direction. Waiting until you can see the way is wiser than a forced advance.',
    ],
    25: [
      'Acting from a clear, uncalculating impulse is how this figure begins. Where your first instinct is honest and unforced, notice what happens when you follow it. Notice how simple a sincere start can be.',
      'Working the field for the work’s sake, with no eye on what it yields, is the image here. Attention to the task in hand matters more than counting the rewards. Consider what you might do if the outcome were not the point.',
      'A tethered ox, led off by a passer-by while its owner is elsewhere, is an image of loss that arrives without fault. Consider how you might respond if a setback arrives that you did not earn. Meeting it without bitterness keeps your footing honest.',
      'At the entry to the outer world, the task is simply to stay true to what you already know is right. If pressures pull at you, steadiness in your own integrity is enough. There is no need to add more.',
      'A trouble not of your own making arrives at the position of authority, and the image suggests leaving remedies aside. Where something has come unbidden, consider whether it needs any remedy at all. Overcorrecting can add to what was already settling.',
      'Even innocent action can run against the season when the figure reaches its end. If moving forward seems to meet only resistance, stillness may serve better than effort. Sincerity does not always mean acting now.',
    ],
    26: [
      'Difficulty ahead is the reason to hold back. Where you feel ready to push forward, consider whether stopping for now would preserve your strength. Restraint is not the same as retreat.',
      'Removing the axle straps from a cart means choosing not to travel for now. Stepping back voluntarily keeps energy intact for a better moment. Consider what you gain by pausing on purpose.',
      'Good horses running together suggest the time to move is approaching. Forward motion benefits from preparation and awareness of hazards. Keep training alongside advancing.',
      'A guard board fixed across a young bull’s horns prevents harm before the horns have grown. At the entry to the outer world, gentle early restraint is easier than later struggle. Consider where a small limit set now would spare effort later.',
      'The tusk of a gelded boar loses its threat because the force behind it has been changed at the root. Addressing the source of a problem works better than fighting its symptom. Ask where the real drive behind a difficulty lies.',
      'A road through the open sky is the image, and stored energy is finally released. Where you have held back long enough, notice that the way ahead may now be clear. Accumulation reaches its purpose when it moves.',
    ],
    27: [
      'Setting aside your own sacred tortoise to stare hungrily at someone else’s meal is the image here. Envy can make you overlook the resources you already hold. Consider what nourishment is already within your reach.',
      'Looking to a high place for sustenance can be tempting when your own resources feel thin. Notice whether that reliance is quietly pulling you off your own course. Self-sufficiency is worth rebuilding.',
      'Turning away from real nourishment towards quick gratification offers little that lasts. Where appetite rather than need is steering, a long pause may help. Ask what would actually sustain you.',
      'Seeking nourishment from above in order to feed others, with the steady, keen gaze of a tiger, is a legitimate reach. At the entry to the outer world, asking for support on behalf of others is fitting. Let the purpose keep the hunger honest.',
      'Leaning on someone wiser for sustenance departs from the usual way for a figure of authority. If a large task feels beyond you, staying steady and accepting guidance may be better than a bold crossing. Knowing your limits is part of leading well.',
      'Becoming the source from which others are fed is the situation here. Where others depend on you, carry that responsibility with awareness. Notice how that seriousness shapes what you feel able to take on.',
    ],
    28: [
      'Laying a mat of white rushes beneath what you set down is an image of extreme care. Where the load ahead is heavy, generous caution at the base makes sense. Preparation this careful is rarely wasted.',
      'A dry willow sending up new shoots at its root describes renewal in an unlikely place. An unexpected pairing or a fresh start can bring life to something tired. Notice where old wood is still growing.',
      'A ridgepole bending under too much weight shows strain pushed past its limit. If a structure is being forced to carry more than it can, the answer may be support rather than pressure. Stubbornness here only deepens the sag.',
      'A ridgepole braced and holding describes a load well supported. At the entry to the outer world, strength comes from staying linked to those who can help. Keep motives straightforward so the support remains sound.',
      'A dry willow putting out flowers but no new roots suggests a surface bloom without deep renewal. Notice where effort decorates rather than restores. Ask what would strengthen the root instead of the blossom.',
      'Wading on until the water rises overhead is the top line’s image of going beyond what the moment allows. Where you have committed to a cause past the point of prudence, pause to reconsider the depth. The intention may be admirable even when the crossing is too deep.',
    ],
    29: [
      'Sliding into a hollow within a hollow suggests difficulty starting to feel normal. Notice where familiarity with a hard situation has dulled your sense of direction. Recognising the pattern is the first step out.',
      'In a deep place, reaching for small, achievable gains is the practical way forward. You do not need to solve everything at once. Take the next modest step within reach.',
      'Hollows lie both ahead and behind, and every move seems to lead into another. Where no direction offers clear footing, stillness may be wiser than struggle. Let the footing show itself before moving.',
      'A plain offering of wine and rice passed in through a window describes sincerity offered simply. At the entry to the outer world, a modest, honest gesture can open a way through difficulty. Ceremony matters less than good faith.',
      'Water settling in a hollow, no higher than the hollow can hold, points to doing just enough. Getting through is the task, and anything grander can wait. Measured effort keeps you moving.',
      'Hemmed in by thorns for a long season, the figure has lost its way. If you feel caught in a tangle of your own making, patient reflection may loosen it. Look for the first thread that can be untangled.',
    ],
    30: [
      'Footsteps crossing in confusion at daybreak suggest many directions at once. A respectful, collected attention can bring order. Composure is the first light.',
      'A warm yellow light, balanced and central, is the image of the inner position. Where you find a measured clarity, let it guide you without extremes. Moderation shines steadily here.',
      'The light of the setting sun marks something drawing to a close. If an ending is in view, consider how to meet it with equanimity. Neither forced cheer nor loud lament suits this hour.',
      'A quick blaze with nothing to feed it describes brilliance that cannot sustain itself. At the entry to the outer world, notice where intensity may be outrunning its fuel. Steadier burning lasts longer.',
      'Tears flowing and deep sighs describe a heart that has truly understood something. Genuine sorrow over a mistake can lead to real change. Let sincere feeling here inform what you change.',
      'A ruler setting out to correct disorder, addressing its leaders while sparing those who merely followed, is the closing image. Where something needs discipline, aim at the root rather than at everything nearby. Clarity at its best is precise, not sweeping.',
    ],
    31: [
      'Influence felt only in the big toe is an intention not yet visible to anyone. A stirring may be real without having any effect yet. Notice it without acting on it too soon.',
      'Movement in the calves suggests an urge to walk before the moment has arrived. Waiting until the influence is clearer works better than moving on impulse. Stillness gives the connection time to form.',
      'Influence in the thighs follows whatever moves ahead of it, the restless position of the threshold. If you are going along with every prompting, consider whether this is truly your own direction. Restraint gives your choice back to you.',
      'The heart is the natural seat of this line, where a steady inner state draws others more than restless effort does. If your mind keeps darting about, notice how narrow the circle it reaches becomes. Consistency reaches further than agitation.',
      'Influence in the back of the neck sits deep and resists being moved. A firm resolve keeps you clear of impulse, though it may reach others less. Consider how to balance steadiness with openness.',
      'Jaws, cheeks and tongue carry the influence, which suggests talk rather than substance. Where words are doing all the work, ask what action would give them weight. Resonance lasts longer when it goes beyond speech.',
    ],
    32: [
      'Seeking permanence too quickly and too deeply puts strain on what is still forming. Where you want something to last, let it grow at its own pace. Early insistence can undermine durability.',
      'Unease lifts as effort comes to fit capacity. Consider where a moderate, sustainable pace would suit you better than an intense one. Proportion is a quiet form of constancy.',
      'Inconsistency of character leaves others unsure what to expect. If conduct shifts with every mood, notice the cost to trust. Steadiness of intention is what makes a person reliable.',
      'Hunting in a field with no game describes persistence in the wrong place. At the entry to the outer world, consider whether your effort is aimed where results are possible. Constancy works only when directed well.',
      'Steady adherence can suit a supporting role while a leading one may call for flexibility. Where you hold firm, ask whether the situation needs loyalty or adaptation. Constancy is not the same as rigidity.',
      'Constant stirring that never settles marks the top of this figure. Where you notice yourself always stirring, a pause may do more than further effort. Lasting things need stillness as well as motion.',
    ],
    33: [
      'At the tail end of a retreat, notice that the last to leave stands nearest to what is being left. Where a withdrawal is already underway, this is a place to keep still and avoid starting anything new.',
      'An image of something bound fast with yellow oxhide describes a commitment that holds while others pull away. If a purpose is worth keeping, hold it quietly and firmly rather than arguing for it.',
      'Ties to people who depend on you can slow a withdrawal that ought to be clean. Notice which obligations are truly yours to carry, and tend them without letting them decide the whole direction.',
      'Stepping back by choice, before anyone pushes, keeps your dignity and your options intact. The inner steadiness this asks for is easier to find when you are clear about what you are leaving and why.',
      'A withdrawal made at the right moment, courteously and without drama, can leave relationships in good order. From a position of responsibility, the manner of stepping back matters as much as the decision itself.',
      'Far along the path of retreat, little is left to hold you, and the distance itself becomes a kind of ease. Where you have already let go, enjoy the freedom it gives without looking back to argue the case again.',
    ],
    34: [
      'Strength gathered in the toes wants to rush ahead before the rest of the body is ready. Pushing forward on force alone tends to outrun your footing, so check your ground first.',
      'Kept within, power stays steady instead of showing off. Quiet consistency here does more than any display, and restraint is a good way to let your strength settle.',
      'A ram that charges a hedge ends up with its horns caught. When force meets resistance at a threshold, notice whether pressing harder is wisdom or simply habit, and consider holding your strength in reserve.',
      'Where the hedge gives way, the path opens without a struggle, and strength moves like the axle of a heavy cart. Entering wider circles, steady forward motion works better than a sudden push.',
      'Letting go of the ram’s stubbornness can be surprisingly easy once you see it clearly. From a place of authority, setting aside the need to prevail may cost far less than it might seem.',
      'Caught in the hedge, the ram can neither push on nor back out. If a situation has reached this kind of stalemate, admitting the difficulty openly is often what begins to loosen it.',
    ],
    35: [
      'Early progress may be met with doubt, and the trust of others has not yet arrived. Stay generous and even-tempered while it builds, since your direction does not need their approval to be sound.',
      'Sorrow can travel alongside real progress without cancelling it. Keep to the centre and stay open to care from an older, kindly figure, or from quarters you had not thought to look.',
      'Where many people share confidence in the direction, moving forward carries their agreement with it. Consensus can steady a step that would feel uncertain alone.',
      'An image of a hoarding squirrel describes advancing while clinging to more than you need. If progress at the edge of wider influence has turned acquisitive, ask what you are storing up and why.',
      'The invitation is to stop weighing every gain and loss. Acting with a clear intention matters more here than tracking whether each step pays off.',
      'Advancing with lowered horns, the energy of progress turns back towards your own house. Use firmness to set your own affairs in order rather than to press on others.',
    ],
    36: [
      'A bird lowering its wings in flight suggests leaving quietly while the light dims. Where you step away from a situation early, others may not understand, and going without a full explanation can be acceptable.',
      'Hurt in the left thigh, the traveller can still be carried by a strong horse. If something has slowed you, look for sturdy help, and put your energy into helping others through as well.',
      'Hunting in the south can bring the source of the darkness itself into view. Even when the cause is visible, change that runs deep is best made gradually rather than all at once.',
      'Close enough to see what lies at the core of a troubled situation, you can read it for what it is. From the edge of the outer world, that clear sight may be the cue to step away quietly while the way out is still open.',
      'Prince Ji kept his light inside while appearing to go along with a difficult court. From a place of responsibility, protecting your integrity may mean keeping your clarity to yourself for a while.',
      'A light that rose too high burns through its own fuel and goes dim. A darkness that has overreached has little left to feed on, and your task is to wait and keep your own light.',
    ],
    37: [
      'Clear boundaries in a shared household keep later tension from taking hold. Where a circle is newly forming, agree early on how things are to be done.',
      'Tending to meals and daily needs at home, one steady person can hold much together. Such a household favours quiet care over ambitious projects that pull attention outward.',
      'Sharp words and raised voices at home can leave everyone raw. If you must lean one way, fairness that errs towards firmness serves a household better than letting everything slide, though warmth still needs room.',
      'An image of someone who brings real wealth to the home describes a person who enriches the shared life. Notice how your resources, practical or emotional, strengthen the people around you.',
      'Influence at the heart of a household works best through affection rather than intimidation. From the place of authority, closeness and care do the work that rules alone cannot.',
      'Long service to a household earns respect when it rests on sincerity and self-examination. Look first at your own conduct, since dignity comes from honesty more than from rank.',
    ],
    38: [
      'A horse that has wandered off need not be chased, since it often finds its own way back. Early in a disagreement, allowing space and meeting even difficult people civilly can prevent a deeper split.',
      'Meeting someone important in a narrow lane suggests contact through an informal route. When the formal way is blocked, an unplanned conversation in the right spirit can do what an official meeting could not.',
      'A cart stuck fast with its team refusing to move makes for a bruising opening. Rough early going and a sound finish can belong to the same story, so keep faith with the direction even when obstacles pile up.',
      'Standing alone in a disagreement can feel colder than the disagreement itself. As you move outward, a single person you can rely on may change the whole temperature of the situation.',
      'An ally who cuts straight through what separates you shows how thin the barrier really was. From a position of responsibility, reaching towards someone of like mind is worth doing even if it looks unconventional.',
      'The image of a drawn bow slowly lowered belongs to suspicion that turns out to be a misreading. Check whether what you fear is real, since someone taken for a threat may be offering friendship.',
    ],
    39: [
      'Pressing ahead at the very start of an obstruction tends to entangle you further. Pausing here, and waiting for a better moment, can be the more respected choice.',
      'Some hardships arrive through duty rather than through any choice of yours, one difficulty following another. If you are carrying that kind of load, working through it for the sake of others is a meaningful choice.',
      'Facing a wall, turning back towards home and the people who rely on you makes sense. Return here is not failure but a way of staying where you are most needed.',
      'Joining forces before the crossing is worth more than any lone attempt at the far bank. As you enter wider circles, a pause to gather allies can turn a blocked road into a shared one.',
      'Whoever holds steady in the thick of a great obstruction becomes a point others can rally to. That steadiness draws helpers towards a common effort.',
      'Even at the very end of an impasse, simply walking away from the struggle is not the whole answer. Turning back towards the shared task, and seeking out someone of real stature, can open a larger way through.',
    ],
    40: [
      'Once a knot has just loosened, a period of quiet recovery is enough. There is little to do except rest and let the release settle.',
      'Three foxes caught in the field and a yellow arrow in hand describe clearing away cunning influences with straightforward means. Honest directness handles what flattery or evasion has tangled.',
      'Someone carrying a heavy load while riding in a fine carriage draws unwanted attention. Consider travelling lighter and letting your standing settle before you display it.',
      'Freeing yourself from the grip at your big toe means loosening a dependence on unhelpful attachments. As you move outward, trustworthy companions find it easier to approach once that space is clear.',
      'Only a genuine inner release frees a situation fully, and others tend to notice when it happens. From the place of authority, let go of what you have been holding and allow your change of heart to speak for itself.',
      'A single shot at a hawk on a high wall removes the last obstacle at the right moment. One well-aimed action can clear what still stands in the way, once the timing is ready.',
    ],
    41: [
      'Before you rush to help someone else, weigh how much you can spare without weakening yourself. Once your own work is in order, a quick and generous offering fits this beginning, provided it stays measured.',
      'Keeping to your centre, you can help others without giving away what is essential to you. If a request asks you to surrender something that matters at your core, declining can be the more useful gift.',
      'A group of three that settles into a pair describes how close bonds tend to form. Notice whether a crowded arrangement needs reducing, and whether going alone might bring the right companion.',
      'Lessening one of your own faults quickly can bring relief to the people around you. Trimming a habit that weighs on others is a reduction worth making.',
      'Help may arrive in a form too valuable to refuse, like a gift of ten tortoise shells. Accept real support gracefully when it comes, without having schemed for it.',
      'Some gains can be kept while leaving everyone else as well off as before. Where that is possible, share them widely, since benefit that serves the whole circle outlasts any private hoard.',
    ],
    42: [
      'Energy given from above can fuel a large undertaking. If support has come your way, put it towards work that matters, and do it well enough to justify the trust.',
      'Someone offers increase as valuable as ten tortoise shells, and it keeps arriving. Receive it with steadiness and a sense of reverence, keeping your intentions consistent over time.',
      'Even hardship can bring increase when it is met with sincerity. Carry your integrity openly, like a seal of office presented to a ruler, and let a difficult turn become useful.',
      'Walking the middle path and reporting faithfully to those in charge, you can serve as a bridge between people. Where larger changes are needed, like moving a whole settlement, trustworthy mediation makes them possible.',
      'Goodwill needs no testing or bargaining to be real. From a place of authority, offer kindness without asking what it might earn, and let it stand on its own.',
      'Increase that benefits only yourself tends to lose the goodwill that made it possible. At the peak, a fickle heart holds back what it could share, so make your generosity dependable while others still lean on you.',
    ],
    43: [
      'Power that has built up wants to move before the ground can bear it. Measure your readiness before you commit to a stand you cannot hold.',
      'A cry of alarm in the night finds someone already prepared. Vigilance and calm readiness make late surprises far easier to meet.',
      'Resolve showing in the jaw can make a stand look harsher than it needs to be. The image here is a lone walk through rain, and if people murmur about where you stand, quiet firmness serves better than open anger.',
      'Sore, skinless thighs make every step a struggle. Guidance that could ease the way is offered but not taken in. Notice whether restlessness is keeping you from hearing it.',
      'Uprooting a stubborn weed such as purslane calls for steady resolve rather than a burst of zeal. Stay in the middle way while dealing firmly with what has lingered.',
      'When no warning sounds, a small leftover problem can quietly return. Before calling a matter finished, check for what remains unresolved beneath the surface.',
    ],
    44: [
      'A bronze brake on a cart describes checking something at the moment it first appears. Where a small, restless influence is beginning to creep in, halting it early is far easier than later.',
      'Fish kept in a tank are contained rather than handed round to guests. A questionable influence is best managed quietly in your own care instead of spread to others.',
      'Hesitation makes each step awkward, like walking on sore legs. Uncomfortable as it is, the hesitation keeps you from a larger misstep, so let caution have its place.',
      'An empty fish tank suggests the connection with people below has slipped away. As you move outward, notice whether distance from those who rely on you has left you without their support.',
      'A melon sheltered beneath willow leaves describes worth kept hidden and allowed to ripen. Keep your integrity quiet and leave room for what ripens unseen.',
      'Meeting others with lowered horns keeps every encounter at a distance. Aloofness may protect you from unwanted influence, though it also closes off warmth worth considering.',
    ],
    45: [
      'Sincere intentions can falter when a crowd is confused about where it is heading. If you speak up honestly, a single gesture of reaching out can lighten the mood, so offer it rather than hold back.',
      'Joining because something genuinely pulls you, rather than through effort or strategy, keeps you steady. Let that natural attraction guide where you belong.',
      'Joining a group with sighs, as an outsider, can feel awkward and slow. Attaching yourself to someone already inside is a reasonable move, even if it costs a little pride.',
      'A great gathering around you invites trust when your motives are selfless. As you step into wider influence, check that the people drawn together serve a shared aim rather than your own standing.',
      'Holding a central place in a gathering does not mean that everyone trusts you yet. From the seat of authority, steady and lasting integrity is what reaches those who still hang back.',
      'Sighs and tears at the edge of a gathering describe feeling left outside the group. Voicing that distress honestly can be the first step towards being welcomed back.',
    ],
    46: [
      'Rising with the welcome of those above you gives an early climb real warmth. Trust offered by others is worth meeting with humble, steady effort.',
      'Sincerity carries more weight than display, so a modest offering is enough. Let an honest heart speak for itself as you move gradually upward.',
      'Climbing into an empty city, you meet no resistance at all. An unusually easy advance is worth taking while also asking what the openness means.',
      'An offering made at a sacred mountain describes a place of honour reached through devotion. As you enter the outer circle, serving something larger than yourself gives your rise its meaning.',
      'Ascending step by step keeps a climb steady and sure. Careful progress through each stage matters more than skipping to the top.',
      'Climbing blind means rising without seeing where the ascent ends. Keep going only with care and integrity, since ambition without sight can outrun its purpose.',
    ],
    47: [
      'A bare tree and a dim valley set the scene for gloom that feeds on itself. Avoid sinking deeper into low spirits, and look for one small source of light.',
      'Feeling hemmed in even while food and drink are plentiful points to a weariness that comfort cannot fix. Stay open to help from a person of standing, and let patient sincerity be the way you meet it.',
      'Leaning on thorns and pressing against stone describes seeking support in the wrong places. Notice whether a hard obstacle is best left alone, and whether the people you count on are really there.',
      'Help arrives only slowly, held back inside a golden carriage. Status or wealth may slow the aid you want to give, yet steady intent can still carry it through.',
      'Pressed from above and below, even someone in authority can feel hemmed in on all sides. A quiet, devoted focus leaves room for things to ease gradually.',
      'Tangled in creeping vines, you might hesitate and tell yourself that any move is a mistake. Recognising that thought for what it is lets you step out decisively.',
    ],
    48: [
      'Mud at the bottom of a neglected well offers no one a drink, and even animals pass it by. Notice whether a resource has been left untended so long that it no longer nourishes anyone.',
      'Water trickling out through a cracked jug, or used only to catch small fish, is spent on too little. Ask whether your gifts are being put to their best use or quietly leaking away.',
      'A well cleaned and full of clear water can still go undrawn. Water only helps once someone draws it, so consider how your offering can be recognised and shared.',
      'Repairing the stone lining of a well pauses its use for a while, yet the maintenance keeps it sound. As you enter wider circles, time spent looking after yourself is not wasted, even if no one drinks in the meantime.',
      'A clear, cold spring is ready for anyone who comes to it. A well-kept resource matters most when it is actually drawn upon and offered to others.',
      'Water drawn freely, with the well left uncovered, serves everyone who comes. Dependable generosity that stays open to all is the fullest expression of what this image offers.',
    ],
    49: [
      'An image of something bound tight in tough yellow hide suits a change that cannot move yet. The wish for change has stirred, but the ground for it has not yet been laid, so hold steady and let your reasons mature before acting on them.',
      'When the right day for change has arrived, preparation can give way to movement. A change that has been carefully considered can be carried forward with calm conviction.',
      'A proposal for change may need airing and testing repeatedly before others commit to it. Pushing ahead too hard can unsettle what you hope to improve, so listen for agreement before you move.',
      'Here the change begins to reach the wider world, and doubts can ease once your purpose is plain to see. Where people can sense the sincerity behind a shift, they tend to accept a new arrangement more readily.',
      'A tiger’s coat changing its pattern is the image for the one who leads a transformation from this place. When your aims are clear and openly held, others may trust the change before any result is visible.',
      'The leopard’s changing markings suggest a change that has already done its essential work. Now is a time to let the new pattern settle, since pressing for still more change could undo what has been gained.',
    ],
    50: [
      'The image is a cauldron tipped over to empty out what has gone stale. Clearing away old residue can be the first useful act, even if the start looks unconventional.',
      'A cauldron holding real food is the image here. Where you hold something of real substance, others may envy it, and quiet steadiness in your own place can keep it safe from interference.',
      'Picture a cauldron whose handles have shifted, so that its good contents cannot easily be lifted and shared. If your worth goes unrecognised for a while, patience may let the right conditions arrive, much as rain eases a long dry spell.',
      'A cauldron with a broken leg spills what it was meant to carry. As you step into wider responsibility, consider whether the load you have accepted is one your present support can bear.',
      'Yellow handles and golden rings describe a vessel that is easy to lift and fit to serve. From this central place, openness to good counsel lets what you hold reach the people it is meant for.',
      'The cauldron here is fitted with rings of jade, hard and gentle at once. Refinement is complete when strength and mildness work together rather than tipping into display.',
    ],
    51: [
      'Thunder arrives, and the first startled response can turn to relieved laughter. Letting the shock sharpen your attention, rather than unsettle you, is the beginning of steadiness.',
      'When a jolt threatens something you value, chasing after it may not be the wisest response. Seeking higher ground and letting time pass can let what matters find its way back.',
      'A shock that leaves you rattled can still become a spur to act more wisely. Is there a step you could take now that turns the jolt into movement?',
      'The image is thunder stuck in mud, its force dulled and slowed. Where a shock has left you bogged down, it may help to look for firmer footing before trying to push on.',
      'Shocks may come and go around you in the position of authority. Staying centred lets you keep hold of the work in hand, whatever the noise nearby.',
      'Looking wildly about serves no one. If trouble has reached those nearby rather than you, this can be the moment to steady yourself and step back, even if others talk.',
    ],
    52: [
      'Stillness begins with the toes, before any step has been taken. Pausing at the very start, before a movement gathers momentum, keeps your options clear.',
      'Stillness reaches the legs but no further. When you hold back while someone you follow moves on, you may not be able to change their course, and any unease about that is worth admitting honestly rather than hiding.',
      'Stillness forced upon the hips and lower back becomes rigidity rather than rest. Holding yourself too hard against movement can leave the heart tight and restless, so look for a gentler kind of pause.',
      'Here stillness reaches the trunk, the body itself at rest. Calming your own reactions as you step into the wider world can be a quiet and sufficient achievement.',
      'The image is a still jaw, words held until they can come in good order. From this place of influence, measured speech tends to carry further than a rush of talk.',
      'Stillness that has become part of your character is the crown of this hexagram. A generous and settled calm can steady more than yourself.',
    ],
    53: [
      'A wild goose first reaches the shoreline, the youngest bird still unsure of itself. Early steps may draw comment, but slow and careful progress is the right pace for a beginning.',
      'The goose settles on a broad rock, where there is food and room to rest. Where you have found secure footing, it is fitting to enjoy it and share what you have.',
      'On the dry plateau the goose is out of its element, and a journey pressed too far may not return as planned. Protecting what you already have may matter more than advancing.',
      'A goose that has flown up into a tree can still find a flat branch to rest upon. Entering unfamiliar surroundings, look for the modest foothold that lets you stay steady.',
      'Here the goose reaches the high ground, though what it hopes for may take a long time to come. Patient loyalty to your aims can outlast whatever delays and obstructs them.',
      'The goose flies beyond the peaks, and its feathers are used in a ceremonial dance. Your example may become something others take their bearings from.',
    ],
    54: [
      'The image is someone entering a household in a lesser role, like a walker with a limp who can still move forward. A modest position need not stop you from making steady, useful progress.',
      'Picture someone who sees with one eye, still able to perceive clearly. When circumstances limit you, quiet loyalty and inner clarity can serve better than seeking notice.',
      'Waiting may mean accepting a lower place than you had hoped for. Before you agree, consider what the terms really are and whether you can live by them.',
      'Delaying a commitment can be wise if the right moment has not yet come. The image is a match postponed until its proper time, and waiting of this kind can be deliberate rather than passive.',
      'A royal bride whose robes are plainer than her attendant’s is the image for this position of authority. Here dignity rests on modesty, like a moon not quite full.',
      'An empty basket and a ritual that yields nothing suggest a bond kept only as a form. If an arrangement has lost its substance, it may be time to ask what it still offers you.',
    ],
    55: [
      'In a time of abundance, you may meet someone whose strengths match your own. Spending time together as equals, for as long as the season lasts, is a fitting way to begin.',
      'The image is a screen so heavy that stars show at midday, brightness hidden behind it. Where pressing your case would only stir mistrust, steady sincerity may reach further than argument.',
      'Shade so deep that the smallest stars show in daylight marks the darkest point in this figure. If your capacity to act is curtailed, it may help to accept the limit and to work within it for now.',
      'Even behind a thick screen, the stars at midday can guide you towards a like-minded ally. Look for the person whose outlook matches yours and whose help you can return.',
      'Bringing capable people forward lets brightness spread beyond one person. Welcoming talent and good counsel can turn fullness into something widely shared.',
      'A grand house screened from its neighbours is the closing image, and behind the gate there is no one to be seen. When fullness turns into withdrawal, consider whom you have shut out.',
    ],
    56: [
      'Fussing over small change and minor grievances on the road can crowd out the journey itself. In unfamiliar ground, small-mindedness can close doors that dignity would keep open.',
      'The traveller reaches an inn with means to hand and a loyal companion found along the way. When you are settled in a modest, secure place, courtesy helps keep what support you have.',
      'The image is an inn catching fire and a companion lost through harsh treatment. A high-handed manner in someone else’s place can cost you the shelter you had.',
      'Here the traveller finds a resting place and the means to defend it, yet the heart is not fully at ease. A foothold in the wider world may still feel provisional, and that unease is worth acknowledging.',
      'A pheasant brought down at the cost of a single arrow is the image for this place of authority. A small outlay made with skill can earn recognition and a place among strangers.',
      'The image here is a bird whose nest catches fire, laughter turning to tears. If carelessness has cost the steady support you relied on, ask what a humbler bearing would restore.',
    ],
    57: [
      'Stepping forward and back without settling on either leaves gentle influence without direction. A soldier’s settled resolve is worth borrowing, so choose a direction and hold to it.',
      'The image is a search reaching under the bed, into corners where hidden influences gather. Patient, thorough looking in familiar places, perhaps with trusted help, can bring what is obscure into the open.',
      'Returning to the same question again and again can wear away your resolve rather than deepen it. Notice whether repeated reconsidering has become a way of not deciding.',
      'The image is a hunt that brings back game of three kinds, enough for every need. As you step into wider affairs, modest persistence can yield more than you expected.',
      'A change that begins unevenly can still be brought to a sound close through careful preparation. From this central position, consider the days before a change and the days after it, and let both guide your timing.',
      'Searching under the bed once too often, the seeker loses the tools that gave strength. Probing past the point of usefulness can leave you without the means to act.',
    ],
    58: [
      'Joy that arises from being at ease with yourself is the quiet start of this figure. Contentment that asks nothing from others is a sound place to begin.',
      'Where joy rests on sincerity, it keeps its footing even among doubtful company. Staying true in your own conduct lets pleasure remain honest.',
      'Joy that is sought from outside, reached for rather than found, sits uneasily. When enjoyment depends on what others supply, ask what you are giving up to get it.',
      'The image is a bargain still being haggled over, one pleasure set against another with no settled choice. Choosing the worthier kind of joy may bring the calm that bargaining cannot.',
      'An open door left to whatever slowly erodes deserves a closer look. Where openness is being taken advantage of, some watchfulness is a form of care.',
      'Joy can become something you are led along by rather than something you choose. If pleasure is drawing you further than you meant to go, pause and ask where it leads.',
    ],
    59: [
      'The image is help from a strong horse, arriving early. When scattering first begins, prompt support can restore order before the pieces drift too far apart.',
      'The image is a low table within reach, something solid to rest against while things scatter. The support to lean on may be close to home.',
      'Letting a narrow self-concern dissolve can free you for something larger. Putting your own interests aside for a while may be the wisest form of dispersal.',
      'Breaking up a close-knit faction can open the way to a wider gathering, like scattered stones forming a hill. As you enter the outer world, notice which small loyalties might give way to a broader common purpose.',
      'From the place of authority, a clear call can spread through a scattered group the way warmth spreads through the body. Sharing out what has been held in reserve can draw people together again.',
      'Stepping well clear of a situation that is doing damage is the image here. Where dispersal is the wise course, distance itself can be a form of protection.',
    ],
    60: [
      'Staying inside your own doorway while the way ahead is unclear is the first image of measure. Knowing when not to go out, and keeping your counsel, is a limit well chosen.',
      'Staying inside the gate when the moment calls for going out turns restraint into hesitation. Consider whether a limit that once served you has outlasted its purpose.',
      'Where nothing is held in check, the aftermath of overdoing it can feel heavy. If you have let things run beyond measure, the honest response is to own it and set a boundary now.',
      'A limit accepted with ease, rather than with strain, is one you no longer have to argue with. Measure that feels natural tends to last.',
      'The image is a sweet limit, one that others can accept because you live by it first. Restraint you practise yourself becomes an example worth following.',
      'A limit pressed until it turns bitter is the closing image. If strictness has begun to harm more than it helps, ease it, though there are times when a hard limit is still the right one.',
    ],
    61: [
      'Being inwardly prepared and settled is where sincerity begins. If your attention starts to split between other hidden aims, that steadiness can quietly slip away.',
      'A crane’s call carried across the shade is the image here. Feeling that is genuine reaches kindred people without being broadcast, and what you have to share can be offered plainly.',
      'Finding a partner or rival can send your mood lurching between exuberance and tears. Notice whether your steadiness depends on someone else.',
      'A moon that is nearly full, and a horse that leaves its pair, describe loyalty to a higher aim over a familiar bond. Entering wider responsibility, you may need to step apart from old companions to stay true.',
      'Sincerity binds people together as firmly as a clasped hand. Trust that is genuinely held can draw the whole group into accord.',
      'A rooster’s cry is sent skyward, a voice reaching beyond what its wings can carry. Where words outrun what has actually been done, bring them back to earth.',
    ],
    62: [
      'A young bird that takes flight before it is ready is the first image here. Stay close to the ground a while longer rather than soaring before you can sustain it.',
      'Being received by someone a step below the person you set out to reach describes an indirect route. Accepting a modest point of contact can be the right measure.',
      'Small precautions matter more than they seem, since what is not guarded against can come from behind. Take the extra care the moment asks for, even if it seems excessive.',
      'Holding back from going beyond your role, you may still meet what you need without seeking it. As you enter the outer world, stay alert and let steady restraint, not force, set your pace.',
      'Dense clouds from the west that do not yet bring rain describe potential not yet released. Look for capable help that has been out of sight, as a hunter reaches into a cave.',
      'The bird that flies past its mark and does not come to rest is the closing image. Overreaching when small steps were called for can leave you far from where you meant to be.',
    ],
    63: [
      'The image is a wheel braked and a fox that wets only its tail. With the crossing barely begun, holding back a little keeps momentum from carrying you too far.',
      'A lost carriage curtain is the image here, and chasing it is not the answer. What has been set aside can simply be left to rest.',
      'A long campaign against a distant land shows how much effort even a settled order can demand. Entrust such work only to people with the steadiness to see it through.',
      'Fine clothing wearing into rags, like a boat with leaks to be stopped, asks for attention that does not lapse from morning to evening. Keep an eye on small signs of wear before they grow.',
      'A modest offering made sincerely can mean more than a lavish display. The spirit of what you give counts for more than its size.',
      'The closing image is a crosser who goes in over the head. Looking back or pressing on too far can undo the balance just reached.',
    ],
    64: [
      'A young fox that wets its tail at the first step suggests a crossing started too soon. Wait until you can see how deep the water runs.',
      'Braking the wheels here is restraint chosen from a place of inner strength. Holding back until the timing is right keeps your readiness intact for when it is needed.',
      'Setting out before the crossing is prepared can stall midstream. Gather your resources first, and then a larger venture may become possible.',
      'Picture a long effort to set a distant land in order. Firm resolve is what sustained work of this kind asks for.',
      'At this central place, a steady light shows through, one others can rely on because it is genuine. From here, sincerity and a clear example can draw a scattered situation into order.',
      'Sharing a cup in good faith as completion nears is fitting, but drinking until the head goes under is not. Celebrate with measure so that confidence does not tip into carelessness.',
    ],
  };
  function forLine(number, index) {
    const set = lines[number];
    return Array.isArray(set) && Number.isInteger(index) && index >= 0 && index < 6 ? set[index] : null;
  }
  const has = number => Array.isArray(lines[number]);
  return {lines, forLine, has};
});
