/* Original reflective text for the Jyotish module. Traditional symbolism and
   significations offered for reflection; not predictions, not verdicts. */
const JyotishText = (() => {
  // Rashi order 0-11: Mesha, Vrishabha, Mithuna, Karka, Simha, Kanya, Tula,
  // Vrischika, Dhanu, Makara, Kumbha, Meena. Rulers follow the traditional
  // list: Mars, Venus, Mercury, Moon, Sun, Mercury, Venus, Mars, Jupiter,
  // Saturn, Saturn, Jupiter.
  const lagna = {
    0: {title:'A quick way of beginning', body:'Mesha lagna, ruled by fire-natured Mars, is traditionally associated with a fast, direct way of meeting the day, moving before the ground is fully mapped. The ram’s instinct favours action first and reflection afterward.', prompt:'Where would starting first serve you better than waiting?'},
    1: {title:'A steady, sensory pace', body:'Vrishabha lagna, ruled by Venus, is traditionally read through earth and fixity: a preference for what can be touched, tasted and trusted to remain. Patience and comfort are its natural register, built slowly and kept close.', prompt:'What are you building slowly enough to actually enjoy?'},
    2: {title:'A mind that keeps moving', body:'Mithuna lagna, ruled by Mercury, is traditionally associated with curiosity, conversation and an ease with more than one idea at once. Air and duality shape a rising sign that gathers information before settling on a view.', prompt:'Which question have you been circling without answering?'},
    3: {title:'A shell around something tender', body:'Karka lagna, ruled by the Moon, is traditionally read as protective and responsive, water in cardinal motion, quick to sense a room before entering it. Memory and care sit close to the surface here.', prompt:'What are you guarding until it feels safe to show?'},
    4: {title:'A presence meant to be seen', body:'Simha lagna, ruled by the Sun, is traditionally associated with warmth, dignity and a steady wish to be recognised for what is genuinely offered. Fire held in a fixed sign burns evenly rather than in bursts.', prompt:'What would you like to be known for doing well?'},
    5: {title:'An eye for what needs fixing', body:'Kanya lagna, ruled by Mercury, is traditionally read through earth and discernment, an attentiveness to detail that wants things done properly rather than merely finished. Service and precision come naturally to this rising sign.', prompt:'What small correction would improve everything around it?'},
    6: {title:'A search for the right balance', body:'Tula lagna, ruled by Venus, is traditionally associated with fairness, comparison and an instinct for weighing one thing against another before choosing. Air in cardinal motion keeps this rising sign alert to how others see things.', prompt:'Whose perspective are you weighing most heavily right now?'},
    7: {title:'A depth that takes its time', body:'Vrischika lagna, ruled by Mars, is traditionally read as intense and private, water held in a fixed sign, slow to trust and thorough once it does. What lies beneath the surface interests this rising sign more than what is shown.', prompt:'What have you been circling without looking at directly?'},
    8: {title:'A reach toward the horizon', body:'Dhanu lagna, ruled by Jupiter, is traditionally associated with an expansive outlook, fire and duality combining into a restless appetite for meaning and distance. Belief and exploration sit at the centre of this rising sign.', prompt:'Which larger question is worth your attention this season?'},
    9: {title:'A structure built to last', body:'Makara lagna, ruled by Saturn, is traditionally read as patient and disciplined, earth moved by cardinal ambition rather than haste. This rising sign favours a plan carried out in stages over a single decisive leap.', prompt:'What could you commit to working at slowly, for years?'},
    10: {title:'A view apart from the crowd', body:'Kumbha lagna, ruled by Saturn, is traditionally associated with independence and a fixed, air-born detachment that prefers its own reading of events to the expected one. Community matters here, but so does standing somewhat apart from it.', prompt:'Where would you rather trust your own judgement instead?'},
    11: {title:'A boundary that stays porous', body:'Meena lagna, ruled by Jupiter, is traditionally read as receptive and imaginative, water and duality merging into a rising sign that takes its bearings from atmosphere as much as fact. Compassion tends to travel easily across its edges.', prompt:'What are you sensing that you cannot yet explain?'}
  };

  const graha = {
    Sun: {theme:'identity, vitality and authority', body:'Surya, the Sun, is traditionally associated with vitality, self-expression and the confidence to occupy the position one holds. Classical texts read it as the soul’s own light, the core around which the rest of the chart turns.'},
    Moon: {theme:'the mind, feeling and instinct', body:'Chandra, the Moon, is traditionally read as the mind itself: memory, mood and the instinctive responses that arrive before thought catches up. It governs comfort, nourishment and the pull toward whatever feels familiar.'},
    Mars: {theme:'courage, drive and initiative', body:'Mangala, Mars, is traditionally associated with courage, energy and the will to act, the planet of initiative rather than deliberation. Classical texts connect it with siblings, land and the physical effort a task demands.'},
    Mercury: {theme:'intellect, speech and exchange', body:'Budha, Mercury, is traditionally read as intellect in motion: language, calculation and the quick adjustments that trade and conversation require. It is the planet of learning that moves between subjects rather than settling in one.'},
    Jupiter: {theme:'wisdom, expansion and guidance', body:'Brihaspati, Jupiter, is traditionally associated with wisdom, generosity and the expansive outlook of a teacher. Classical texts read it as the planet of growth, belief and the guidance that widens a narrow view.'},
    Venus: {theme:'harmony, pleasure and connection', body:'Shukra, Venus, is traditionally read as the planet of harmony, comfort and the arts, drawn toward what is pleasing to the senses. It governs affection, cooperation and the diplomacy that keeps a relationship workable.'},
    Saturn: {theme:'discipline, patience and structure', body:'Shani, Saturn, is traditionally associated with discipline, delay and the patience that only time can teach. Classical texts read it as the planet of structure, responsibility and the slow, exacting work of endurance.'},
    Rahu: {theme:'ambition, hunger and the unfamiliar', body:'Rahu, the north lunar node, is traditionally read as an unfinished hunger: ambition, obsession and a pull toward whatever lies outside ordinary experience. It has no physical body in the classical scheme, only direction and appetite.'},
    Ketu: {theme:'detachment, introspection and release', body:'Ketu, the south lunar node, is traditionally associated with detachment, introspection and a familiarity that arrived from somewhere the mind cannot quite place. Classical texts read it as the planet that quietly loosens what Rahu spent itself chasing.'}
  };

  // Nakshatra order 0-26: Ashwini, Bharani, Krittika, Rohini, Mrigashira,
  // Ardra, Punarvasu, Pushya, Ashlesha, Magha, Purva Phalguni, Uttara
  // Phalguni, Hasta, Chitra, Swati, Vishakha, Anuradha, Jyeshtha, Mula,
  // Purva Ashadha, Uttara Ashadha, Shravana, Dhanishta, Shatabhisha, Purva
  // Bhadrapada, Uttara Bhadrapada, Revati.
  const nakshatra = {
    0: {keyword:'swift beginnings', body:'Ashwini takes its symbol from a horse’s head and its deity from the twin Ashwini Kumaras, physicians who moved between worlds with unusual speed. It is traditionally associated with quick starts and a readiness to act before hesitation sets in.', prompt:'What are you ready to begin without further preparation?'},
    1: {keyword:'carrying something through', body:'Bharani’s symbol is the womb, and its deity Yama is traditionally read as the guardian of thresholds and endings that clear the way for what comes next. This nakshatra is associated with the effort of carrying something to completion.', prompt:'What are you determined to see through to the end?'},
    2: {keyword:'a cutting clarity', body:'Krittika’s symbol is a blade or flame, and its deity Agni, fire itself, lends this nakshatra a traditional association with sharp discernment and the will to burn away what no longer serves. Precision and purpose are its usual register.', prompt:'What could you see more clearly if you looked directly at it?'},
    3: {keyword:'steady growth', body:'Rohini’s symbol is a cart laden with growth, and its deity Prajapati is traditionally associated with fertility, patience and the slow accumulation of what will eventually ripen. This nakshatra favours what is grown carefully over what arrives quickly.', prompt:'What are you tending that isn’t ready to be rushed?'},
    4: {keyword:'a gentle searching', body:'Mrigashira’s symbol is a deer’s head, alert and searching, and its deity Soma is traditionally read as the wandering curiosity that moves toward whatever seems just out of reach. This nakshatra is associated with a soft, exploratory attention.', prompt:'What are you quietly searching for right now?'},
    5: {keyword:'weather that clears the air', body:'Ardra’s symbol is a single teardrop, and its deity Rudra, the storm, is traditionally associated with intensity that clears the air rather than merely disturbing it. This nakshatra is read as transformation arriving through difficulty rather than around it.', prompt:'What difficulty might actually be clearing something?'},
    6: {keyword:'a return to what matters', body:'Punarvasu’s symbol is a bow and quiver, ready again after use, and its deity Aditi, mother of the gods, is traditionally associated with renewal and a second chance at what was set down too soon. This nakshatra favours return over departure.', prompt:'What is worth returning to and trying again?'},
    7: {keyword:'quiet nourishment', body:'Pushya’s symbol is a cow’s udder, and its deity Brihaspati is traditionally associated with nourishment, guidance and the steady care that asks for nothing in return. This nakshatra is read as one of the more settled, sustaining placements.', prompt:'Who or what are you quietly sustaining right now?'},
    8: {keyword:'a penetrating instinct', body:'Ashlesha’s symbol is a coiled serpent, and its deities the Nagas are traditionally associated with a penetrating instinct that senses what is not yet said aloud. This nakshatra favours insight gathered quietly over insight offered freely.', prompt:'What have you sensed that you haven’t named yet?'},
    9: {keyword:'inherited authority', body:'Magha’s symbol is a throne, and its deities the Pitris, the ancestors, are traditionally associated with inherited authority and the weight of a lineage carried forward. This nakshatra is read as dignity earned partly by what came before it.', prompt:'What inheritance, spoken or not, are you carrying forward?'},
    10: {keyword:'ease enjoyed openly', body:'Purva Phalguni’s symbol is the front legs of a bed, and its deity Bhaga is traditionally associated with enjoyment, rest and pleasure taken without apology. This nakshatra favours comfort offered and received in equal measure.', prompt:'Where could you allow yourself more ease right now?'},
    11: {keyword:'quiet alliance', body:'Uttara Phalguni’s symbol is the back legs of a bed, and its deity Aryaman is traditionally associated with alliance, patronage and the steady support one person offers another. This nakshatra is read as dependable rather than dramatic.', prompt:'Whose steady support have you not properly acknowledged?'},
    12: {keyword:'skill in the hands', body:'Hasta’s symbol is an open hand, and its deity Savitr is traditionally associated with skill, craft and the satisfaction of making something with care. This nakshatra favours ability practised until it becomes nearly effortless.', prompt:'What craft would reward more deliberate practice?'},
    13: {keyword:'a brilliance worth shaping', body:'Chitra’s symbol is a bright jewel, and its deity Tvashtar, the divine craftsman, is traditionally associated with design, brilliance and the shaping of raw material into something distinctive. This nakshatra favours appearance matched by real skill.', prompt:'What are you shaping that deserves more attention to form?'},
    14: {keyword:'flexible independence', body:'Swati’s symbol is a young shoot bending in the wind, and its deity Vayu is traditionally associated with independence and a flexibility that survives what rigid things cannot. This nakshatra favours adaptability over a fixed position.', prompt:'Where would bending serve you better than holding firm?'},
    15: {keyword:'determined achievement', body:'Vishakha’s symbol is a triumphal archway, and its deities Indra and Agni together are traditionally associated with determined effort aimed at a visible goal. This nakshatra favours ambition pursued with focus rather than left to drift.', prompt:'What goal deserves a more determined, focused effort?'},
    16: {keyword:'devotion and friendship', body:'Anuradha’s symbol is the lotus, and its deity Mitra is traditionally associated with friendship, devotion and the loyalty that holds steady across distance. This nakshatra favours connections built slowly and kept with care.', prompt:'Which friendship deserves more of your attention lately?'},
    17: {keyword:'seniority and protection', body:'Jyeshtha’s symbol is a circular amulet, worn for protection, and its deity Indra is traditionally associated with seniority, responsibility and the burden of looking after others. This nakshatra favours the eldest role in any group it occupies.', prompt:'Where are you already the one others look to?'},
    18: {keyword:'getting to the root', body:'Mula’s symbol is a bundle of roots pulled from the ground, and its deity Nirriti is traditionally associated with dissolving what is inessential to reach what is foundational. This nakshatra favours investigation that goes all the way down.', prompt:'What would you find if you kept asking why?'},
    19: {keyword:'an early, clean victory', body:'Purva Ashadha’s symbol is a winnowing fan, and its deity Apas, the waters, is traditionally associated with purification and an early, invigorating sense of momentum. This nakshatra favours conviction gathered quickly and held with confidence.', prompt:'What conviction are you ready to act on early?'},
    20: {keyword:'a lasting achievement', body:'Uttara Ashadha’s symbol is an elephant’s tusk, and its deities the Vishvadevas, the universal gods, are traditionally associated with achievement built to outlast the moment it was made in. This nakshatra favours the long, unglamorous middle of a project.', prompt:'What are you building that should be made to last?'},
    21: {keyword:'careful listening', body:'Shravana’s symbol is an ear, or three footprints marking a path, and its deity Vishnu is traditionally associated with listening, learning and the steady following of a well-chosen course. This nakshatra favours attention over assertion.', prompt:'What would you learn if you listened more than you spoke?'},
    22: {keyword:'shared rhythm', body:'Dhanishta’s symbol is a drum, and its deities the Vasus are traditionally associated with rhythm, music and an abundance measured through what is shared rather than kept alone. This nakshatra favours effort that finds its beat alongside others.', prompt:'Where would working in rhythm with others help most?'},
    23: {keyword:'vast, quiet healing', body:'Shatabhisha’s symbol is an empty circle, and its deity Varuna, keeper of the cosmic waters, is traditionally associated with vastness, mystery and a hundred remedies for what troubles the body. This nakshatra favours solitary, unhurried repair.', prompt:'What are you healing from in your own time and way?'},
    24: {keyword:'fierce, single-minded intensity', body:'Purva Bhadrapada’s symbol is a sword, and its deity Aja Ekapada, the one-footed goat, is traditionally associated with fierce, single-minded intensity aimed at a single point. This nakshatra favours conviction that does not divide its attention.', prompt:'What deserves your full, undivided attention right now?'},
    25: {keyword:'a calm beneath the surface', body:'Uttara Bhadrapada’s symbol is a pair of twins, and its deity Ahir Budhnya, the serpent of the deep, is traditionally associated with a calm that holds considerable strength beneath it. This nakshatra favours quiet endurance over visible effort.', prompt:'Where is your strength showing up as calm rather than action?'},
    26: {keyword:'safe passage', body:'Revati’s symbol is a fish swimming in boundless water, and its deity Pushan, guardian of journeys, is traditionally associated with nourishment and safe passage to a destination not yet in sight. This nakshatra favours gentle guidance over forceful direction.', prompt:'What passage are you being asked to move through gently?'}
  };

  // Dasha lords, in the traditional Vimshottari cycle order.
  const dashaLord = {
    Ketu: {title:'A period of quiet unwinding', body:'The Ketu period is traditionally associated with introspection, a stretch of time when outer ambition tends to loosen and attention turns inward. Old attachments are more easily set down than usually taken up.', prompt:'What are you finding easier to release just now?'},
    Venus: {title:'A period drawn to harmony', body:'The Venus period is traditionally read as a stretch inclined toward comfort, connection and the arts, when relationships and aesthetic pleasures tend to move to the foreground. Classical texts associate it with ease more than urgency.', prompt:'What would you like this stretch of time to feel like?'},
    Sun: {title:'A period in a brighter light', body:'The Sun period is traditionally associated with visibility, authority and questions of standing, a stretch when a person’s position tends to come under closer attention. Confidence and self-direction are its usual themes.', prompt:'What would you like to be recognised for right now?'},
    Moon: {title:'A period of shifting moods', body:'The Moon period is traditionally read as emotionally responsive, a stretch when mood, memory and domestic matters tend to move closer to the surface. Classical texts associate it with care, both given and needed.', prompt:'What is your attention returning to without being asked?'},
    Mars: {title:'A period that asks for action', body:'The Mars period is traditionally associated with energy, initiative and a readiness to act rather than deliberate further. Classical texts read it as a stretch when courage and direct effort tend to be tested.', prompt:'Where is direct action more useful than more planning?'},
    Rahu: {title:'A period of restless reaching', body:'The Rahu period is traditionally read as a stretch of unusual ambition, when the appetite for the unfamiliar tends to outpace what feels settled. Classical texts associate it with intensity rather than ease.', prompt:'What are you reaching for that you can’t quite name?'},
    Jupiter: {title:'A period of widening perspective', body:'The Jupiter period is traditionally associated with growth, guidance and an expansive outlook, a stretch when learning and belief tend to move to the centre. Classical texts often connect it with teachers, higher study and a widening view.', prompt:'What are you ready to understand more broadly?'},
    Saturn: {title:'A period of patient endurance', body:'The Saturn period is traditionally read as a stretch of discipline, delay and the slow accumulation that only time produces. Classical texts associate it with responsibility and the testing of patience rather than quick results.', prompt:'What could you keep doing without expecting quick results?'},
    Mercury: {title:'A period of sharpened thinking', body:'The Mercury period is traditionally associated with intellect, communication and the quick adjustments that study, trade and negotiation require. Classical texts read it as a stretch inclined toward learning and exchange.', prompt:'What would you like to understand more precisely?'}
  };

  const bhava = {
    1: 'The first house is traditionally read as the body, temperament and the self met first by the world.',
    2: 'The second house is traditionally associated with resources, speech and the family one is born into.',
    3: 'The third house is traditionally read as courage, effort and the company of siblings.',
    4: 'The fourth house is traditionally associated with home, inner ground and a mother’s early influence.',
    5: 'The fifth house is traditionally read as intellect, creativity and the guidance one has learned to trust.',
    6: 'The sixth house is traditionally associated with daily work, routine and the obstacles a person learns to manage.',
    7: 'The seventh house is traditionally read as partnership and the agreements made with another.',
    8: 'The eighth house is traditionally associated with transformation and whatever is shared beneath the surface.',
    9: 'The ninth house is traditionally read as belief, higher learning and journeys beyond the familiar.',
    10: 'The tenth house is traditionally associated with vocation and the part of a life visible to others.',
    11: 'The eleventh house is traditionally read as community, aspiration and the gains that come through others.',
    12: 'The twelfth house is traditionally associated with rest, retreat and letting go of what is no longer carried.'
  };

  return {lagna, graha, nakshatra, dashaLord, bhava};
})();
if (typeof module !== 'undefined' && module.exports) module.exports = JyotishText;
