/* Original reflective text for the Jyotish module. Traditional symbolism and
   significations offered for reflection; not predictions, not verdicts. */
const JyotishText = (() => {
  // Rashi order 0-11: Mesha, Vrishabha, Mithuna, Karka, Simha, Kanya, Tula,
  // Vrischika, Dhanu, Makara, Kumbha, Meena. Rulers follow the traditional
  // list: Mars, Venus, Mercury, Moon, Sun, Mercury, Venus, Mars, Jupiter,
  // Saturn, Saturn, Jupiter.
  const lagna = {
    0: {title:'A quick way of beginning', body:'Mars gives Mesha lagna its quick, direct temper, a fire sign eager to move before the ground is fully mapped. The ram’s instinct favours action first and reflection afterward.', prompt:'Where would starting first serve you better than waiting?'},
    1: {title:'A steady, sensory pace', body:'Vrishabha lagna is traditionally read through earth and fixity, ruled by a Venus that prefers what can be touched, tasted and trusted to remain. Patience and comfort are its natural register, built slowly and kept close.', prompt:'What are you building slowly enough to actually enjoy?'},
    2: {title:'A mind that keeps moving', body:'Curiosity comes naturally under Mithuna lagna, where Mercury’s quick mind favours conversation and more than one idea at once. Air and duality shape a rising sign that gathers information before settling on a view.', prompt:'Which question have you been circling without answering?'},
    3: {title:'A shell around something tender', body:'The Moon governs Karka lagna, protective and responsive, water moving in a cardinal rush that senses a room before entering it. Memory and care sit close to the surface here.', prompt:'What are you guarding until it feels safe to show?'},
    4: {title:'A presence meant to be seen', body:'Simha lagna, ruled by the Sun, carries warmth, dignity and a steady wish to be recognised for what is genuinely offered. Fire held in a fixed sign burns evenly rather than in bursts.', prompt:'What would you like to be known for doing well?'},
    5: {title:'An eye for what needs fixing', body:'An eye for detail defines Kanya lagna, where earth-toned Mercury wants things done properly rather than merely finished. Service and precision come naturally to this rising sign.', prompt:'What small correction would improve everything around it?'},
    6: {title:'A search for the right balance', body:'Tula lagna, ruled by Venus, weighs one thing against another before choosing, fairness mattering as much as the outcome itself. Air in cardinal motion keeps this rising sign alert to how others see things.', prompt:'Whose perspective are you weighing most heavily right now?'},
    7: {title:'A depth that takes its time', body:'Depth suits Vrischika lagna, where Mars moves through water held in a fixed sign, slow to trust and thorough once it does. What lies beneath the surface interests this rising sign more than what is shown.', prompt:'What have you been circling without looking at directly?'},
    8: {title:'A reach toward the horizon', body:'Jupiter widens the horizon for Dhanu lagna, fire and duality combining into a restless appetite for meaning and distance. Belief and exploration sit at the centre of this rising sign.', prompt:'Which larger question is worth your attention this season?'},
    9: {title:'A structure built to last', body:'Makara lagna, ruled by Saturn, is patient and disciplined, earth moved by cardinal ambition rather than haste. This rising sign favours a plan carried out in stages over a single decisive leap.', prompt:'What could you commit to working at slowly, for years?'},
    10: {title:'A view apart from the crowd', body:'Independence marks Kumbha lagna, a fixed, air-born detachment under Saturn that prefers its own reading of events to the expected one. Community matters here, but so does standing somewhat apart from it.', prompt:'Where would you rather trust your own judgement instead?'},
    11: {title:'A boundary that stays porous', body:'Meena lagna, ruled by Jupiter, is receptive and imaginative, water and duality merging into a rising sign that takes its bearings from atmosphere as much as fact. Compassion tends to travel easily across its edges.', prompt:'What are you sensing that you cannot yet explain?'}
  };

  const graha = {
    Sun: {theme:'identity, vitality and authority', body:'Surya, the Sun, is traditionally associated with vitality, self-expression and the confidence to occupy the position one holds. Classical texts read it as the soul’s own light, the core around which the rest of the chart turns.'},
    Moon: {theme:'the mind, feeling and instinct', body:'Chandra, the Moon, is traditionally read as the mind itself: memory, mood and the instinctive responses that arrive before thought catches up. It governs comfort, nourishment and the pull toward whatever feels familiar.'},
    Mars: {theme:'courage, drive and initiative', body:'Mangala, Mars, is traditionally associated with courage, energy and the will to act, the planet of initiative rather than deliberation. Classical texts connect it with siblings, land and the physical effort a task demands.'},
    Mercury: {theme:'intellect, speech and exchange', body:'Budha, Mercury, is traditionally read as intellect in motion: language, calculation and the quick adjustments that trade and conversation require. It is the planet of learning that moves between subjects rather than settling in one.'},
    Jupiter: {theme:'wisdom, expansion and guidance', body:'Brihaspati, Jupiter, is traditionally associated with wisdom, generosity and the expansive outlook of a teacher. Classical texts read it as the planet of growth, belief and the guidance that widens a narrow view.'},
    Venus: {theme:'harmony, pleasure and connection', body:'Shukra, Venus, is traditionally read as the planet of harmony, comfort and the arts, drawn toward what is pleasing to the senses. It governs affection, cooperation and the diplomacy that keeps a relationship workable.'},
    Saturn: {theme:'discipline, patience and structure', body:'Shani, Saturn, is traditionally associated with discipline, delay and the patience that only time can teach. Classical texts read it as the planet of structure, responsibility and the slow, exacting work of endurance.'},
    Rahu: {theme:'ambition, hunger and the unfamiliar', body:'Rahu, the north lunar node, is traditionally read as an unfinished hunger: ambition, obsession and a pull toward whatever lies outside ordinary experience. It has no physical body in the classical scheme, only direction and appetite.'},
    Ketu: {theme:'detachment, introspection and release', body:'Ketu, the south lunar node, is traditionally associated with detachment, introspection and a familiarity that arrived from somewhere the mind cannot quite place. Classical texts read it as the planet that quietly loosens what Rahu spent itself chasing.'}
  };

  // Nakshatra order 0-26: Ashwini, Bharani, Krittika, Rohini, Mrigashira,
  // Ardra, Punarvasu, Pushya, Ashlesha, Magha, Purva Phalguni, Uttara
  // Phalguni, Hasta, Chitra, Swati, Vishakha, Anuradha, Jyeshtha, Mula,
  // Purva Ashadha, Uttara Ashadha, Shravana, Dhanishta, Shatabhisha, Purva
  // Bhadrapada, Uttara Bhadrapada, Revati.
  const nakshatra = {
    0: {keyword:'swift beginnings', body:'Ashwini Kumaras, twin physicians who could close any distance in an instant, are the guiding deities here. Their emblem, a horse’s head, carries the same appetite: to move first and let the details follow.', prompt:'What are you ready to begin without further preparation?'},
    1: {keyword:'carrying something through', body:'Bharani’s oldest picture is a womb, holding something until it is ready to arrive on its own schedule. Yama, keeper of thresholds, watches over the endings that clear space for what comes next.', prompt:'What are you determined to see through to the end?'},
    2: {keyword:'a cutting clarity', body:'Agni, fire itself, rules Krittika, and its symbol, a blade or a single flame, reflects the same cutting clarity. What burns here tends to burn clean, leaving less behind than expected.', prompt:'What could you see more clearly if you looked directly at it?'},
    3: {keyword:'steady growth', body:'New growth fills the cart that is Rohini’s picture, tended by Prajapati, the creator concerned with what ripens rather than what appears overnight. Patience is built into the symbol itself, long before any harvest shows.', prompt:'What are you tending that isn’t ready to be rushed?'},
    4: {keyword:'a gentle searching', body:'A deer’s head turned mid-step is Mrigashira’s emblem, and Soma, wandering and curious, is read as its deity. Attention here tends to move gently toward whatever seems just out of reach, without forcing the approach.', prompt:'What are you quietly searching for right now?'},
    5: {keyword:'weather that clears the air', body:'Rudra, the storm, presides over Ardra, whose symbol, a single teardrop, suggests weather that clears more than it disturbs. Something difficult often has to pass through here before what follows can be seen plainly.', prompt:'What difficulty might actually be clearing something?'},
    6: {keyword:'a return to what matters', body:'A bow and quiver, restrung and ready again, mark Punarvasu, paired with Aditi, mother of the gods and patron of second chances. Old ground gets revisited under this sign more often than new ground gets broken.', prompt:'What is worth returning to and trying again?'},
    7: {keyword:'quiet nourishment', body:'Brihaspati, teacher and guide, is traditionally associated with nourishment that asks for nothing back, and Pushya’s symbol, a cow’s udder, offers exactly that. Few placements are considered as steady or as quietly sustaining as this one.', prompt:'Who or what are you quietly sustaining right now?'},
    8: {keyword:'a penetrating instinct', body:'A coiled serpent is Ashlesha’s emblem, watched over by the Nagas, whose old stories describe instinct sharper than plain sight. What is sensed here tends to arrive before it can be explained.', prompt:'What have you sensed that you haven’t named yet?'},
    9: {keyword:'inherited authority', body:'Magha takes its image from a throne, occupied under the watch of the Pitris, the ancestors whose weight sits behind whoever sits there. Authority carried this way was rarely built from nothing; some part of it was inherited.', prompt:'What inheritance, spoken or not, are you carrying forward?'},
    10: {keyword:'ease enjoyed openly', body:'The front legs of a bed form Purva Phalguni’s picture, presided over by Bhaga, whose old portfolio is enjoyment taken without apology. Comfort offered here tends to be comfort actually received, not merely performed.', prompt:'Where could you allow yourself more ease right now?'},
    11: {keyword:'quiet alliance', body:'Where Purva Phalguni ends, Uttara Phalguni continues with the back legs of the same bed, now under Aryaman, patron of alliance and quiet backing. Support given this way tends to be dependable well past the point it stops being noticed.', prompt:'Whose steady support have you not properly acknowledged?'},
    12: {keyword:'skill in the hands', body:'Savitr, associated with skill freely offered, governs Hasta, whose symbol is simply an open hand. Whatever is made under this sign tends to be made with care, and practised until the effort stops showing.', prompt:'What craft would reward more deliberate practice?'},
    13: {keyword:'a brilliance worth shaping', body:'A bright jewel is Chitra’s emblem, shaped by Tvashtar, the craftsman god credited with turning raw material into something distinct. Appearance matters here, but mostly when it is backed by real skill underneath.', prompt:'What are you shaping that deserves more attention to form?'},
    14: {keyword:'flexible independence', body:'A young shoot bending in open wind is Swati’s picture, with Vayu, the wind itself, as its deity. Whatever grows under this sign tends to survive by flexing, not by refusing to move.', prompt:'Where would bending serve you better than holding firm?'},
    15: {keyword:'determined achievement', body:'Vishakha’s symbol, a triumphal archway, is traditionally associated with determined effort aimed at a single, visible goal. Indra and Agni, its joint deities, favour focus over a wide, scattered pace.', prompt:'What goal deserves a more determined, focused effort?'},
    16: {keyword:'devotion and friendship', body:'Mitra, god of friendship and quiet loyalty, watches over Anuradha, whose emblem is the lotus. Bonds formed here are rarely loud, but they tend to hold across long distances and longer silences.', prompt:'Which friendship deserves more of your attention lately?'},
    17: {keyword:'seniority and protection', body:'A circular amulet, worn against harm, is Jyeshtha’s symbol, fitting for a nakshatra ruled by Indra, senior among the old gods. Being the eldest in a room, welcome or not, is a familiar position here.', prompt:'Where are you already the one others look to?'},
    18: {keyword:'getting to the root', body:'Mula takes its image from a bundle of roots pulled clean from the ground, governed by Nirriti, traditionally read as the force that strips things back to what is foundational. Investigation here rarely stops at the first easy answer.', prompt:'What would you find if you kept asking why?'},
    19: {keyword:'an early, clean victory', body:'A winnowing fan is Purva Ashadha’s picture, and its deity Apas, the waters, is traditionally associated with purification and an early sense of momentum. Confidence tends to arrive quickly here, well before all the evidence is in.', prompt:'What conviction are you ready to act on early?'},
    20: {keyword:'a lasting achievement', body:'Purva Ashadha’s early momentum is answered by Uttara Ashadha, whose elephant’s-tusk emblem belongs to the Vishvadevas, the universal gods concerned with what endures. Little that matters here gets finished quickly; most of it gets finished eventually.', prompt:'What are you building that should be made to last?'},
    21: {keyword:'careful listening', body:'Vishnu, credited with patient listening, is paired with Shravana, whose symbol is an ear, or three footprints tracing a chosen path. Learning under this placement tends to come from attention rather than argument.', prompt:'What would you learn if you listened more than you spoke?'},
    22: {keyword:'shared rhythm', body:'A drum is Dhanishta’s emblem, kept by the Vasus, gods of the elements known for finding a shared beat. Effort under this placement tends to land better in company than in isolation.', prompt:'Where would working in rhythm with others help most?'},
    23: {keyword:'vast, quiet healing', body:'An empty circle, wide enough to hold anything, is Shatabhisha’s picture. Varuna, keeper of vast waters, is traditionally associated with mystery and remedies for what troubles the body, applied slowly and mostly alone.', prompt:'What are you healing from in your own time and way?'},
    24: {keyword:'fierce, single-minded intensity', body:'Aja Ekapada, the one-footed goat, is an old, fierce figure paired with Purva Bhadrapada, whose symbol is a sword aimed at a single point. Conviction here rarely spreads itself across more than one target at a time.', prompt:'What deserves your full, undivided attention right now?'},
    25: {keyword:'a calm beneath the surface', body:'Purva Bhadrapada’s single point gives way to Uttara Bhadrapada’s pair of twins, watched over by Ahir Budhnya, the serpent said to rest in the deepest water. Considerable strength can sit under a calm surface here, largely unannounced.', prompt:'Where is your strength showing up as calm rather than action?'},
    26: {keyword:'safe passage', body:'A fish moving through boundless water is Revati’s picture, guided by Pushan, patron of journeys and safe arrival at a destination not yet in sight. Guidance under this placement tends to be gentle rather than forceful.', prompt:'What passage are you being asked to move through gently?'}
  };

  // Dasha lords, in the traditional Vimshottari cycle order.
  const dashaLord = {
    Ketu: {title:'A period of quiet unwinding', body:'Ketu’s stretch is traditionally read as introspective, a time when outer ambition tends to loosen and attention turns inward. Old attachments are more easily set down than usually taken up.', prompt:'What are you finding easier to release just now?'},
    Venus: {title:'A period drawn to harmony', body:'Comfort, connection and the arts tend to move to the foreground during a Venus period, traditionally read as inclined toward ease rather than urgency. Relationships and aesthetic pleasures often take priority here.', prompt:'What would you like this stretch of time to feel like?'},
    Sun: {title:'A period in a brighter light', body:'Visibility and questions of standing come forward under the Sun’s period, traditionally associated with a person’s position drawing closer attention. Confidence and self-direction are its usual themes.', prompt:'What would you like to be recognised for right now?'},
    Moon: {title:'A period of shifting moods', body:'Mood, memory and domestic matters tend to move closer to the surface during a Moon period, emotionally responsive by tradition. Classical texts associate it with care, both given and needed.', prompt:'What is your attention returning to without being asked?'},
    Mars: {title:'A period that asks for action', body:'Energy and initiative define the Mars period, traditionally read as a stretch when courage and direct effort tend to be tested. Deliberation gives way here to a readiness to act.', prompt:'Where is direct action more useful than more planning?'},
    Rahu: {title:'A period of restless reaching', body:'Unusual ambition marks the Rahu period, traditionally read as a stretch when appetite for the unfamiliar tends to outpace what feels settled. Classical texts associate it with intensity rather than ease.', prompt:'What are you reaching for that you can’t quite name?'},
    Jupiter: {title:'A period of widening perspective', body:'Growth, guidance and an expansive outlook move to the centre during a Jupiter period, learning and belief given more room than usual. Classical texts often connect it with teachers, higher study and a widening view.', prompt:'What are you ready to understand more broadly?'},
    Saturn: {title:'A period of patient endurance', body:'Discipline, delay and the slow accumulation that only time produces define the Saturn period by tradition. Classical texts associate it with responsibility and the testing of patience rather than quick results.', prompt:'What could you keep doing without expecting quick results?'},
    Mercury: {title:'A period of sharpened thinking', body:'Intellect and communication sharpen during the Mercury period, traditionally read as inclined toward the quick adjustments that study, trade and negotiation require. Classical texts read it as a stretch suited to learning and exchange.', prompt:'What would you like to understand more precisely?'}
  };

  const bhava = {
    1: 'The first house is traditionally read as the body, temperament and the self met first by the world.',
    2: 'The second house is traditionally associated with resources, speech and the family one is born into.',
    3: 'The third house is traditionally read as courage, effort and the company of siblings.',
    4: 'The fourth house is traditionally associated with home, inner ground and a mother’s early influence.',
    5: 'The fifth house is traditionally read as intellect, creativity and the guidance one has learned to trust.',
    6: 'The sixth house is traditionally associated with daily work, routine and the effort of keeping things in order.',
    7: 'The seventh house is traditionally read as partnership and the agreements made with another.',
    8: 'The eighth house is traditionally associated with transformation and whatever is shared beneath the surface.',
    9: 'The ninth house is traditionally read as belief, higher learning and journeys beyond the familiar.',
    10: 'The tenth house is traditionally associated with vocation and the part of a life visible to others.',
    11: 'The eleventh house is traditionally read as community, friendship and the hopes people build together.',
    12: 'The twelfth house is traditionally associated with rest, retreat and letting go of what is no longer carried.'
  };

  // Gochar: past tense and third person throughout. The supportive table itself
  // is rendered from JyotishEngine.GOCHAR_SUPPORTIVE so copy and engine cannot drift.
  const gochar = {
    intro: 'Gochar, the Jyotish reading of transits, sets the grahas of a chosen day against the birth chart. Each graha is counted in signs from the rashi the Moon occupied at birth, and tradition gave every count its own character.',
    supportive: 'Tradition counted this transit as supportive',
    demanding: 'Tradition counted this transit as more demanding',
    sadeSati: 'Tradition called Saturn’s passage through the 12th, 1st and 2nd signs from the natal Moon Sade Sati, a span of about seven and a half years associated with steady effort. The name marks that association and was never meant as a forecast.',
    method: 'Positions are calculated for 12:00 UTC on the chosen day, so a graha that changes sign during the day is shown in its noon sign. They use the Lahiri ayanamsa and mean lunar nodes, as elsewhere in this section. Houses are counted whole-sign from the natal Moon’s rashi, which is the 1st. The table below is the classical Gochara scheme counted from the Moon, as summarised in Mantreswara’s Phaladeepika; other texts vary at the margins. Vedha — the rule under which a graha in a paired sign was said to cancel a transit — is not applied. This tab describes traditional associations, not predictions.'
  };

  return {lagna, graha, nakshatra, dashaLord, bhava, gochar};
})();
if (typeof module !== 'undefined' && module.exports) module.exports = JyotishText;
