/* Interactive natal presentation; interpretations are original reflective writing. */
const NatalChart = (() => {
  const E=NatalEngine, esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const houseNames=['Identity & approach','Values & resources','Learning & communication','Home & foundations','Creativity & pleasure','Daily practice & service','Partnership & agreements','Intimacy & shared resources','Beliefs & discovery','Vocation & visibility','Community & hopes','Solitude & inner life'];
  const housePrompts=['How do you want to meet the world?','What is worth your time, energy and care?','What conversation could open a new possibility?','What helps you feel rooted and at home?','What would you create for the pleasure of it?','Which daily rhythm supports your larger intentions?','What does a fair and honest partnership ask of you?','Where would clearer boundaries support deeper trust?','Which belief is ready to meet a wider world?','What contribution do you want to be known for?','Which people help you imagine a worthwhile future?','What becomes audible when you make room for quiet?'];
  const lenses=['direct action, courage and fresh beginnings','steadiness, sensory experience and patient growth','curiosity, conversation and changing perspectives','care, belonging and emotional memory','expression, generosity and the courage to be seen','discernment, useful practice and thoughtful refinement','reciprocity, proportion and considered choices','depth, honesty and meaningful transformation','discovery, perspective and the search for meaning','structure, responsibility and long-term commitments','independent thinking, community and new possibilities','imagination, empathy and a permeable inner world'];
  const roles={Sun:['Identity & purpose','what gives you a sense of authorship'],Moon:['Feelings & belonging','how you seek emotional steadiness'],Mercury:['Thinking & communication','how you learn, connect ideas and express them'],Venus:['Affection & values','what you enjoy and how you relate'],Mars:['Drive & assertion','how you act, pursue and set boundaries'],Jupiter:['Growth & perspective','how you explore possibility and meaning'],Saturn:['Structure & responsibility','how you build capacity through commitment'],Uranus:['Freedom & reinvention','where you experiment with a different way'],Neptune:['Imagination & ideals','how you hold dreams, sensitivity and uncertainty'],Pluto:['Depth & transformation','how you engage with change and shared power'],'North Node':['A direction to explore','a symbolic invitation to try less familiar patterns'],'South Node':['Familiar patterns','a symbolic lens on habits and existing strengths'],Ascendant:['Your approach to life','the way you enter situations and meet the world'],Midheaven:['Vocation & public direction','the contribution you want to develop and make visible'],Descendant:['Partnership & encounter','the qualities you explore through close relationship'],'Imum Coeli':['Roots & private foundations','the inner ground from which you grow']};
  const aspectCopy={Conjunction:'These themes occupy similar territory. Explore how they can work together without one drowning out the other.',Sextile:'These themes suggest an opening that grows through participation. A small, deliberate action can help you use it.',Square:'These themes can pull in different directions. Give each a clear role and look for a practice that makes the tension useful.',Trine:'These themes may feel naturally compatible. Notice the ease available here, and choose how to use it with intention.',Opposition:'These themes face one another across the chart. Make room for both sides instead of asking one to carry the whole story.'};
  const systemNames={placidus:'Placidus','whole-sign':'Whole Sign',equal:'Equal'};
  const allPoints=model=>[...model.points,...model.axes];
  const degree=value=>`${Math.floor(value)}°${String(Math.floor((value%1)*60)).padStart(2,'0')}′`;
  const motion=point=>point.kind==='angle'?'Chart angle':point.kind==='node'?'Mean node · retrograde':point.stationary?'Near station':point.retrograde?'Retrograde':'Direct';
  const styles=`.n-ring{fill:none;stroke:#d9bd86;stroke-width:1}.n-sector{fill:#182b39;stroke:#8e866f;stroke-width:.6}.n-sign{fill:#f7dfb4;font:23px "Segoe UI Symbol","Apple Symbols",serif;text-anchor:middle}.n-sign-name{fill:#cbdce0;font:10px sans-serif;text-anchor:middle}.n-cusp{stroke:#c5bc9e;stroke-width:.7;opacity:.5}.n-house{fill:#d9c8a8;font:11px sans-serif;text-anchor:middle}.n-aspect{stroke:#8dd0c8;stroke-width:.7;opacity:.4}.n-aspect.hard{stroke:#e7a19d}.n-aspect.chosen{stroke:#fff0bf;stroke-width:2;opacity:1}.n-leader{stroke:#a8c5d0;stroke-width:.6;opacity:.65}.n-marker{fill:#d6edeb;stroke:#14212f;stroke-width:1}.n-planet{fill:#fae5be;font:24px "Segoe UI Symbol","Apple Symbols",serif;text-anchor:middle}.n-degree{fill:#d3e3e5;font:9px sans-serif;text-anchor:middle}.n-point{cursor:pointer}.n-point.selected .n-planet,.n-point:focus .n-planet{fill:#fff}.n-point.selected circle,.n-point:focus circle{stroke:#f8d992;stroke-width:2;fill:#27505b}.n-hit{fill:#14212f;stroke:none}.n-axis{stroke:#e3c38c;stroke-width:1.5}.n-axis-name{fill:#fff0c4;font:10px sans-serif;text-anchor:middle}.n-point:focus{outline:none}.n-title{fill:#acc9ce;font:9px sans-serif;letter-spacing:1px;text-anchor:middle}`;
  function renderWheel(model,selection={kind:'point',key:'Sun'},interactive=false,showAspects=true) {
    const center=300,point=(r,longitude)=>{const angle=(180-(longitude-model.angles.asc))*Math.PI/180;return [center+r*Math.cos(angle),center+r*Math.sin(angle)];};
    const line=(a,b,cls,extra='')=>`<line class="${cls}" x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" ${extra}/>`;
    const sectors=E.signNames.map((name,index)=>{
      const a=point(272,index*30),b=point(272,(index+1)*30),c=point(231,(index+1)*30),d=point(231,index*30),label=point(252,index*30+15);
      return `<path class="n-sector" d="M${a} A272 272 0 0 0 ${b} L${c} A231 231 0 0 1 ${d} Z"/><text class="n-sign" x="${label[0]}" y="${label[1]+1}">${E.signGlyphs[index]}\uFE0E</text><text class="n-sign-name" x="${label[0]}" y="${label[1]+14}">${name}</text>`;
    }).join('');
    const ticks=Array.from({length:72},(_,i)=>line(point(i%6===0?278:282,i*5),point(287,i*5),'n-cusp')).join('');
    const houses=model.cusps.map((cusp,index)=>{
      const midpoint=cusp+E.mod(model.cusps[(index+1)%12]-cusp)/2,label=point(143,midpoint);
      const selected=selection.kind==='house'&&selection.key===String(index+1);
      return `${line(point(123,cusp),point(230,cusp),'n-cusp')}<g class="n-point${selected?' selected':''}" ${interactive?`role="button" tabindex="0" data-natal-kind="house" data-natal-key="${index+1}" aria-label="Inspect house ${index+1}: ${houseNames[index]}" aria-pressed="${selected}"`:''}><circle cx="${label[0]}" cy="${label[1]-3}" r="12" fill="#101d2b"/><text class="n-house" x="${label[0]}" y="${label[1]+1}">${index+1}</text></g>`;
    }).join('');
    const lookup=Object.fromEntries(allPoints(model).map(item=>[item.name,item]));
    const aspects=showAspects?model.aspects.map(aspect=>line(point(120,lookup[aspect.a].longitude),point(120,lookup[aspect.b].longitude),`n-aspect${['Square','Opposition'].includes(aspect.type)?' hard':''}${selection.kind==='aspect'&&selection.key===aspect.id?' chosen':''}`)).join(''):'';
    // Separate crowded glyphs; leader lines retain their exact ecliptic positions.
    const sorted=[...model.points].sort((a,b)=>a.longitude-b.longitude);
    let gapIndex=0,gap=0;
    sorted.forEach((item,index)=>{const g=E.mod(sorted[(index+1)%sorted.length].longitude-item.longitude);if(g>gap){gap=g;gapIndex=(index+1)%sorted.length;}});
    const ordered=[...sorted.slice(gapIndex),...sorted.slice(0,gapIndex)];
    const base=ordered[0].longitude,actual=ordered.map(item=>base+E.mod(item.longitude-base));
    const labels=actual.map((angle,index)=>index===0?angle:0);
    for(let i=1;i<labels.length;i++) labels[i]=Math.max(actual[i],labels[i-1]+13);
    const shift=labels.reduce((sum,angle,index)=>sum+angle-actual[index],0)/labels.length;
    const planets=ordered.map((item,index)=>{
      const label=point(195,labels[index]-shift),anchor=point(165,item.longitude),selected=selection.kind==='point'&&selection.key===item.name;
      return `${line(anchor,label,'n-leader')}<circle class="n-marker" cx="${anchor[0]}" cy="${anchor[1]}" r="2.5"/><g class="n-point${selected?' selected':''}" ${interactive?`role="button" tabindex="0" data-natal-kind="point" data-natal-key="${item.name}" aria-label="Inspect ${item.name}: ${item.sign} ${item.degrees}" aria-pressed="${selected}"`:''}><circle class="n-hit" cx="${label[0]}" cy="${label[1]-3}" r="18"/><text class="n-planet" x="${label[0]}" y="${label[1]+3}">${item.symbol}\uFE0E</text><text class="n-degree" x="${label[0]}" y="${label[1]+18}">${item.degrees}${item.retrograde?' ℞':''}</text></g>`;
    }).join('');
    const axes=model.axes.map(item=>{
      const pos=point(291,item.longitude);
      return `${line(point(225,item.longitude),point(280,item.longitude),'n-axis')}<text class="n-axis-name" x="${pos[0]}" y="${pos[1]+3}">${item.symbol}</text>`;
    }).join('');
    return `<svg xmlns="http://www.w3.org/2000/svg" class="natal-wheel" viewBox="0 0 600 600" ${interactive?'role="group" aria-label="Calculated natal chart: choose a planet or house"':'role="img" aria-label="Calculated natal chart with planets, houses and aspects"'}><style>${styles}</style><rect width="600" height="600" rx="300" fill="#101d2b"/><circle class="n-ring" cx="300" cy="300" r="289"/>${sectors}${ticks}${houses}<circle class="n-ring" cx="300" cy="300" r="122"/>${aspects}${planets}${axes}<text class="n-title" x="300" y="303">ISHTAR INSIGHTS</text></svg>`;
  }
  function detail(model,selection) {
    if(selection.kind==='house') {
      const number=Number(selection.key),cusp=E.placement(model.cusps[number-1]),occupants=model.points.filter(point=>point.house===number);
      return `<p class="reading-label">${systemNames[model.houseSystem]} houses</p><h3>House ${number}</h3><p class="natal-detail-theme">${houseNames[number-1]}</p><dl><div><dt>Cusp</dt><dd>${cusp.sign}</dd></div><div><dt>Degree</dt><dd>${cusp.degrees}</dd></div></dl><p>This part of the chart is traditionally associated with ${houseNames[number-1].toLowerCase()}. Its ${cusp.sign} cusp adds a lens of ${lenses[cusp.index]}.</p><p class="sky-explorer-prompt"><strong>Placements here</strong>${occupants.map(point=>point.name).join(' · ') || 'No planets or nodes here. An unoccupied house is still part of the chart.'}</p><p class="sky-explorer-prompt"><strong>Journal prompt</strong>${housePrompts[number-1]}</p>`;
    }
    if(selection.kind==='aspect') {
      const aspect=model.aspects.find(item=>item.id===selection.key);
      if(!aspect) return '';
      return `<p class="reading-label">${aspect.type} · ${aspect.tone}</p><h3>${aspect.a}<br><span class="natal-aspect-symbol">${aspect.symbol}</span> ${aspect.b}</h3><dl><div><dt>Angle</dt><dd>${aspect.angle}°</dd></div><div><dt>Orb</dt><dd>${degree(aspect.orb)}</dd></div></dl><p>${roles[aspect.a][0]} meets ${roles[aspect.b][0].toLowerCase()}. ${aspectCopy[aspect.type]}</p><p class="sky-explorer-prompt"><strong>${aspect.applying===null?'Contact to a chart angle':aspect.applying?'Applying aspect':'Separating aspect'}</strong>${aspect.applying===null?'This contact describes the chart at the entered moment.':aspect.applying?'The bodies are moving toward the exact aspect at this moment.':'The bodies are moving away from the exact aspect at this moment.'}</p><p class="sky-explorer-prompt"><strong>Journal prompt</strong>Where do these two themes meet in your everyday choices?</p>`;
    }
    const item=allPoints(model).find(point=>point.name===selection.key) || model.points[0],role=roles[item.name];
    return `<p class="reading-label">${item.kind==='node'?'Mean lunar node':item.kind==='angle'?'Calculated chart angle':'Natal placement'}</p><h3>${item.name}<br><span class="natal-detail-sign">in ${item.sign}</span></h3><p class="natal-detail-theme">${role[0]}</p><dl><div><dt>Longitude</dt><dd>${item.degrees} ${item.glyph}\uFE0E</dd></div><div><dt>House</dt><dd>${item.house}</dd></div><div><dt>Element</dt><dd>${item.element}</dd></div><div><dt>Quality</dt><dd>${item.quality}</dd></div></dl><p>In this reading, ${item.name} represents ${role[1]}. ${item.sign} brings an emphasis on ${lenses[item.index]}.</p><p class="sky-explorer-prompt"><strong>House ${item.house} · ${houseNames[item.house-1]}</strong>Explore how this theme shows up through ${houseNames[item.house-1].toLowerCase()}.</p>${item.kind!=='angle'?`<p class="sky-explorer-prompt"><strong>${motion(item)}</strong>${item.kind==='node'?'Mean nodes describe the averaged lunar orbital axis, not a physical planet.':item.retrograde?'Retrograde describes apparent backward motion from Earth. As a reflection, consider where review or an inward approach is useful.':'Direct motion is the usual forward movement through the zodiac.'}</p>`:''}<p class="sky-explorer-prompt"><strong>Journal prompt</strong>${housePrompts[item.house-1]}</p>`;
  }
  function bigThree(model) {
    return `<div class="natal-big-three">${[model.points[0],model.points[1],model.axes[0]].map(item=>`<button type="button" data-open-natal="point" data-natal-key="${item.name}"><span>${item.name==='Ascendant'?'Rising':item.name}</span><strong>${item.glyph}\uFE0E ${item.sign}</strong><small>${item.degrees}</small></button>`).join('')}</div>`;
  }
  function report(model,view='placements',filter='all') {
    const tableRows=allPoints(model).map(item=>`<tr><th scope="row"><button type="button" data-open-natal="point" data-natal-key="${item.name}"><span aria-hidden="true">${item.symbol}\uFE0E</span> ${item.name}</button></th><td>${item.sign}<small>${item.degrees}</small></td><td>${item.house}</td><td>${motion(item)}</td></tr>`).join('');
    const filtered=model.aspects.filter(item=>filter==='all'||item.type===filter);
    return `<section class="natal-report" aria-label="Natal chart report"><header><div><p class="reading-label">Your chart, in detail</p><h4>The pattern of your sky</h4></div><button type="button" data-print-natal>Print chart & report ↗</button></header><p class="natal-calculation-line">Tropical zodiac · ${systemNames[model.houseSystem]} houses · ${esc(model.timeZone)} · ${esc(model.date.slice(0,16).replace('T',' '))} UTC</p>${model.notice?`<p class="natal-notice">${model.notice}</p>`:''}<div class="natal-report-nav" role="group" aria-label="Natal chart details">${[['placements','Placements'],['houses','Houses'],['aspects','Aspects'],['balance','Balance']].map(([key,name])=>`<button type="button" data-natal-view="${key}" aria-pressed="${view===key}" aria-controls="natal-${key}">${name}</button>`).join('')}</div>
      <div id="natal-placements" class="natal-report-panel"${view==='placements'?'':' hidden'}><div class="natal-table-scroll" tabindex="0" aria-label="Planet placements table"><table><thead><tr><th scope="col">Body / point</th><th scope="col">Sign & degree</th><th scope="col">House</th><th scope="col">Motion</th></tr></thead><tbody>${tableRows}</tbody></table></div></div>
      <div id="natal-houses" class="natal-report-panel"${view==='houses'?'':' hidden'}><div class="natal-house-grid">${model.cusps.map((cusp,index)=>{const p=E.placement(cusp);return `<button type="button" data-open-natal="house" data-natal-key="${index+1}"><span class="house-number">${index+1}</span><span><strong>${houseNames[index]}</strong><small>${p.glyph}\uFE0E ${p.sign} · ${p.degrees}</small></span></button>`;}).join('')}</div></div>
      <div id="natal-aspects" class="natal-report-panel"${view==='aspects'?'':' hidden'}><label class="natal-aspect-filter">Aspect type <select id="natal-aspect-filter"><option value="all">All major aspects</option>${E.aspectTypes.map(type=>`<option${filter===type.name?' selected':''}>${type.name}</option>`).join('')}</select></label><p class="natal-panel-hint">${filtered.length} contacts · tightest orbs first · choose a contact for its interpretation.</p><div class="natal-aspect-grid">${filtered.map(item=>`<button type="button" data-open-natal="aspect" data-natal-key="${item.id}"><span class="aspect-mark ${['Square','Opposition'].includes(item.type)?'hard':''}">${item.symbol}</span><span><strong>${item.a} · ${item.b}</strong><small>${item.type} · orb ${degree(item.orb)}${item.applying===null?'':item.applying?' · applying':' · separating'}</small></span></button>`).join('') || '<p>No contacts within these orbs.</p>'}</div></div>
      <div id="natal-balance" class="natal-report-panel"${view==='balance'?'':' hidden'}><p class="natal-panel-hint">An equal count of the ten planets. Nodes and chart angles are excluded.</p><div class="natal-balance-grid">${[['Elements',model.balance.elements],['Qualities',model.balance.qualities]].map(([title,values])=>`<article><h5>${title}</h5>${Object.entries(values).map(([name,count])=>`<div class="natal-balance-row"><span>${name}</span><meter min="0" max="10" value="${count}" aria-label="${name}: ${count} of 10 planets"></meter><strong>${count}/10</strong></div>`).join('')}</article>`).join('')}</div><p class="natal-panel-hint">Use the distribution as a conversation starter. A low count is not a deficiency.</p></div>
      <details class="insight-method"><summary>Calculation settings & interpretation notes</summary><p>Positions use Astronomy Engine 2.1.19, a tropical zodiac and geocentric ecliptic longitudes. Time-zone conversion uses the browser’s historical IANA rules. Placidus divides semi-diurnal and semi-nocturnal arcs; Whole Sign starts the first house at the beginning of the rising sign; Equal starts at the Ascendant and uses twelve 30° houses. Polar charts use Whole Sign if Placidus is unavailable.</p><p>The lunar nodes are mean nodes. Major aspects use ${E.aspectTypes.map(type=>`${type.name.toLowerCase()} ${degree(type.orb*model.orbScale)}`).join(', ')} maximum orbs. Applying/separating is estimated from motion around the birth moment. Interpretations are original reflective writing, not predictions. Birth time and place precision affect the angles and houses.</p><p>Sources: <a href="https://github.com/cosinekitty/astronomy" target="_blank" rel="noopener">Astronomy Engine</a> · <a href="https://www.astro.com/swisseph/swisseph.htm" target="_blank" rel="noopener">house-system definitions</a> · <a href="docs/NATAL-CHART.md" target="_blank" rel="noopener">methods & validation</a></p></details></section>`;
  }
  function download(model,selection,showAspects=true) {
    const blob=new Blob([renderWheel(model,selection,false,showAspects)],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');
    link.href=url;link.download=`ishtar-natal-${model.birthday}.svg`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  return {renderWheel,detail,bigThree,report,download,systemNames,degree};
})();
