/* Interactive natal presentation; interpretations are original reflective writing. */
const NatalChart = (() => {
  const E=NatalEngine, esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const houseNames=['Identity & approach','Values & resources','Learning & communication','Home & foundations','Creativity & pleasure','Daily practice & service','Partnership & agreements','Intimacy & shared resources','Beliefs & discovery','Vocation & visibility','Community & hopes','Solitude & inner life'];
  const housePrompts=['How do you want to meet the world?','What is worth your time, energy and care?','What conversation could open a new possibility?','What helps you feel rooted and at home?','What would you create for the pleasure of it?','Which daily rhythm supports your larger intentions?','What does a fair and honest partnership ask of you?','Where would clearer boundaries support deeper trust?','Which belief is ready to meet a wider world?','What contribution do you want to be known for?','Which people help you imagine a worthwhile future?','What becomes audible when you make room for quiet?'];
  const lenses=['direct action, courage and fresh beginnings','steadiness, sensory experience and patient growth','curiosity, conversation and changing perspectives','care, belonging and emotional memory','expression, generosity and the courage to be seen','discernment, useful practice and thoughtful refinement','reciprocity, proportion and considered choices','depth, honesty and meaningful transformation','discovery, perspective and the search for meaning','structure, responsibility and long-term commitments','independent thinking, community and new possibilities','imagination, empathy and a permeable inner world'];
  const roles={Sun:['Identity & purpose','what gives you a sense of authorship'],Moon:['Feelings & belonging','how you seek emotional steadiness'],Mercury:['Thinking & communication','how you learn, connect ideas and express them'],Venus:['Affection & values','what you enjoy and how you relate'],Mars:['Drive & assertion','how you act, pursue and set boundaries'],Jupiter:['Growth & perspective','how you explore possibility and meaning'],Saturn:['Structure & responsibility','how you build capacity through commitment'],Uranus:['Freedom & reinvention','where you experiment with a different way'],Neptune:['Imagination & ideals','how you hold dreams, sensitivity and uncertainty'],Pluto:['Depth & transformation','how you engage with change and shared power'],'North Node':['A direction to explore','a symbolic invitation to try less familiar patterns'],'South Node':['Familiar patterns','a symbolic lens on habits and existing strengths'],Ascendant:['Your approach to life','the way you enter situations and meet the world'],Midheaven:['Vocation & public direction','the contribution you want to develop and make visible'],Descendant:['Partnership & encounter','the qualities you explore through close relationship'],'Imum Coeli':['Roots & private foundations','the inner ground from which you grow']};
  const aspectCopy={Conjunction:'These themes occupy similar territory. Explore how they can work together without one drowning out the other.',Sextile:'These themes suggest an opening that grows through participation. A small, deliberate action can help you use it.',Square:'These themes can pull in different directions. Give each a clear role and look for a practice that makes the tension useful.',Trine:'These themes may feel naturally compatible. Notice the ease available here, and choose how to use it with intention.',Opposition:'These themes face one another across the chart. Make room for both sides instead of asking one to carry the whole story.','Semi-sextile':'These themes sit side by side but speak different languages. Small, patient adjustments can help them learn from each other.','Semi-square':'These themes can rub together with a low, persistent friction. Notice where a minor irritation asks for a small change of habit.',Sesquiquadrate:'These themes can meet with a restless push. Look for the practical step that turns the pressure into something useful.',Quincunx:'These themes share little common ground. Rather than forcing a fit, find ways for each to be honoured on its own terms.'};
  const systemNames={placidus:'Placidus','whole-sign':'Whole Sign',equal:'Equal'};
  const allPoints=model=>[...model.points,...model.axes];
  const degree=value=>`${Math.floor(value)}°${String(Math.floor((value%1)*60)).padStart(2,'0')}′`;
  const motion=point=>point.kind==='angle'?'Chart angle':point.kind==='node'?'Mean node · retrograde':point.stationary?'Near station':point.retrograde?'Retrograde':'Direct';
  const styles=`.n-ring{fill:none;stroke:#d9bd86;stroke-width:1}.n-sector{fill:#182b39;stroke:#8e866f;stroke-width:.6}.n-sign{fill:#f7dfb4;font:23px "Segoe UI Symbol","Apple Symbols",serif;text-anchor:middle}.n-sign-name{fill:#cbdce0;font:10px sans-serif;text-anchor:middle}.n-cusp{stroke:#c5bc9e;stroke-width:.7;opacity:.5}.n-house{fill:#d9c8a8;font:11px sans-serif;text-anchor:middle}.n-aspect{stroke:#8dd0c8;stroke-width:.7;opacity:.4}.n-aspect.hard{stroke:#e7a19d}.n-aspect.chosen{stroke:#fff0bf;stroke-width:2;opacity:1}.n-aspect.minor{stroke:#b8cdd5;stroke-width:.6;stroke-dasharray:3 3;opacity:.3}.n-aspect.minor.chosen{stroke:#fff0bf;stroke-width:2;stroke-dasharray:none;opacity:1}.n-leader{stroke:#a8c5d0;stroke-width:.6;opacity:.65}.n-marker{fill:#d6edeb;stroke:#14212f;stroke-width:1}.n-planet{fill:#fae5be;font:24px "Segoe UI Symbol","Apple Symbols",serif;text-anchor:middle}.n-degree{fill:#d3e3e5;font:9px sans-serif;text-anchor:middle}.n-point{cursor:pointer}.n-point.selected .n-planet,.n-point:focus .n-planet{fill:#fff}.n-point.selected circle,.n-point:focus circle{stroke:#f8d992;stroke-width:2;fill:#27505b}.n-hit{fill:#14212f;stroke:none}.n-axis{stroke:#e3c38c;stroke-width:1.5}.n-axis-name{fill:#fff0c4;font:10px sans-serif;text-anchor:middle}.n-point:focus{outline:none}.n-title{fill:#acc9ce;font:9px sans-serif;letter-spacing:1px;text-anchor:middle}`
    // Ivory: the ink-light paper palette. Scoped to .ivory because an inline SVG's <style> applies to the whole page.
    +[['>rect','fill:#fbf7ee'],[' .n-ring','stroke:#9a7b45'],[' .n-sector','fill:#f4ecdc;stroke:#c9b58f'],[' .n-sign','fill:#7a5418'],[' .n-sign-name','fill:#56676c'],[' .n-cusp','stroke:#7d735c;opacity:.6'],[' .n-house','fill:#6d5733'],[' .n-point circle','fill:#fbf7ee'],[' .n-aspect','stroke:#2d7f78;opacity:.6'],[' .n-aspect.hard','stroke:#b4544d'],[' .n-aspect.minor','stroke:#7f98a2;opacity:.5'],[' .n-leader','stroke:#8aa1a9;opacity:.8'],[' .n-marker','fill:#2b4f5c;stroke:#fbf7ee'],[' .n-planet','fill:#1d2b36'],[' .n-degree','fill:#4a5c62'],[' .n-axis','stroke:#9a7331'],[' .n-axis-name','fill:#7a5418'],[' .n-title','fill:#8f9fa3']].map(([sel,rule])=>`.natal-wheel.ivory${sel}{${rule}}`).join('');
  function renderWheel(model,selection={kind:'point',key:'Sun'},interactive=false,showAspects=true,showMinor=false,palette='midnight') {
    const center=300,point=(r,longitude)=>{const angle=(180-(longitude-model.angles.asc))*Math.PI/180;return [center+r*Math.cos(angle),center+r*Math.sin(angle)];};
    const line=(a,b,cls,extra='')=>`<line class="${cls}" x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" ${extra}/>`;
    const sectors=E.signNames.map((name,index)=>{
      const a=point(272,index*30),b=point(272,(index+1)*30),c=point(231,(index+1)*30),d=point(231,index*30),label=point(252,index*30+15);
      return `<path class="n-sector" d="M${a} A272 272 0 0 0 ${b} L${c} A231 231 0 0 1 ${d} Z"/><text class="n-sign" x="${label[0]}" y="${label[1]+1}">${E.signGlyphs[index]}\uFE0E</text><text class="n-sign-name" x="${label[0]}" y="${label[1]+14}">${name}</text>`;
    }).join('');
    const ticks=Array.from({length:72},(_,i)=>line(point(i%6===0?278:282,i*5),point(287,i*5),'n-cusp')).join('');
    const houses=model.cusps.map((cusp,index)=>{
      const midpoint=cusp+E.mod(model.cusps[(index+1)%12]-cusp)/2,label=point(143,midpoint);
      const selected=selection.kind==='house'&&selection.key===String(index+1);
      return `${line(point(123,cusp),point(230,cusp),'n-cusp')}<g class="n-point${selected?' selected':''}" ${interactive?`role="button" tabindex="0" data-natal-kind="house" data-natal-key="${index+1}" aria-label="Inspect house ${index+1}: ${houseNames[index]}" aria-pressed="${selected}"`:''}><circle cx="${label[0]}" cy="${label[1]-3}" r="12" fill="#101d2b"/><text class="n-house" x="${label[0]}" y="${label[1]+1}">${index+1}</text></g>`;
    }).join('');
    const lookup=Object.fromEntries(allPoints(model).map(item=>[item.name,item]));
    const aspectLine=(aspect,cls)=>line(point(120,lookup[aspect.a].longitude),point(120,lookup[aspect.b].longitude),`n-aspect${cls}${selection.kind==='aspect'&&selection.key===aspect.id?' chosen':''}`);
    // Minor lines draw first, underneath the majors; .n-aspect.minor in the SVG styles string above draws them lighter and dashed.
    const aspects=showAspects?`${showMinor?(model.minorAspects||[]).map(aspect=>aspectLine(aspect,' minor')).join(''):''}${model.aspects.map(aspect=>aspectLine(aspect,['Square','Opposition'].includes(aspect.type)?' hard':'')).join('')}`:'';
    // Separate crowded glyphs; leader lines retain their exact ecliptic positions.
    const sorted=[...model.points].sort((a,b)=>a.longitude-b.longitude);
    let gapIndex=0,gap=0;
    sorted.forEach((item,index)=>{const g=E.mod(sorted[(index+1)%sorted.length].longitude-item.longitude);if(g>gap){gap=g;gapIndex=(index+1)%sorted.length;}});
    const ordered=[...sorted.slice(gapIndex),...sorted.slice(0,gapIndex)];
    const base=ordered[0].longitude,actual=ordered.map(item=>base+E.mod(item.longitude-base));
    const labels=actual.map((angle,index)=>index===0?angle:0);
    for(let i=1;i<labels.length;i++) labels[i]=Math.max(actual[i],labels[i-1]+13);
    const shift=labels.reduce((sum,angle,index)=>sum+angle-actual[index],0)/labels.length;
    const planets=ordered.map((item,index)=>{
      const label=point(195,labels[index]-shift),anchor=point(165,item.longitude),selected=selection.kind==='point'&&selection.key===item.name;
      return `${line(anchor,label,'n-leader')}<circle class="n-marker" cx="${anchor[0]}" cy="${anchor[1]}" r="2.5"/><g class="n-point${selected?' selected':''}" ${interactive?`role="button" tabindex="0" data-natal-kind="point" data-natal-key="${item.name}" aria-label="Inspect ${item.name}: ${item.sign} ${item.degrees}" aria-pressed="${selected}"`:''}><circle class="n-hit" cx="${label[0]}" cy="${label[1]-3}" r="18"/><text class="n-planet" x="${label[0]}" y="${label[1]+3}">${item.symbol}\uFE0E</text><text class="n-degree" x="${label[0]}" y="${label[1]+18}">${item.degrees}${item.retrograde?' ℞':''}</text></g>`;
    }).join('');
    const axes=model.axes.map(item=>{
      const pos=point(291,item.longitude);
      return `${line(point(225,item.longitude),point(280,item.longitude),'n-axis')}<text class="n-axis-name" x="${pos[0]}" y="${pos[1]+3}">${item.symbol}</text>`;
    }).join('');
    return `<svg xmlns="http://www.w3.org/2000/svg" class="natal-wheel${palette==='ivory'?' ivory':''}" viewBox="0 0 600 600" ${interactive?'role="group" aria-label="Calculated natal chart: choose a planet or house"':'role="img" aria-label="Calculated natal chart with planets, houses and aspects"'}><style>${styles}</style><rect width="600" height="600" rx="300" fill="#101d2b"/><circle class="n-ring" cx="300" cy="300" r="289"/>${sectors}${ticks}${houses}<circle class="n-ring" cx="300" cy="300" r="122"/>${aspects}${planets}${axes}<text class="n-title" x="300" y="303">ISHTAR INSIGHTS</text></svg>`;
  }
  function detail(model,selection) {
    if(selection.kind==='house') {
      const number=Number(selection.key),cusp=E.placement(model.cusps[number-1]),occupants=model.points.filter(point=>point.house===number);
      return `<p class="reading-label">${systemNames[model.houseSystem]} houses</p><h3>House ${number}</h3><p class="natal-detail-theme">${houseNames[number-1]}</p><dl><div><dt>Cusp</dt><dd>${cusp.sign}</dd></div><div><dt>Degree</dt><dd>${cusp.degrees}</dd></div></dl><p>This part of the chart is traditionally associated with ${houseNames[number-1].toLowerCase()}. Its ${cusp.sign} cusp adds a lens of ${lenses[cusp.index]}.</p><p class="sky-explorer-prompt"><strong>Placements here</strong>${occupants.map(point=>point.name).join(' · ') || 'No planets or nodes here. An unoccupied house is still part of the chart.'}</p><p class="sky-explorer-prompt"><strong>Journal prompt</strong>${housePrompts[number-1]}</p>`;
    }
    if(selection.kind==='aspect') {
      const aspect=[...model.aspects,...(model.minorAspects||[])].find(item=>item.id===selection.key);
      if(!aspect) return '';
      return `<p class="reading-label">${aspect.type} · ${aspect.tone}</p><h3>${aspect.a}<br><span class="natal-aspect-symbol">${aspect.symbol}</span> ${aspect.b}</h3><dl><div><dt>Angle</dt><dd>${aspect.angle}°</dd></div><div><dt>Orb</dt><dd>${degree(aspect.orb)}</dd></div></dl><p>${roles[aspect.a][0]} meets ${roles[aspect.b][0].toLowerCase()}. ${aspectCopy[aspect.type]}</p><p class="sky-explorer-prompt"><strong>${aspect.applying===null?'Contact to a chart angle':aspect.applying?'Applying aspect':'Separating aspect'}</strong>${aspect.applying===null?'This contact describes the chart at the entered moment.':aspect.applying?'The bodies are moving toward the exact aspect at this moment.':'The bodies are moving away from the exact aspect at this moment.'}</p><p class="sky-explorer-prompt"><strong>Journal prompt</strong>Where do these two themes meet in your everyday choices?</p>`;
    }
    const item=allPoints(model).find(point=>point.name===selection.key) || model.points[0],role=roles[item.name];
    return `<p class="reading-label">${item.kind==='node'?'Mean lunar node':item.kind==='angle'?'Calculated chart angle':'Natal placement'}</p><h3>${item.name}<br><span class="natal-detail-sign">in ${item.sign}</span></h3><p class="natal-detail-theme">${role[0]}</p><dl><div><dt>Longitude</dt><dd>${item.degrees} ${item.glyph}\uFE0E</dd></div><div><dt>House</dt><dd>${item.house}</dd></div><div><dt>Element</dt><dd>${item.element}</dd></div><div><dt>Quality</dt><dd>${item.quality}</dd></div></dl><p>In this reading, ${item.name} represents ${role[1]}. ${item.sign} brings an emphasis on ${lenses[item.index]}.</p><p class="sky-explorer-prompt"><strong>House ${item.house} · ${houseNames[item.house-1]}</strong>Explore how this theme shows up through ${houseNames[item.house-1].toLowerCase()}.</p>${item.kind!=='angle'?`<p class="sky-explorer-prompt"><strong>${motion(item)}</strong>${item.kind==='node'?'Mean nodes describe the averaged lunar orbital axis, not a physical planet.':item.retrograde?'Retrograde describes apparent backward motion from Earth. As a reflection, consider where review or an inward approach is useful.':'Direct motion is the usual forward movement through the zodiac.'}</p>`:''}<p class="sky-explorer-prompt"><strong>Journal prompt</strong>${housePrompts[item.house-1]}</p>`;
  }
  function bigThree(model) {
    return `<div class="natal-big-three">${[model.points[0],model.points[1],model.axes[0]].map(item=>`<button type="button" data-open-natal="point" data-natal-key="${item.name}"><span>${item.name==='Ascendant'?'Rising':item.name}</span><strong>${item.glyph}\uFE0E ${item.sign}</strong><small>${item.degrees}</small></button>`).join('')}</div>`;
  }
  const methodNotes=model=>`<p>Positions use Astronomy Engine 2.1.19, a tropical zodiac and geocentric ecliptic longitudes. Time-zone conversion uses the browser’s historical IANA rules. Placidus divides semi-diurnal and semi-nocturnal arcs; Whole Sign starts the first house at the beginning of the rising sign; Equal starts at the Ascendant and uses twelve 30° houses. Polar charts use Whole Sign if Placidus is unavailable.</p><p>The lunar nodes are mean nodes. Major aspects use ${E.aspectTypes.map(type=>`${type.name.toLowerCase()} ${degree(type.orb*model.orbScale)}`).join(', ')} maximum orbs. Minor aspects, when included, use a fixed ${degree(2)} orb. Applying/separating is estimated from motion around the birth moment. Interpretations are original reflective writing, not predictions. Birth time and place precision affect the angles and houses.</p>`;
  function report(model,view='placements',filter='all',showMinor=false) {
    const tableRows=allPoints(model).map(item=>`<tr><th scope="row"><button type="button" data-open-natal="point" data-natal-key="${item.name}"><span aria-hidden="true">${item.symbol}\uFE0E</span> ${item.name}</button></th><td>${item.sign}<small>${item.degrees}</small></td><td>${item.house}</td><td>${motion(item)}</td></tr>`).join('');
    const listed=showMinor?[...model.aspects,...(model.minorAspects||[])].sort((a,b)=>a.orb-b.orb):model.aspects,filtered=listed.filter(item=>filter==='all'||item.type===filter);
    return `<section class="natal-report" aria-label="Natal chart report"><header><div><p class="reading-label">Your chart, in detail</p><h4>The pattern of your sky</h4></div><button type="button" data-print-natal><span aria-hidden="true">⎙</span> Print or save as PDF</button></header><p class="natal-calculation-line">Tropical zodiac · ${systemNames[model.houseSystem]} houses · ${esc(model.timeZone)} · ${esc(model.date.slice(0,16).replace('T',' '))} UTC</p>${model.notice?`<p class="natal-notice">${model.notice}</p>`:''}<div class="natal-report-nav" role="group" aria-label="Natal chart details">${[['placements','Placements'],['houses','Houses'],['aspects','Aspects'],['balance','Balance']].map(([key,name])=>`<button type="button" data-natal-view="${key}" aria-pressed="${view===key}" aria-controls="natal-${key}">${name}</button>`).join('')}</div>
      <div id="natal-placements" class="natal-report-panel"${view==='placements'?'':' hidden'}><div class="natal-table-scroll" tabindex="0" aria-label="Planet placements table"><table><thead><tr><th scope="col">Body / point</th><th scope="col">Sign & degree</th><th scope="col">House</th><th scope="col">Motion</th></tr></thead><tbody>${tableRows}</tbody></table></div></div>
      <div id="natal-houses" class="natal-report-panel"${view==='houses'?'':' hidden'}><div class="natal-house-grid">${model.cusps.map((cusp,index)=>{const p=E.placement(cusp);return `<button type="button" data-open-natal="house" data-natal-key="${index+1}"><span class="house-number">${index+1}</span><span><strong>${houseNames[index]}</strong><small>${p.glyph}\uFE0E ${p.sign} · ${p.degrees}</small></span></button>`;}).join('')}</div></div>
      <div id="natal-aspects" class="natal-report-panel"${view==='aspects'?'':' hidden'}><div class="natal-aspect-controls"><label class="natal-aspect-filter">Aspect type <select id="natal-aspect-filter"><option value="all">${showMinor?'All aspects':'All major aspects'}</option>${[...E.aspectTypes,...(showMinor?E.minorAspectTypes:[])].map(type=>`<option${filter===type.name?' selected':''}>${type.name}</option>`).join('')}</select></label><label class="natal-aspect-filter"><input type="checkbox" id="natal-minor-aspects"${showMinor?' checked':''}> Include minor aspects</label></div><p class="natal-panel-hint">${filtered.length} contacts · tightest orbs first · choose a contact for its interpretation.</p><div class="natal-aspect-grid">${filtered.map(item=>`<button type="button" data-open-natal="aspect" data-natal-key="${item.id}"><span class="aspect-mark ${['Square','Opposition'].includes(item.type)?'hard':''}">${item.symbol}</span><span><strong>${item.a} · ${item.b}</strong><small>${item.type} · orb ${degree(item.orb)}${item.applying===null?'':item.applying?' · applying':' · separating'}</small></span></button>`).join('') || '<p>No contacts within these orbs.</p>'}</div></div>
      <div id="natal-balance" class="natal-report-panel"${view==='balance'?'':' hidden'}><p class="natal-panel-hint">An equal count of the ten planets. Nodes and chart angles are excluded.</p><div class="natal-balance-grid">${[['Elements',model.balance.elements],['Qualities',model.balance.qualities]].map(([title,values])=>`<article><h5>${title}</h5>${Object.entries(values).map(([name,count])=>`<div class="natal-balance-row"><span>${name}</span><meter min="0" max="10" value="${count}" aria-label="${name}: ${count} of 10 planets"></meter><strong>${count}/10</strong></div>`).join('')}</article>`).join('')}</div><p class="natal-panel-hint">Use the distribution as a conversation starter. A low count is not a deficiency.</p></div>
      <details class="insight-method"><summary>Calculation settings & interpretation notes</summary>${methodNotes(model)}<p>Sources: <a href="https://github.com/cosinekitty/astronomy" target="_blank" rel="noopener">Astronomy Engine</a> · <a href="https://www.astro.com/swisseph/swisseph.htm" target="_blank" rel="noopener">house-system definitions</a> · <a href="docs/NATAL-CHART.md" target="_blank" rel="noopener">methods & validation</a></p></details></section>`;
  }
  function download(model,selection,showAspects=true,showMinor=false,palette='midnight') {
    const blob=new Blob([renderWheel(model,selection,false,showAspects,showMinor,palette)],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');
    link.href=url;link.download=`ishtar-natal-${model.birthday}${palette==='ivory'?'-ivory':''}.svg`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  // The keepsake edition: a print-only document, rendered on demand and never shown on screen.
  const noSelection={kind:'none'};
  function birthLabel(model) {
    const moment=new Date(`${model.birthday}T${model.time}:00Z`);
    return {date:new Intl.DateTimeFormat(undefined,{dateStyle:'long',timeZone:'UTC'}).format(moment),time:new Intl.DateTimeFormat(undefined,{timeStyle:'short',timeZone:'UTC'}).format(moment)};
  }
  const keepsakeTitle=model=>`Natal chart · ${birthLabel(model).date} · Ishtar Insights`;
  function keepsake(model,{place='',palette='ivory',showMinor=false}={}) {
    const when=birthLabel(model),[sun,moon]=model.points,[asc,mc]=model.axes,hard=aspect=>['Square','Opposition'].includes(aspect.type);
    const minor=aspect=>E.minorAspectTypes.some(type=>type.name===aspect.type);
    const aspects=(showMinor?[...model.aspects,...(model.minorAspects||[])]:model.aspects).slice().sort((a,b)=>a.orb-b.orb);
    const pair=Object.fromEntries(aspects.flatMap(a=>[[`${a.a}|${a.b}`,a],[`${a.b}|${a.a}`,a]]));
    const bodies=[...model.points,asc,mc];
    const grid=bodies.map((row,i)=>`<tr>${bodies.slice(0,i).map(col=>{const a=pair[`${row.name}|${col.name}`];return a?`<td class="${hard(a)?'hard':''}${minor(a)?' minor':''}">${a.symbol}<small>${Math.floor(a.orb)}°</small></td>`:'<td></td>';}).join('')}<th>${row.symbol}\uFE0E</th></tr>`).join('');
    const page=(number,title,body,cls='')=>`<section class="nk-page${cls}"><header class="nk-running"><span>Ishtar Insights</span><span>${when.date}</span></header>${title?`<h2><span>${number}</span>${title}</h2>`:''}${body}</section>`;
    const prompts=[[`The Sun in house ${sun.house}`,housePrompts[sun.house-1]],[`The Moon in house ${moon.house}`,housePrompts[moon.house-1]],[`${asc.sign} rising`,housePrompts[0]],[`Midheaven in ${mc.sign}`,housePrompts[9]]].filter((item,index,all)=>all.findIndex(other=>other[1]===item[1])===index);
    const lines='<span></span>'.repeat(4);
    return `<article class="natal-keepsake" aria-hidden="true">
      <section class="nk-page nk-cover"><header class="nk-mast"><span>Ishtar Insights</span><span>Natal chart · keepsake edition</span></header>
        <p class="nk-eyebrow">The sky at the moment you arrived</p><h1>${when.date}</h1><p class="nk-when">${when.time}${place?` · ${esc(place)}`:''}</p>
        <figure class="nk-wheel">${renderWheel(model,noSelection,false,true,showMinor,palette)}</figure>
        <div class="nk-big-three">${[['Sun',sun],['Moon',moon],['Rising',asc]].map(([label,item])=>`<div><span>${label}</span><strong>${item.glyph}\uFE0E ${item.sign}</strong><small>${item.degrees} · house ${item.house}</small><p>${roles[item.name][0]}</p></div>`).join('')}</div>
        <footer class="nk-colophon">Tropical zodiac · ${systemNames[model.houseSystem]} houses · ${esc(model.timeZone)} · ${esc(model.date.slice(0,16).replace('T',' '))} UTC</footer></section>
      ${page('I','Placements',`<table class="nk-placements"><thead><tr><th scope="col">Body</th><th scope="col">Position</th><th scope="col">House</th><th scope="col">In this reading</th></tr></thead><tbody>${allPoints(model).map(item=>`<tr><th scope="row"><b${item.kind==='angle'?' class="nk-angle"':''}>${item.symbol}\uFE0E</b>${item.name}<small>${motion(item)}</small></th><td><b>${item.glyph}\uFE0E</b>${item.sign}<small>${item.degrees}</small></td><td>${item.house}</td><td><strong>${roles[item.name][0]}</strong>${item.sign} brings ${lenses[item.index]}.</td></tr>`).join('')}</tbody></table>`)}
      ${page('II','Houses',`<p class="nk-lede">${systemNames[model.houseSystem]} houses. Each cusp sign colours the area of life its house describes.</p><div class="nk-houses">${model.cusps.map((cusp,index)=>{const p=E.placement(cusp),here=model.points.filter(point=>point.house===index+1);return `<div><span class="nk-house-number">${index+1}</span><strong>${houseNames[index]}</strong><small>${p.glyph}\uFE0E ${p.sign} · ${p.degrees}</small><p>Through ${lenses[p.index]}.</p><em>${here.map(point=>`${point.symbol}\uFE0E ${point.name}`).join(' · ')||'No planets here'}</em></div>`;}).join('')}</div><div class="nk-method"><h3>About this chart</h3>${methodNotes(model)}</div>`)}
      ${page('III','Aspects',`<div class="nk-aspect-layout"><figure class="nk-grid"><table>${grid}</table><figcaption>Aspect grid · symbol and whole-degree orb${showMinor?' · minor aspects lighter':''}</figcaption></figure><div class="nk-balance">${[['Elements',model.balance.elements],['Qualities',model.balance.qualities]].map(([title,values])=>`<h3>${title}</h3>${Object.entries(values).map(([name,count])=>`<div class="nk-bar"><span>${name}</span><i style="--n:${count}"></i><b>${count}</b></div>`).join('')}`).join('')}<p>Ten planets, counted equally. A low count is not a deficiency.</p></div></div><ol class="nk-aspects">${aspects.map(a=>`<li class="${hard(a)?'hard':''}${minor(a)?' minor':''}"><b>${a.symbol}</b><span>${a.a} · ${a.b}<small>${a.type} · orb ${degree(a.orb)}${a.applying===null?'':a.applying?' · applying':' · separating'}</small></span></li>`).join('')||'<li>No contacts within these orbs.</li>'}</ol>`)}
      ${page('IV','Reflections',`<p class="nk-lede">A chart is a set of questions more than answers. Take one at a time, and write what comes.</p>${prompts.map(([label,prompt])=>`<div class="nk-prompt"><span>${label}</span><p>${prompt}</p><div class="nk-lines">${lines}</div></div>`).join('')}`)}
    </article>`;
  }
  function keepsakePanel(model,palette='ivory') {
    const choice=(key,name,note)=>`<button type="button" data-keepsake-palette="${key}" aria-pressed="${palette===key}"><strong>${name}</strong><small>${note}</small></button>`;
    return `<section class="natal-keepsake-panel" aria-labelledby="natal-keepsake-title"><div class="nk-previews" aria-hidden="true"><span class="nk-thumb nk-thumb-cover">${renderWheel(model,noSelection,false,true,false,palette)}<i></i><i></i></span><span class="nk-thumb nk-thumb-table"><i></i><i></i><i></i><i></i><i></i><i></i></span><span class="nk-thumb nk-thumb-grid"><i></i><i></i><i></i></span><span class="nk-thumb nk-thumb-lines"><i></i><i></i><i></i><i></i></span></div>
      <div class="nk-panel-copy"><p class="reading-label">Keepsake edition</p><h5 id="natal-keepsake-title">Print your chart, or keep it as a PDF</h5><p>Five pages set for paper: your wheel and big three, every placement and house, an aspect grid with your elemental balance, and reflection prompts with room to write.</p>
        <div class="nk-palette-choice" role="group" aria-label="Wheel style for printing">${choice('ivory','Ivory','Light and ink-friendly')}${choice('midnight','Midnight','The night-sky wheel')}</div>
        <div class="nk-panel-actions"><button type="button" class="nk-print" data-print-natal><span aria-hidden="true">⎙</span> Print or save as PDF</button><button type="button" data-natal-download>Download the wheel · SVG</button></div>
        <p class="nk-panel-hint">For a PDF, choose “Save as PDF” as the printer. Turning off headers and footers in the print dialog gives the cleanest pages.</p></div></section>`;
  }
  return {renderWheel,detail,bigThree,report,download,keepsake,keepsakeTitle,keepsakePanel,systemNames,degree};
})();
