/* Original reflections and local-only interactions for the numerology studio. */
const Numerology = (() => {
  'use strict';
  const E = NumerologyEngine;
  const esc = value => String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const themes = {
    1:{title:'The courage to begin',words:'Initiative · independence · direction',story:'One offers a lens on the moment you stop waiting for a ready-made path. Its symbolism centers on agency: deciding what matters, taking the first step, and allowing experience to refine the plan.',capacity:'A clear intention can give scattered effort a direction. Let independence include the freedom to choose your own pace.',edge:'Notice when self-reliance becomes a refusal to receive help, or when starting something new keeps you from finishing what matters.',connection:'Make your preference clear while leaving room for another person’s equally real needs.',work:'Choose a modest experiment that puts an idea into motion. Give it an end point at which you will review what you learned.',practice:'Begin one thing you have been waiting to feel fully ready for. Keep the first step small.',prompt:'Where can I act with more agency and less need to prove myself?'},
    2:{title:'The art of meeting',words:'Cooperation · sensitivity · reciprocity',story:'Two brings attention to the space between people, ideas, and needs. Its symbolism asks what becomes possible when listening is active and an agreement leaves room for both sides.',capacity:'Patience and careful listening can reveal a possibility that speed would miss. Notice the value of an honest exchange.',edge:'Keeping the peace can become a way of disappearing from the conversation. Agreement is more useful when your own preference is present.',connection:'Ask what mutual care looks like in actions, rather than assuming you both mean the same thing by it.',work:'Invite a second perspective before settling the plan. Clarify who will do what and how you will check in.',practice:'Make one clear request, and offer another person space to answer honestly.',prompt:'What would cooperation look like if my needs were included?'},
    3:{title:'A voice of your own',words:'Expression · imagination · connection',story:'Three opens a conversation about expression: giving a feeling, observation, or idea a form that can be shared. Its symbolism makes space for play, experimentation, and the pleasure of finding the right words.',capacity:'Imagination can connect things that first seemed unrelated. Give an unfinished idea a kind audience and a little room to develop.',edge:'Expression can scatter into performance or too many beginnings. Choose what you want to say before deciding how it should be received.',connection:'Let humor and warmth make room for honesty, including the feeling that is harder to express.',work:'Bring one idea out of your head and into a draft, sketch, demonstration, or conversation.',practice:'Make something for twenty minutes without editing it as you go.',prompt:'What wants expression before it needs approval?'},
    4:{title:'A foundation worth tending',words:'Structure · craft · steadiness',story:'Four asks how a meaningful intention becomes part of everyday life. Its symbolism lives in the useful framework: a practice, boundary, or dependable arrangement that makes room for something to grow.',capacity:'Steady attention can turn a vague wish into a workable commitment. Let the structure support a life you actually want to live.',edge:'A helpful rule can outlast its purpose. Check whether consistency is offering support or demanding that nothing ever change.',connection:'Build trust through a promise you can keep, and renegotiate early when the conditions change.',work:'Break the work into repeatable steps. Improve one part of the method instead of rebuilding everything at once.',practice:'Repair or simplify one routine that affects the rest of your day.',prompt:'Which structure supports me, and which one needs to become more flexible?'},
    5:{title:'Room for discovery',words:'Change · curiosity · adaptability',story:'Five turns toward experience, movement, and a willingness to revise the familiar. Its symbolism invites a conscious experiment: discovering what freedom means when it is paired with attention to consequences.',capacity:'A fresh perspective can loosen a stale problem. Let curiosity broaden your options before deciding what needs to change.',edge:'Constant novelty can become a way of avoiding discomfort or a commitment. Distinguish a nourishing change from an escape that repeats the same pattern.',connection:'Talk about the balance between freedom and reliability rather than expecting the other person to guess it.',work:'Try a different route or method, then compare the result with what you already know.',practice:'Change one small part of your usual approach and observe what it teaches you.',prompt:'What kind of freedom would make my life fuller, rather than simply busier?'},
    6:{title:'Care with a center',words:'Responsibility · belonging · harmony',story:'Six considers how care becomes sustainable. Its symbolism points toward home, relationships, and the quality of what you tend, while asking that your own needs remain inside the circle of responsibility.',capacity:'Attention to ordinary needs can make a place or relationship feel more welcoming. Let care be specific enough to receive.',edge:'Taking responsibility for everyone’s comfort can leave little room for their agency or your rest. A caring boundary can strengthen the relationship.',connection:'Ask what support is wanted before offering a solution. Make room to receive care as well as give it.',work:'Improve the conditions in which people do their work. Share a practical responsibility instead of quietly absorbing it.',practice:'Choose one act of care for yourself and one you can offer without resentment.',prompt:'How can I care deeply without carrying what belongs to someone else?'},
    7:{title:'The question beneath',words:'Inquiry · reflection · understanding',story:'Seven offers a lens on attention, solitude, and the search for understanding. Its symbolism favors a thoughtful pause: examining an assumption, following a worthwhile question, and letting evidence change your view.',capacity:'Depth can come from spending longer with one question. Quiet attention may reveal a distinction that constant input has blurred.',edge:'Reflection can turn into distance or endless preparation. Notice when the next insight needs an experience rather than another explanation.',connection:'Share enough of your inner process for someone to meet you there. Privacy does not have to mean disconnection.',work:'Set aside a period for focused study, then translate what you learn into a useful test or clear explanation.',practice:'Spend a little undistracted time with a question, then write one thing you can investigate.',prompt:'What do I understand more clearly when I slow down and look again?'},
    8:{title:'Purposeful stewardship',words:'Agency · organization · responsibility',story:'Eight examines how intention meets resources, decisions, and shared consequences. Its symbolism is an invitation to use influence responsibly and define success in terms that remain meaningful after the visible result.',capacity:'Clear priorities can bring people, time, and effort into a workable arrangement. Notice the value of accountable leadership.',edge:'An external measure of success can crowd out the life it was meant to serve. Consider the human cost of a goal and the fairness of the process.',connection:'Make expectations and the balance of responsibility explicit. Leave room for a voice that carries less formal authority.',work:'Choose a useful outcome, identify the resources it needs, and decide how progress will be judged fairly.',practice:'Review one commitment against your actual capacity, then make a clear adjustment.',prompt:'What would success look like if responsibility and enough were part of its definition?'},
    9:{title:'What you carry forward',words:'Completion · compassion · perspective',story:'Nine gathers a cycle into a wider view. Its symbolism makes room for completion, letting go, and an awareness of the people and experiences that have shaped the work. An ending can be honored without being prolonged.',capacity:'Perspective can help separate an enduring value from the form it once took. Keep the learning while allowing the next chapter to differ.',edge:'A wish to help everyone can become diffuse, or an attachment to a meaningful past can delay a necessary ending. Make care concrete and release deliberate.',connection:'Acknowledge what a relationship has taught you while staying attentive to what it needs in the present.',work:'Finish, document, or pass on a piece of work. Give a useful contribution a form that others can carry forward.',practice:'Complete one loose end and name one lesson you want to take with you.',prompt:'What is ready to be completed, and what wisdom should continue?'},
    11:{title:'Insight given a voice',words:'Master 11 · perception · connection',story:'Eleven is retained as a master number in this method, alongside its root of two. Read it as a symbolic conversation between a vivid idea or impression and the patient work of making it understandable to someone else.',capacity:'A subtle observation can become useful when it is expressed clearly and checked against experience. Give an insight a grounded form.',edge:'The master-number label is not a demand to be exceptional. Let an impression remain a question until observation or conversation supports it.',connection:'Pair sensitivity with a direct question. Another person’s experience is best learned by asking.',work:'Translate a larger idea into an example, image, or prototype that someone else can respond to.',practice:'Write down an insight, then name one ordinary way to explore whether it is useful.',prompt:'How could I give an important impression a clear and grounded expression?'},
    22:{title:'A vision made workable',words:'Master 22 · vision · practical craft',story:'Twenty-two is retained as a master number in this method, alongside its root of four. Its symbolism joins a broad vision with the small, dependable structures that allow people to build something together.',capacity:'A worthwhile ambition can become approachable when it has a clear first phase. Let the plan grow from what the work teaches you.',edge:'A large ideal can make ordinary progress feel inadequate. There is no requirement to build something monumental for your effort to matter.',connection:'Share ownership of the vision. Ask the people involved what they need for the arrangement to remain workable.',work:'Define one useful milestone, the support it requires, and what you can simplify before beginning.',practice:'Bring a big idea down to one realistic promise you can keep this week.',prompt:'What small structure would let a larger possibility begin to take shape?'},
    33:{title:'Care that teaches',words:'Master 33 · compassion · contribution',story:'Thirty-three is retained as a master number in this method, alongside its root of six. Its symbolism brings care, expression, and service into conversation: offering what you have learned without making yourself responsible for every outcome.',capacity:'An experience shared with patience can make someone else’s path feel less lonely. Let generosity include respect for their choices.',edge:'Service becomes strained when it requires self-erasure or a perfect example. You can contribute while remaining a person with limits and unfinished learning.',connection:'Offer support that leaves the other person room to choose. Include your own need for rest and reciprocity.',work:'Make useful knowledge easier to understand or access. Ask what will help before deciding what to provide.',practice:'Share one useful thing you have learned, and leave yourself space to receive something in return.',prompt:'What can I offer generously without making it a measure of my worth?'}
  };
  const cycleCopy = {
    1:['Choose a beginning worth protecting. Let this year’s reflection center on the direction you want to establish, with enough room to learn as you go.','Give one fresh idea a practical first step this month. A beginning can be small and still change your relationship with the work.','Begin one manageable thing today. Decide what the first step is before asking yourself for confidence.'],
    2:['Consider the relationships, agreements, and patient tending that help an intention develop. Use this year’s theme to notice where cooperation needs a clearer conversation.','Make room for listening and adjustment this month. A useful agreement may matter more than a fast answer.','Give one exchange your full attention. Ask a clear question and leave room for the reply.'],
    3:['Explore how you want to express yourself and what you want to make visible. Give creativity a regular place rather than waiting for inspiration to carry the whole effort.','Choose something to share or make this month. Let enjoyment help the work develop without requiring every experiment to become a result.','Give a thought or feeling a simple form: a note, a sketch, or an honest conversation.'],
    4:['Look at the foundations that support your commitments. This is a useful year-theme for reviewing routines, improving a method, and choosing a pace you can sustain.','Bring order to one part of your life this month. Let the structure reduce effort rather than become another standard to meet.','Complete one practical step. A small repair or clear plan can make the next task easier.'],
    5:['Consider what a thoughtful change could teach you. Make space to explore, while distinguishing the freedom you want from movement for its own sake.','Try a fresh approach this month and notice its effects. Keep enough steadiness around the experiment to learn from it.','Change one small part of your usual routine. Stay curious about what feels more alive or more useful.'],
    6:['Reflect on care, belonging, and the responsibilities you want to keep. Let the year’s theme include fair sharing and the conditions that allow affection to last.','Tend a relationship, a shared space, or a commitment this month. Include a boundary that keeps the care sustainable.','Offer one specific act of care, including one for yourself. Ask before assuming what someone else needs.'],
    7:['Give a worthwhile question time to deepen. Use the year’s theme to review what you believe, make room for study, and turn reflection into a grounded understanding.','Protect a little time for focused inquiry this month. Look for the question underneath the obvious task.','Step back from extra input long enough to hear your own question. Write down what still needs evidence.'],
    8:['Review how you use your time, resources, and influence. Let this year’s reflection connect the results you seek with a fair process and a clear sense of enough.','Choose an outcome you can work toward responsibly this month. Clarify the scope, the resources, and the commitments involved.','Make one decision that respects your actual capacity. Let a clear priority organize the next step.'],
    9:['Consider what is ready for completion and what deserves to continue in another form. Honor a chapter by gathering its learning rather than requiring it to last forever.','Finish or release one lingering task this month. Give what you have learned a useful place in the next chapter.','Close one small loop. Acknowledge what it taught you before moving on.']
  };
  const roles = {
    path:{label:'Life Path',lens:'A broad theme to revisit across different chapters of life. Treat it as a question you can grow with, rather than a fixed description of who you must be.'},
    birthDay:{label:'Birth Day',lens:'A close-up on the day you were born. This reading keeps the full day visible and explores its reduced number as an everyday way of contributing; other traditions also interpret the compound day.'},
    attitude:{label:'Attitude',lens:'Also called a Sun number in some numerology systems. It combines your birth month and day as a lens on the way you begin, approach a situation, or respond to a new experience.'},
    expression:{label:'Expression',lens:'All the letters of the entered name contribute here. Use this as a lens on how you give your abilities and interests a form in the world.'},
    soul:{label:'Soul Urge',lens:'The vowels of the entered name contribute here; this is also called Heart’s Desire. Use it to explore what feels nourishing or meaningful from the inside.'},
    personality:{label:'Personality',lens:'The consonants of the entered name contribute here. This is a symbolic lens on outward expression, not a way to know what another person actually thinks of you.'},
    maturity:{label:'Maturity',lens:'Life Path and Expression are added together for a longer-view reflection on how experience and contribution might develop together. This does not assign an age or predict a future event.'}
  };
  const localToday = () => {const d=new Date();return E.dateKey(d.getFullYear(),d.getMonth()+1,d.getDate());};
  const numberLabel = result => result ? result.master?`${result.value}/${result.root}`:String(result.value) : '—';
  const trail = result => result.steps.join(' → ');
  const dateLabel = value => new Intl.DateTimeFormat(undefined,{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
  const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  function readNumber(result, role, calculation) {
    if(!result) return `<article class="num-reading num-empty"><h5>${roles[role].label} is not calculated</h5><p>No ${role==='soul'?'vowels':'consonants'} were selected in this spelling. Check the name and any Y choices; an empty group does not mean a missing quality.</p></article>`;
    const t=themes[result.value];
    return `<article class="num-reading"><header><div class="num-seal" aria-hidden="true"><span>${result.value}</span>${result.master?`<small>root ${result.root}</small>`:''}</div><div><p class="num-kicker">${roles[role].label} · ${numberLabel(result)}</p><h5>${t.title}</h5><p class="num-keywords">${t.words}</p></div></header><p class="num-role-lens">${roles[role].lens}</p><p>${t.story}</p><div class="num-reading-pair"><section><h6>A useful expression</h6><p>${t.capacity}</p></section><section><h6>Room to grow</h6><p>${t.edge}</p></section></div><div class="num-life-lenses"><section><h6>In connection</h6><p>${t.connection}</p></section><section><h6>In your work</h6><p>${t.work}</p></section><section><h6>A small practice</h6><p>${t.practice}</p></section></div><blockquote>${t.prompt}</blockquote><details class="num-method"><summary>See the calculation</summary>${calculation}</details></article>`;
  }
  function attach(root, parts, previous={}) {
    const birth=E.birthday(E.dateKey(parts.year,parts.month,parts.day));
    const initialToday=localToday(), lastDate='2100-12-31';
    const tabs=['birth','cycles','name','loshu'];
    const state={tab:tabs.includes(previous?.tab)?previous.tab:'birth',core:['path','birthDay','attitude'].includes(previous?.core)?previous.core:'path',cycleDate:previous?.cycleDate || initialToday,period:['year','month','day'].includes(previous?.period)?previous.period:'year',name:previous?.name || '',yVowels:previous?.yVowels || [],nameRead:Boolean(previous?.nameRead),nameKind:['expression','soul','personality','maturity'].includes(previous?.nameKind)?previous.nameKind:'expression'};
    if(!E.parseDate(state.cycleDate)||state.cycleDate<birth.parts.value) state.cycleDate=birth.parts.value;
    const controller=new AbortController(), $=selector=>root.querySelector(selector);
    root.classList.add('numerology-room');
    root.innerHTML=`<header class="num-intro"><div><p class="num-kicker">The numerology studio</p><h4>Numbers with a story.</h4><p>Explore the patterns of a birth date, the rhythm of a year, and the letters of a name. Follow the numbers into a richer conversation with yourself.</p><span class="num-birth-caption">Your birth date · ${dateLabel(birth.parts.value)}</span></div><div class="num-intro-orbit" aria-hidden="true"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span><i>✧</i></div></header>
      <nav class="num-tabs" aria-label="Numerology perspectives">${[['birth','Birth numbers','Your foundation'],['cycles','Personal cycles','Year · month · day'],['name','Name reading','Letters & expression'],['loshu','Lo Shu','The nine-cell square']].map(([id,label,sub])=>`<button type="button" data-num-tab="${id}" aria-pressed="${state.tab===id}" aria-controls="num-${id}">${label}<small>${sub}</small></button>`).join('')}</nav>
      <section id="num-birth" class="num-view"></section>
      <section id="num-cycles" class="num-view"><div class="num-section-heading"><p class="num-kicker">A changing rhythm</p><h5>Put a moment in perspective.</h5><p>Explore a date, then move through the year and the nine-year cycle around it.</p></div><div class="num-date-controls"><button type="button" data-num-day="-1" aria-label="Previous day">←</button><label for="num-cycle-date" class="sr-only">Date to explore</label><input id="num-cycle-date" type="date" value="${esc(state.cycleDate)}" min="${birth.parts.value}" max="${lastDate}"><button type="button" data-num-day="1" aria-label="Next day">→</button><button type="button" data-num-today>Today</button></div><div id="num-cycle-content"></div></section>
      <section id="num-name" class="num-view"><div class="num-section-heading"><p class="num-kicker">An optional name reading</p><h5>The letters you carry.</h5><p>Explore Expression, Soul Urge, Personality, and a longer-view Maturity number. The traditional starting point is your full name at birth; you can also explore another spelling as a variation.</p></div><form id="num-name-form"><label for="num-full-name">Name to explore</label><div class="num-name-entry"><input id="num-full-name" type="text" maxlength="120" value="${esc(state.name)}" placeholder="First, middle and last names…" autocomplete="off" spellcheck="false" aria-describedby="num-name-help"><button type="submit">Read this name <span aria-hidden="true">↗</span></button></div><p id="num-name-help">Include middle names; leave out titles and suffixes. Calculated in this page, with no upload or saved name.</p><fieldset id="num-y-options" hidden><legend>How does each Y sound?</legend><p>Check a Y when it acts as a vowel, as in Lynn. Leave it unchecked when it acts as a consonant, as at the start of Yara. Your choices affect Soul Urge and Personality.</p><div id="num-y-choices"></div></fieldset><p id="num-name-status" role="status"></p></form><div id="num-name-results"></div></section>
      <section id="num-loshu" class="num-view">${BirthdayInsights.renderNumbers(parts)}</section>
      <footer class="num-footnote"><p>A symbolic practice for reflection. These readings offer questions and perspectives, rather than measurements of personality or predictions.</p><details class="num-method"><summary>Traditions, methods & sources</summary><p>Birth and name readings use modern Pythagorean conventions. Life Path reduces the month, day and year separately, retaining 11, 22 and 33, then adds and reduces those values. Birth Day shows the original day alongside its reduced interpretation. Attitude adds month and day and always reduces to 1–9.</p><p>Personal cycles use calendar years beginning January 1, with no master numbers retained: birth month + birth day + selected year gives Personal Year; adding the selected month gives Personal Month; adding the day gives Personal Day. Some schools use birthday boundaries instead.</p><p>Name values repeat 1–9 across A–Z. This page adds the full name’s letters before reduction, retaining 11, 22 and 33 at the final reduction; it does not reduce each name separately first. Vowels and consonants are summed separately with the same rule. Maturity adds Life Path and Expression. Accents and common Latin ligatures are transliterated, and the exact A–Z spelling is shown. Other alphabets need a transliteration you choose. Master numbers are paired with their root, not treated as a rank or a measure of worth.</p><p>Lo Shu has its own Chinese cultural and mathematical context. Its modern birthday-digit overlay remains separate from these Pythagorean calculations; its birth-date root reduces master numbers too.</p><p>Calculation references: <a href="https://www.numerology.com/articles/your-numerology-chart/life-path-number-meanings/" target="_blank" rel="noopener">Life Path method</a> · <a href="https://www.worldnumerology.com/do-your-own-reading/" target="_blank" rel="noopener">Pythagorean chart conventions</a> · <a href="https://www.worldnumerology.com/personal-numerology-forecast/" target="_blank" rel="noopener">Calendar-year cycles</a>. All reading text and prompts here are original.</p></details></footer>`;
    function showTab() {
      root.querySelectorAll('[data-num-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.numTab===state.tab)));
      root.querySelectorAll('.num-view').forEach(p=>p.hidden=p.id!==`num-${state.tab}`);
    }
    function coreCalculation(kind) {
      if(kind==='path') return `<ol class="num-calculation">${['Month','Day','Year'].map((label,i)=>`<li><span>${label}</span><strong>${trail(birth.components[i])}</strong></li>`).join('')}<li><span>Add the three results</span><strong>${birth.components.map(x=>x.value).join(' + ')} = ${birth.path.steps[0]}</strong></li><li><span>Life Path</span><strong>${trail(birth.path)}</strong></li></ol><p>11, 22 and 33 are retained at each stage. Your Life Path can therefore differ from the single-digit birth-date root in Lo Shu.</p>`;
      if(kind==='birthDay') return `<p>Day of birth: <strong>${birth.parts.day}</strong>. Reduced reading: <strong>${trail(birth.birthDay)}</strong>.</p><p>The original day is kept visible. This page reads its reduced theme rather than assigning separate meanings to every compound day from 10–31.</p>`;
      return `<p>Birth month ${birth.parts.month} + birth day ${birth.parts.day} = <strong>${trail(birth.attitude)}</strong>.</p><p>Attitude is reduced to a single digit, including when the intermediate sum is 11, 22 or 33.</p>`;
    }
    function renderBirth() {
      $('#num-birth').innerHTML=`<div class="num-core-cards" role="group" aria-label="Explore your birth numbers">${['path','birthDay','attitude'].map(kind=>`<button type="button" data-num-core="${kind}" aria-pressed="${state.core===kind}"><span>${roles[kind].label}</span><strong>${kind==='birthDay'?birth.parts.day:numberLabel(birth[kind])}</strong><small>${kind==='birthDay'&&birth.parts.day!==birth.birthDay.value?`Read through ${numberLabel(birth.birthDay)}`:themes[birth[kind].value].words.split(' · ').slice(-2).join(' · ')}</small></button>`).join('')}</div><div id="num-core-reading">${readNumber(birth[state.core],state.core,coreCalculation(state.core))}</div><section class="num-weave"><p class="num-kicker">Read the numbers together</p><h5>${themes[birth.path.value].title} meets ${themes[birth.attitude.value].words.split(' · ')[0].toLowerCase()}.</h5><p>Your Life Path ${numberLabel(birth.path)} offers the wider theme of <strong>${themes[birth.path.value].words.toLowerCase()}</strong>. Your Attitude ${birth.attitude.value} brings <strong>${themes[birth.attitude.value].words.toLowerCase()}</strong> into the way you approach a moment. Notice where these perspectives support one another and where they invite a different response.</p><p>${birth.path.root===birth.birthDay.root?`Life Path and Birth Day share the root ${birth.path.root}. That repeated theme can be a useful thread to revisit in both a larger question and an ordinary daily choice.`:`Your Birth Day ${birth.parts.day}, read through ${numberLabel(birth.birthDay)}, adds the perspective of ${themes[birth.birthDay.value].words.toLowerCase()}. Let it broaden the reading rather than requiring every number to describe the same part of you.`}</p><blockquote>Which theme feels familiar, which one stretches your view, and what small action could bring them into conversation?</blockquote></section>`;
    }
    function renderCycles() {
      $('#num-cycle-date').value=state.cycleDate;
      const parsed=E.parseDate(state.cycleDate);
      if(!parsed||state.cycleDate<birth.parts.value||state.cycleDate>lastDate) {
        $('#num-cycle-content').innerHTML=`<p class="num-error" role="status">Choose a valid date from ${dateLabel(birth.parts.value)} through December 31, 2100.</p>`;
        root.querySelectorAll('[data-num-day]').forEach(b=>b.disabled=true);return;
      }
      const c=E.cycles(birth,state.cycleDate),selected=c[state.period],level=['year','month','day'].indexOf(state.period),t=themes[selected.value];
      root.querySelectorAll('[data-num-day]').forEach(b=>b.disabled=b.dataset.numDay==='-1'?state.cycleDate<=birth.parts.value:state.cycleDate>=lastDate);
      const calculations={year:`${birth.parts.month} + ${birth.parts.day} + ${c.date.year} = ${trail(c.year)}`,month:`Personal Year ${c.year.value} + month ${c.date.month} = ${trail(c.month)}`,day:`Personal Month ${c.month.value} + day ${c.date.day} = ${trail(c.day)}`};
      $('#num-cycle-content').innerHTML=`<p class="num-date-caption" role="status">Exploring ${dateLabel(state.cycleDate)} · calendar-year method</p><div class="num-cycle-cards" role="group" aria-label="Explore a personal cycle">${['year','month','day'].map(kind=>`<button type="button" data-num-period="${kind}" aria-pressed="${state.period===kind}"><span>Personal ${kind}</span><strong>${c[kind].value}</strong><small>${kind==='year'?c.date.year:kind==='month'?monthNames[c.date.month-1]:`${c.date.day} ${monthNames[c.date.month-1].slice(0,3)}`}</small></button>`).join('')}</div><article class="num-cycle-reading"><p class="num-kicker">Personal ${state.period} ${selected.value}</p><h5>${t.title}</h5><p>${cycleCopy[selected.value][level]}</p><p class="num-cycle-context">${state.period==='year'?'The year offers a broad reflective theme. Your month and day numbers add shorter perspectives within it.':state.period==='month'?`This month sits within Personal Year ${c.year.value}, whose theme is ${themes[c.year.value].words.toLowerCase()}. Look for a way the two can support one practical intention.`:`This day sits within Personal Month ${c.month.value} and Personal Year ${c.year.value}. Keep its theme small enough to try in the life you are actually living today.`}</p><blockquote>${t.prompt}</blockquote><details class="num-method"><summary>See the cycle calculation</summary><ol class="num-calculation">${['year','month','day'].map(kind=>`<li><span>${kind[0].toUpperCase()+kind.slice(1)}</span><strong>${calculations[kind]}</strong></li>`).join('')}</ol><p>These cycles always reduce to 1–9. The birth year is not used. Year boundaries are January 1; this page does not use birthday-to-birthday cycles.</p></details></article><section class="num-cycle-overview"><div class="num-overview-heading"><h5>Your nine-year sequence</h5><p>Choose a year to explore its place in the cycle.</p></div><div class="num-years" role="group" aria-label="Nine-year cycle">${c.years.map(y=>`<button type="button" data-num-year="${y.year}" aria-pressed="${y.year===c.date.year}" ${y.year<birth.parts.year||y.year>2100?'disabled':''}><span>${y.year}</span><strong>${y.number}</strong><small>${['Begin','Connect','Express','Build','Explore','Care','Reflect','Organize','Complete'][y.number-1]}</small></button>`).join('')}</div></section><section class="num-cycle-overview"><div class="num-overview-heading"><h5>Twelve months of ${c.date.year}</h5><p>A smaller rhythm within Personal Year ${c.year.value}.</p></div><div class="num-months" role="group" aria-label="Personal months">${c.months.map(m=>`<button type="button" data-num-month="${m.month}" aria-pressed="${m.month===c.date.month}" ${c.date.year===birth.parts.year&&m.month<birth.parts.month?'disabled':''}><span>${monthNames[m.month-1]}</span><strong>${m.number}</strong><small>${themes[m.number].words.split(' · ')[0]}</small></button>`).join('')}</div></section>`;
    }
    function renderYChoices() {
      const n=E.normalizeName(state.name),ys=n.ys || [];
      $('#num-y-options').hidden=!ys.length;
      $('#num-y-choices').innerHTML=ys.map(y=>`<label><input type="checkbox" data-num-y="${y.index}" ${state.yVowels.includes(y.index)?'checked':''}>Y in ${esc(y.word)} · letter ${y.index+1} of the name is a vowel</label>`).join('');
    }
    function renderName() {
      if(!state.nameRead) {
        $('#num-name-results').innerHTML='<div class="num-name-invitation"><span aria-hidden="true">A · B · C <i>↓</i> 1 · 2 · 3</span><h5>A name, seen another way.</h5><p>When you are ready, enter a name to see its numbers, explore each perspective, and follow every letter through the calculation.</p></div>';return;
      }
      const n=E.nameProfile(state.name,state.yVowels,birth);
      if(n.status!=='ready') {$('#num-name-status').textContent=n.message;$('#num-name-results').innerHTML='';return;}
      $('#num-name-status').textContent=`Reading ready · calculated spelling: ${n.normalized}.`;
      const kind=state.nameKind, selected=n[kind];
      const group=kind==='soul'?n.letters.filter(x=>x.vowel):kind==='personality'?n.letters.filter(x=>!x.vowel):n.letters;
      const calculation=kind==='maturity'?`<p>Life Path ${numberLabel(birth.path)} + Expression ${numberLabel(n.expression)}: <strong>${birth.path.value} + ${n.expression.value} = ${trail(n.maturity)}</strong>.</p>`:`<p>${kind==='expression'?'All letters':kind==='soul'?'Vowels':'Consonants'}: ${group.map(x=>`${x.letter} (${x.value})`).join(' + ') || 'None'}${selected?` = <strong>${trail(selected)}</strong>`:''}.</p><p>The whole group is added before reduction. Master numbers 11, 22 and 33 are retained at the final reduction.</p>`;
      $('#num-name-results').innerHTML=`<div class="num-name-cards" role="group" aria-label="Explore your name numbers">${['expression','soul','personality','maturity'].map(key=>`<button type="button" data-num-name-kind="${key}" aria-pressed="${kind===key}"><span>${roles[key].label}</span><strong>${numberLabel(n[key])}</strong><small>${{expression:'All letters',soul:'Vowels',personality:'Consonants',maturity:'Life Path + Expression'}[key]}</small></button>`).join('')}</div><section class="num-letter-study"><div class="num-overview-heading"><h5>Every letter, accounted for.</h5><p>${kind==='maturity'?'The name’s Expression joins your Life Path in the Maturity reading.':`Highlighted letters contribute to ${roles[kind].label}.`} Exact spelling: <strong>${esc(n.normalized)}</strong></p></div><div class="num-letter-words" aria-label="Letter values">${[...new Set(n.letters.map(x=>x.wordIndex))].map(wordIndex=>`<div class="num-letter-word">${n.letters.filter(x=>x.wordIndex===wordIndex).map(x=>`<span class="num-letter${kind==='soul'&&!x.vowel||kind==='personality'&&x.vowel?' is-muted':''}" aria-label="${x.letter}: ${x.value}, ${x.vowel?'vowel':'consonant'}"><b>${x.letter}</b><small>${x.value}</small></span>`).join('')}</div>`).join('')}</div><p class="num-letter-totals">All letters ${n.totals.expression} = vowels ${n.totals.soul} + consonants ${n.totals.personality}</p></section>${readNumber(selected,kind,calculation)}<section class="num-weave"><p class="num-kicker">Name & birth date together</p><h5>Intention into expression.</h5><p>Life Path ${numberLabel(birth.path)} invites you to revisit <strong>${themes[birth.path.value].words.toLowerCase()}</strong>. Expression ${numberLabel(n.expression)} brings <strong>${themes[n.expression.value].words.toLowerCase()}</strong> into the way you contribute. Consider one situation in which you could make room for both perspectives.</p>${n.soul&&n.personality?`<p>Soul Urge ${numberLabel(n.soul)} asks what feels meaningful inwardly; Personality ${numberLabel(n.personality)} explores outward expression. ${n.soul.root===n.personality.root?'They share a root here. Use that repeated theme to ask where your choices feel congruent with what matters to you.':'Their different themes can open a useful question: what would help your outward choices express more of what matters to you inwardly?'}</p>`:''}<blockquote>What feels true to your experience, and what would you put into your own words?</blockquote></section>`;
    }
    root.addEventListener('click', event=>{
      const button=event.target.closest('button');if(!button)return;const d=button.dataset;
      if(d.numTab){state.tab=d.numTab;showTab();return;}
      if(d.numCore){state.core=d.numCore;renderBirth();$(`[data-num-core="${state.core}"]`).focus({preventScroll:true});return;}
      if(d.numNameKind){state.nameKind=d.numNameKind;renderName();$(`[data-num-name-kind="${state.nameKind}"]`).focus({preventScroll:true});return;}
      if(d.numPeriod){state.period=d.numPeriod;renderCycles();$(`[data-num-period="${state.period}"]`).focus({preventScroll:true});return;}
      let focus='';
      if('numToday' in d){state.cycleDate=localToday();state.period='day';focus='[data-num-today]';}
      if(d.numDay){const date=new Date(`${state.cycleDate}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+Number(d.numDay));state.cycleDate=date.toISOString().slice(0,10);focus=`[data-num-day="${d.numDay}"]`;}
      if(d.numYear){const p=E.parseDate(state.cycleDate);state.cycleDate=E.dateInMonth(state.cycleDate,Number(d.numYear),p.month,birth.parts.value,lastDate);state.period='year';focus=`[data-num-year="${d.numYear}"]`;}
      if(d.numMonth){const p=E.parseDate(state.cycleDate);state.cycleDate=E.dateInMonth(state.cycleDate,p.year,Number(d.numMonth),birth.parts.value,lastDate);state.period='month';focus=`[data-num-month="${d.numMonth}"]`;}
      if(focus){renderCycles();$(focus)?.focus({preventScroll:true});}
    },{signal:controller.signal});
    root.addEventListener('change',event=>{
      if(event.target.id==='num-cycle-date'){state.cycleDate=event.target.value;renderCycles();}
      if(event.target.matches('[data-num-y]')) {state.yVowels=[...root.querySelectorAll('[data-num-y]:checked')].map(x=>Number(x.dataset.numY));if(state.nameRead)renderName();}
    },{signal:controller.signal});
    $('#num-full-name').addEventListener('input',event=>{state.name=event.target.value;state.nameRead=false;state.yVowels=[];renderYChoices();$('#num-name-status').textContent=state.name?'Choose Read this name when you are ready.':'';renderName();},{signal:controller.signal});
    $('#num-name-form').addEventListener('submit',event=>{event.preventDefault();state.name=$('#num-full-name').value;state.nameRead=true;renderName();},{signal:controller.signal});
    renderBirth();renderCycles();renderYChoices();renderName();showTab();
    return {getState:()=>({...state,yVowels:[...state.yVowels]}),destroy:()=>controller.abort()};
  }
  return {attach};
})();
