/* Original reflections and local-only interactions for the numerology studio. */
const Numerology = (() => {
  'use strict';
  const E = NumerologyEngine;
  const esc = value => String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const themes = {
    1:{title:'The courage to begin',words:'Initiative · independence · direction',story:'One offers a lens on the moment you stop waiting for a ready-made path. Its symbolism centers on agency: deciding what matters, taking the first step, and allowing experience to refine the plan.',capacity:'A clear intention can give scattered effort a direction. Let independence include the freedom to choose your own pace.',edge:'Notice when self-reliance becomes a refusal to receive help, or when starting something new keeps you from finishing what matters.',connection:'Make your preference clear while leaving room for another person’s equally real needs.',work:'Choose a modest experiment that puts an idea into motion. Give it an end point at which you will review what you learned.',practice:'Begin one thing you have been waiting to feel fully ready for. Keep the first step small.',prompt:'Where can I act with more agency and less need to prove myself?'},
    2:{title:'The art of meeting',words:'Cooperation · sensitivity · reciprocity',story:'Two brings attention to the space between people, ideas, and needs. Its symbolism asks what becomes possible when listening is active and an agreement leaves room for both sides.',capacity:'Patience and careful listening can reveal a possibility that speed would miss. Notice the value of an honest exchange.',edge:'Keeping the peace can become a way of disappearing from the conversation. Agreement is more useful when your own preference is present.',connection:'Ask what mutual care looks like in actions, rather than assuming you both mean the same thing by it.',work:'Invite a second perspective before settling the plan. Clarify who will do what and how you will check in.',practice:'Make one clear request, and offer another person space to answer honestly.',prompt:'What would cooperation look like if my needs were included?'},
    3:{title:'A voice of your own',words:'Expression · imagination · connection',story:'Three opens a conversation about expression: giving a feeling, observation, or idea a form that can be shared. Its symbolism makes space for play, experimentation, and the pleasure of finding the right words.',capacity:'Imagination can connect things that first seemed unrelated. Give an unfinished idea a kind audience and a little room to develop.',edge:'Expression can scatter into performance or too many beginnings. Choose what you want to say before deciding how it should be received.',connection:'Let humor and warmth make room for honesty, including the feeling that is harder to express.',work:'Bring one idea out of your head and into a draft, sketch, demonstration, or conversation.',practice:'Make something for twenty minutes without editing it as you go.',prompt:'What wants expression before it needs approval?'},
    4:{title:'A foundation worth tending',words:'Structure · craft · steadiness',story:'Four asks how a meaningful intention becomes part of everyday life. Its symbolism lives in the useful framework: a practice, boundary, or dependable arrangement that makes room for something to grow.',capacity:'Steady attention can turn a vague wish into a workable commitment. Let the structure support a life you actually want to live.',edge:'A helpful rule can outlast its purpose. Check whether consistency is offering support or demanding that nothing ever change.',connection:'Build trust through a promise you can keep, and renegotiate early when the conditions change.',work:'Break the work into repeatable steps. Improve one part of the method instead of rebuilding everything at once.',practice:'Repair or simplify one routine that affects the rest of your day.',prompt:'Which structure supports me, and which one needs to become more flexible?'},
    5:{title:'Room for discovery',words:'Change · curiosity · adaptability',story:'Five turns toward experience, movement, and a willingness to revise the familiar. Its symbolism invites a conscious experiment: discovering what freedom means when it is paired with attention to consequences.',capacity:'A fresh perspective can loosen a stale problem. Let curiosity broaden your options before deciding what needs to change.',edge:'Constant novelty can become a way of avoiding discomfort or a commitment. Distinguish a nourishing change from an escape that repeats the same pattern.',connection:'Talk about the balance between freedom and reliability rather than expecting the other person to guess it.',work:'Try a different route or method, then compare the result with what you already know.',practice:'Change one small part of your usual approach and observe what it teaches you.',prompt:'What kind of freedom would make my life fuller, rather than simply busier?'},
    6:{title:'Care with a center',words:'Responsibility · belonging · harmony',story:'Six considers how care becomes sustainable. Its symbolism points toward home, relationships, and the quality of what you tend, while asking that your own needs remain inside the circle of responsibility.',capacity:'Attention to ordinary needs can make a place or relationship feel more welcoming. Let care be specific enough to receive.',edge:'Taking responsibility for everyone’s comfort can leave little room for their agency or your rest. A caring boundary can strengthen the relationship.',connection:'Ask what support is wanted before offering a solution. Make room to receive care as well as give it.',work:'Improve the conditions in which people do their work. Share a practical responsibility instead of quietly absorbing it.',practice:'Choose one act of care for yourself and one you can offer without resentment.',prompt:'How can I care deeply without carrying what belongs to someone else?'},
    7:{title:'The question beneath',words:'Inquiry · reflection · understanding',story:'Seven offers a lens on attention, solitude, and the search for understanding. Its symbolism favors a thoughtful pause: examining an assumption, following a worthwhile question, and letting evidence change your view.',capacity:'Depth can come from spending longer with one question. Quiet attention may reveal a distinction that constant input has blurred.',edge:'Reflection can turn into distance or endless preparation. Notice when the next insight needs an experience rather than another explanation.',connection:'Share enough of your inner process for someone to meet you there. Privacy does not have to mean disconnection.',work:'Set aside a period for focused study, then translate what you learn into a useful test or clear explanation.',practice:'Spend a little undistracted time with a question, then write one thing you can investigate.',prompt:'What do I understand more clearly when I slow down and look again?'},
    8:{title:'Purposeful stewardship',words:'Agency · organization · responsibility',story:'Eight examines how intention meets resources, decisions, and shared consequences. Its symbolism is an invitation to use influence responsibly and define success in terms that remain meaningful after the visible result.',capacity:'Clear priorities can bring people, time, and effort into a workable arrangement. Notice the value of accountable leadership.',edge:'An external measure of success can crowd out the life it was meant to serve. Consider the human cost of a goal and the fairness of the process.',connection:'Make expectations and the balance of responsibility explicit. Leave room for a voice that carries less formal authority.',work:'Choose a useful outcome, identify the resources it needs, and decide how progress will be judged fairly.',practice:'Review one commitment against your actual capacity, then make a clear adjustment.',prompt:'What would success look like if responsibility and enough were part of its definition?'},
    9:{title:'What you carry forward',words:'Completion · compassion · perspective',story:'Nine gathers a cycle into a wider view. Its symbolism makes room for completion, letting go, and an awareness of the people and experiences that have shaped the work. An ending can be honored without being prolonged.',capacity:'Perspective can help separate an enduring value from the form it once took. Keep the learning while allowing the next chapter to differ.',edge:'A wish to help everyone can become diffuse, or an attachment to a meaningful past can delay a necessary ending. Make care concrete and release deliberate.',connection:'Acknowledge what a relationship has taught you while staying attentive to what it needs in the present.',work:'Finish, document, or pass on a piece of work. Give a useful contribution a form that others can carry forward.',practice:'Complete one loose end and name one lesson you want to take with you.',prompt:'What is ready to be completed, and what wisdom should continue?'},
    11:{title:'Insight given a voice',words:'Master 11 · perception · connection',story:'Eleven is retained as a master number in this method, alongside its root of two. Read it as a symbolic conversation between a vivid idea or impression and the patient work of making it understandable to someone else.',capacity:'A subtle observation can become useful when it is expressed clearly and checked against experience. Give an insight a grounded form.',edge:'The master-number label is not a demand to be exceptional. Let an impression remain a question until observation or conversation supports it.',connection:'Pair sensitivity with a direct question. Another person’s experience is best learned by asking.',work:'Translate a larger idea into an example, image, or prototype that someone else can respond to.',practice:'Write down an insight, then name one ordinary way to explore whether it is useful.',prompt:'How could I give an important impression a clear and grounded expression?'},
    22:{title:'A vision made workable',words:'Master 22 · vision · practical craft',story:'Twenty-two is retained as a master number in this method, alongside its root of four. Its symbolism joins a broad vision with the small, dependable structures that allow people to build something together.',capacity:'A worthwhile ambition can become approachable when it has a clear first phase. Let the plan grow from what the work teaches you.',edge:'A large ideal can make ordinary progress feel inadequate. There is no requirement to build something monumental for your effort to matter.',connection:'Share ownership of the vision. Ask the people involved what they need for the arrangement to remain workable.',work:'Define one useful milestone, the support it requires, and what you can simplify before beginning.',practice:'Bring a big idea down to one realistic promise you can keep this week.',prompt:'What small structure would let a larger possibility begin to take shape?'},
    33:{title:'Care that teaches',words:'Master 33 · compassion · contribution',story:'Thirty-three is retained as a master number in this method, alongside its root of six. Its symbolism brings care, expression, and service into conversation: offering what you have learned without making yourself responsible for every outcome.',capacity:'An experience shared with patience can make someone else’s path feel less lonely. Let generosity include respect for their choices.',edge:'Service becomes strained when it requires self-erasure or a perfect example. You can contribute while remaining a person with limits and unfinished learning.',connection:'Offer support that leaves the other person room to choose. Include your own need for rest and reciprocity.',work:'Make useful knowledge easier to understand or access. Ask what will help before deciding what to provide.',practice:'Share one useful thing you have learned, and leave yourself space to receive something in return.',prompt:'What can I offer generously without making it a measure of my worth?'}
  };
  const cycleCopy = {
    1:['Choose a beginning worth protecting. Let this year’s reflection center on the direction you want to establish, with enough room to learn as you go.','Give one fresh idea a practical first step this month. A beginning can be small and still change your relationship with the work.','Begin one manageable thing today. Decide what the first step is before asking yourself for confidence.'],
    2:['Consider the relationships, agreements, and patient tending that help an intention develop. Use this year’s theme to notice where cooperation needs a clearer conversation.','Make room for listening and adjustment this month. A useful agreement may matter more than a fast answer.','Give one exchange your full attention. Ask a clear question and leave room for the reply.'],
    3:['Explore how you want to express yourself and what you want to make visible. Give creativity a regular place rather than waiting for inspiration to carry the whole effort.','Choose something to share or make this month. Let enjoyment help the work develop without requiring every experiment to become a result.','Give a thought or feeling a simple form: a note, a sketch, or an honest conversation.'],
    4:['Look at the foundations that support your commitments. This is a useful year-theme for reviewing routines, improving a method, and choosing a pace you can sustain.','Bring order to one part of your life this month. Let the structure reduce effort rather than become another standard to meet.','Complete one practical step. A small repair or clear plan can make the next task easier.'],
    5:['Consider what a thoughtful change could teach you. Make space to explore, while distinguishing the freedom you want from movement for its own sake.','Try a fresh approach this month and notice its effects. Keep enough steadiness around the experiment to learn from it.','Change one small part of your usual routine. Stay curious about what feels more alive or more useful.'],
    6:['Reflect on care, belonging, and the responsibilities you want to keep. Let the year’s theme include fair sharing and the conditions that allow affection to last.','Tend a relationship, a shared space, or a commitment this month. Include a boundary that keeps the care sustainable.','Offer one specific act of care, including one for yourself. Ask before assuming what someone else needs.'],
    7:['Give a worthwhile question time to deepen. Use the year’s theme to review what you believe, make room for study, and turn reflection into a grounded understanding.','Protect a little time for focused inquiry this month. Look for the question underneath the obvious task.','Step back from extra input long enough to hear your own question. Write down what still needs evidence.'],
    8:['Review how you use your time, resources, and influence. Let this year’s reflection connect the results you seek with a fair process and a clear sense of enough.','Choose an outcome you can work toward responsibly this month. Clarify the scope, the resources, and the commitments involved.','Make one decision that respects your actual capacity. Let a clear priority organize the next step.'],
    9:['Consider what is ready for completion and what deserves to continue in another form. Honor a chapter by gathering its learning rather than requiring it to last forever.','Finish or release one lingering task this month. Give what you have learned a useful place in the next chapter.','Close one small loop. Acknowledge what it taught you before moving on.']
  };
  const roles = {
    path:{label:'Life Path',lens:'A broad theme to revisit across different chapters of life. Treat it as a question you can grow with, rather than a fixed description of who you must be.'},
    birthDay:{label:'Birth Day',lens:'A close-up on the day you were born. This reading keeps the full day visible and explores its reduced number as an everyday way of contributing; other traditions also interpret the compound day.'},
    attitude:{label:'Attitude',lens:'Also called a Sun number in some numerology systems. It combines your birth month and day as a lens on the way you begin, approach a situation, or respond to a new experience.'},
    expression:{label:'Expression',lens:'All the letters of the entered name contribute here. Use this as a lens on how you give your abilities and interests a form in the world.'},
    soul:{label:'Soul Urge',lens:'The vowels of the entered name contribute here; this is also called Heart’s Desire. Use it to explore what feels nourishing or meaningful from the inside.'},
    personality:{label:'Personality',lens:'The consonants of the entered name contribute here. This is a symbolic lens on outward expression, not a way to know what another person actually thinks of you.'},
    maturity:{label:'Maturity',lens:'Life Path and Expression are added together for a longer-view reflection on how experience and contribution might develop together. This does not assign an age or predict a future event.'}
  };
  // One sentence per number: how the theme reads as a chapter of life rather than a trait. Original copy.
  const arcLens = {
    1:'As a chapter, this number asks you to find your own footing and make decisions you can stand behind.',
    2:'As a chapter, this number turns attention to partnership, patience and the quality of your agreements.',
    3:'As a chapter, this number makes room for expression, friendship and work that wants to be seen.',
    4:'As a chapter, this number favors building: routines, skills and commitments that hold weight.',
    5:'As a chapter, this number brings movement, change and the question of what freedom is for.',
    6:'As a chapter, this number gathers responsibility, home and the people who depend on one another.',
    7:'As a chapter, this number slows the pace toward study, privacy and understanding.',
    8:'As a chapter, this number tests how you handle resources, authority and visible results.',
    9:'As a chapter, this number asks what you are ready to complete and what you will pass on.',
    11:'As a chapter, this master number heightens perception and asks that insight find a practical voice.',
    22:'As a chapter, this master number pairs a large vision with the patience to build it in stages.',
    33:'As a chapter, this master number centers on care that teaches, and on keeping that care sustainable.'
  };
  // Challenges 0–8. Original copy. A challenge is a recurring question, not a flaw.
  const challengeCopy = {
    0:{title:'The open question',words:'Choice · self-direction · everything possible',story:'A zero challenge has no single theme. Traditionally it is read as the freedom, and the difficulty, of choosing your own emphasis when nothing in particular is pushing back. The question in this period is which challenge you decide to take on deliberately.',prompt:'Which of the other challenges would I choose to work on, if nothing chose for me?'},
    1:{title:'Standing on your own',words:'Independence · confidence · will',story:'This challenge circles the question of self-reliance: learning to trust your own judgment without needing to win every argument, and to lead without pushing people away.',prompt:'Where am I waiting for permission that I could give myself?'},
    2:{title:'Sensitivity with a spine',words:'Feeling · cooperation · boundaries',story:'This challenge concerns the balance between sensitivity and self-erasure. It asks you to stay open to others without taking every mood personally, and to cooperate without disappearing from the agreement.',prompt:'When I keep the peace, whose peace is it?'},
    3:{title:'Saying it plainly',words:'Expression · focus · follow-through',story:'This challenge gathers around expression: scattered energy, unfinished projects, or words held back for fear of how they will land. The invitation is to choose what you want to say and give it a finished form.',prompt:'What have I been talking around instead of saying?'},
    4:{title:'Structure that serves',words:'Work · order · flexibility',story:'This challenge asks how you relate to routine and effort. Too little structure leaves intentions unbuilt; too much turns a method into a cage. The work is to find the amount of order that actually helps.',prompt:'Which rule am I keeping past its usefulness?'},
    5:{title:'Freedom with a keel',words:'Change · restraint · curiosity',story:'This challenge concerns freedom: restlessness, excess, or the opposite fear of any change at all. It invites a curiosity that can stay long enough to learn something.',prompt:'What am I moving away from, and would staying teach me more?'},
    6:{title:'Care without control',words:'Responsibility · idealism · acceptance',story:'This challenge gathers around responsibility and expectation: caring so much about how things should be that people, including you, are not allowed to be as they are.',prompt:'Whose responsibility have I quietly taken over?'},
    7:{title:'Trusting what you find',words:'Faith · inquiry · openness',story:'This challenge concerns doubt and distance: analyzing rather than experiencing, or keeping so much private that no one can meet you there. It asks for inquiry that leads back into life.',prompt:'What would I have to feel if I stopped explaining it?'},
    8:{title:'Enough, and what it is for',words:'Resources · ambition · fairness',story:'This challenge concerns money, power and the measure of success. It can show as over-focus on results or as an avoidance of them. The question is what you would do with enough.',prompt:'What result am I chasing, and what would I do the day after I had it?'}
  };
  // How each Life Path tends to enter a relationship of any kind. Original copy; no verdicts.
  const relating = {
    1:{title:'Leads with initiative',story:'One tends to enter a relationship by acting: suggesting the plan, making the first call, taking a stand. The gift is momentum; the question is whether the other person is being invited or simply carried along.',prompt:'When did I last let someone else set the direction, and how did it feel?'},
    2:{title:'Leads with attention',story:'Two tends to enter a relationship by noticing: the mood, the unspoken need, the small adjustment that keeps things easy. The gift is attunement; the question is whether your own preferences are still visible in the exchange.',prompt:'What do I want here that I have not yet said out loud?'},
    3:{title:'Leads with expression',story:'Three tends to enter a relationship through conversation, humor and shared enthusiasm. The gift is warmth that makes people feel welcome; the question is whether the harder feelings get the same airtime as the pleasant ones.',prompt:'What would I say to this person if I trusted them to hear it?'},
    4:{title:'Leads with reliability',story:'Four tends to enter a relationship by showing up: consistently, practically, on time. The gift is trust built from kept promises; the question is whether steadiness leaves room for the other person to change.',prompt:'Which of my routines is this relationship allowed to interrupt?'},
    5:{title:'Leads with curiosity',story:'Five tends to enter a relationship as an adventure: new places, new ideas, a dislike of anything that feels like a script. The gift is aliveness; the question is what happens when the other person needs something predictable.',prompt:'What kind of steadiness would I be willing to offer, and for how long?'},
    6:{title:'Leads with care',story:'Six tends to enter a relationship by taking care of it: the home, the meal, the difficult relative, the plan for everyone. The gift is devotion; the question is whether care is being offered or quietly required.',prompt:'What would this person say they actually need from me?'},
    7:{title:'Leads with depth',story:'Seven tends to enter a relationship slowly, from the inside out, preferring one real conversation to many easy ones. The gift is being fully met; the question is whether privacy is protecting you or keeping the other person out.',prompt:'What have I understood about this person that I have never told them?'},
    8:{title:'Leads with commitment',story:'Eight tends to enter a relationship as a shared enterprise: goals, responsibilities, a sense of building something. The gift is loyalty and follow-through; the question is who holds the authority when you disagree.',prompt:'Where in this relationship do I need to be right, and what would it cost to let that go?'},
    9:{title:'Leads with perspective',story:'Nine tends to enter a relationship with a wide lens: generous, forgiving, interested in the whole person and the wider world. The gift is acceptance; the question is whether the particular, daily person gets as much attention as the ideal.',prompt:'What small, ordinary thing about this person deserves my full attention this week?'},
    11:{title:'Leads with perception',story:'Eleven, read with its root of two, tends to enter a relationship by sensing what is unspoken and wanting to name it. The gift is insight offered with care; the question is whether the intensity of noticing leaves the other person room to be ordinary.',prompt:'What am I sensing that I could simply ask about instead?'},
    22:{title:'Leads with a shared project',story:'Twenty-two, read with its root of four, tends to enter a relationship with a vision of what the two of you could build. The gift is scale and patience; the question is whether the person matters as much as the plan.',prompt:'If we never built anything together, what would still be worth keeping?'},
    33:{title:'Leads with devotion',story:'Thirty-three, read with its root of six, tends to enter a relationship as a calling to care and to teach. The gift is generosity; the question is whether the giving leaves room to receive.',prompt:'When did I last let this person take care of me?'}
  };
  const concordCopy = {
    mind:'the mind concord (1, 5, 7): numbers traditionally grouped around thinking, independence and inquiry',
    practical:'the practical concord (2, 4, 8): numbers traditionally grouped around cooperation, structure and stewardship',
    expressive:'the expressive concord (3, 6, 9): numbers traditionally grouped around expression, care and perspective'
  };
  // Chaldean compound readings 10–52. Original copy; no fortune-telling, no outcome claims.
  const compoundCopy = {
    10:{title:'The turning wheel',words:'Rotation · confidence · consequence',story:'Ten is traditionally pictured as a wheel: what is set in motion comes round. As a name number it invites a look at how your intentions return to you in the responses of others, and at what you would want to keep turning.',prompt:'What have I set in motion that is now coming back around?'},
    11:{title:'The taut wire',words:'Instinct · tension · timing',story:'Eleven is traditionally read for a heightened sensitivity to atmosphere: what has not yet been said out loud. As a name number it can be read as attentiveness to shifting undercurrents, and the discipline of choosing when to act on a hunch.',prompt:'What have I sensed that deserves a closer look before I decide?'},
    12:{title:'The offering made',words:'Patience · surrender · service',story:'Twelve is traditionally pictured as a willing wait, giving something up so a larger pattern can complete itself. Read as a name number, it asks what you hold loosely and what a period of patience might be preparing you for.',prompt:'What am I willing to set down so something else can finish forming?'},
    13:{title:'The turned page',words:'Change · release · renewal',story:'Thirteen is traditionally associated with sudden transformation rather than steady progress. As a name number it can be read as an invitation to let an old form end cleanly, so whatever comes next has room to take its own shape.',prompt:'What chapter am I still holding onto past its natural close?'},
    14:{title:'The crossing current',words:'Movement · risk · adaptability',story:'Fourteen is traditionally linked to sudden movement and changing conditions. Read as a name number, it favors a flexible plan over a rigid one, and a habit of checking your footing before committing to the next step.',prompt:'Where would a looser plan actually serve me better than a fixed one?'},
    15:{title:'The magnetic circle',words:'Charisma · gathering · responsibility',story:'Fifteen is traditionally read as a pull toward you: people, attention, opportunity. As a name number it asks what you do with that gathering, and whether the circle you draw people into is one you would want to stand inside yourself.',prompt:'What am I asking people to gather around, and does it hold up?'},
    16:{title:'What the storm clears',words:'Disruption · rebuilding · humility',story:'Sixteen is traditionally pictured as a structure coming down unexpectedly. As a name number it can be read as a lesson in rebuilding on steadier ground, and in letting an old certainty go before the new one is fully formed.',prompt:'What certainty am I still building on that has already shifted?'},
    17:{title:'A star to steer by',words:'Guidance · hope · quiet direction',story:'Seventeen is traditionally pictured as a single star, visible but distant. Read as a name number, it favors a steady inward compass over a loud external one, and the discipline of returning to it after a distracting stretch.',prompt:'What quiet direction have I been drowning out with noise?'},
    18:{title:'Between two rooms',words:'Tension · discernment · integration',story:'Eighteen is traditionally read as a pull between competing demands: the practical and the inward, the outer world and an unfinished inner conversation. As a name number it asks for an honest look at which room you keep avoiding.',prompt:'Which of my two rooms have I been neglecting lately?'},
    19:{title:'A clear morning',words:'Visibility · warmth · promise',story:'Nineteen is traditionally associated with the sun rising: a name that tends to be seen and to see. Read it as a question about what you want to bring into the light and what deserves to stay quietly your own.',prompt:'What would I do differently if I assumed I was already being noticed?'},
    20:{title:'The waking hour',words:'Awareness · threshold · readiness',story:'Twenty is traditionally read as an awakening: a moment when something that was dim becomes clear enough to act on. As a name number it favors attentiveness at the edge of a decision, rather than waiting for total certainty.',prompt:'What have I already noticed that I am waiting for permission to act on?'},
    21:{title:'The gathered crown',words:'Achievement · patience · recognition',story:'Twenty-one is traditionally pictured as a reward that arrives after sustained effort rather than a sudden win. Read as a name number, it invites a look at what you have been building quietly and whether it is ready to be shown.',prompt:'What steady effort of mine is ready to be seen?'},
    22:{title:'The wide scaffold',words:'Ambition · structure · scale',story:'Twenty-two is traditionally read as a large vision that needs an equally patient method. As a name number it can be read as a caution against skipping the scaffolding on the way to something meant to last.',prompt:'What foundation still needs attention before I build any higher?'},
    23:{title:'The royal star',words:'Support · leadership · timing',story:'Twenty-three is traditionally called the royal star of the lion, a number of help arriving at the right moment. Read as a name number, it favors a readiness to lead when called on, and a willingness to accept support without losing your own direction.',prompt:'What help would I accept right now if I let myself ask for it?'},
    24:{title:'The shared harvest',words:'Cooperation · exchange · care',story:'Twenty-four is traditionally read as gain that comes through partnership rather than solitary effort. As a name number it asks what you contribute to a shared undertaking, and whether the exchange feels balanced from both sides.',prompt:'What am I contributing to this partnership, and what am I receiving?'},
    25:{title:'The tested method',words:'Analysis · refinement · patience',story:'Twenty-five is traditionally read as understanding earned through trial rather than instinct alone. Read as a name number, it favors a willingness to test an approach, notice what fails, and adjust before repeating it.',prompt:'What method of mine deserves one more honest test before I trust it?'},
    26:{title:'The uneven partnership',words:'Discernment · balance · caution',story:'Twenty-six is traditionally read as a caution about relying too heavily on someone else’s judgment or resources. As a name number it invites a closer look at whether an alliance is genuinely mutual or quietly one-sided.',prompt:'Which partnership of mine would benefit from a more honest accounting?'},
    27:{title:'The raised staff',words:'Authority · responsibility · command',story:'Twenty-seven is traditionally pictured as a staff of office: influence that comes with an obligation to use it well. Read as a name number, it asks how you carry authority when you have it, and how clearly you delegate what is not yours alone.',prompt:'How am I using the authority I already have?'},
    28:{title:'The solitary rebuild',words:'Independence · setback · resilience',story:'Twenty-eight is traditionally read as a pattern of gain interrupted, then rebuilt through one’s own effort. As a name number it favors self-reliance without bitterness, and the discipline of starting again with what you have learned.',prompt:'What would rebuilding look like if I stopped waiting for outside help?'},
    29:{title:'The clouded mirror',words:'Discernment · uncertainty · patience',story:'Twenty-nine is traditionally read as a period when clarity is hard to reach and appearances can mislead. Read as a name number, it favors slowing down long enough for a clearer reflection to form before you commit to a reading of events.',prompt:'What am I assuming clearly when the evidence is still cloudy?'},
    30:{title:'The long think',words:'Reflection · depth · imagination',story:'Thirty is traditionally read as a mind drawn toward ideas rather than immediate action. As a name number it favors long, unhurried thought and a willingness to let a good idea mature before it is tested against the world.',prompt:'What idea of mine is ready to be tested, rather than thought about again?'},
    31:{title:'The quiet room',words:'Solitude · focus · self-sufficiency',story:'Thirty-one is traditionally read as a capacity to work well alone, drawing on inner resources rather than a crowd. Read as a name number, it asks whether your solitude is restorative or has quietly become isolation.',prompt:'Is my time alone still feeding me, or has it become a habit of avoidance?'},
    32:{title:'The kept promise',words:'Loyalty · cooperation · steadiness',story:'Thirty-two is traditionally read as strength that comes from reliable connection rather than individual force. As a name number it favors keeping a commitment even after the initial enthusiasm fades, and choosing allies with care.',prompt:'Which commitment of mine needs my attention now that the excitement has faded?'},
    33:{title:'The teaching hand',words:'Guidance · patience · generosity',story:'Thirty-three is traditionally read as care that takes the shape of teaching: sharing what you know so someone else can carry it further. Read as a name number, it asks whether your guidance leaves room for another person’s own way of learning.',prompt:'Where am I teaching, and where am I quietly insisting on being followed?'},
    34:{title:'The measured risk',words:'Judgment · timing · calculation',story:'Thirty-four is traditionally read as a readiness to act once the odds have been carefully weighed. As a name number it favors patience with the weighing itself, and a clear sense of what you are actually risking.',prompt:'What decision am I ready to make once I stop second-guessing the math?'},
    35:{title:'The working hands',words:'Craft · practicality · results',story:'Thirty-five is traditionally read as skill applied steadily until it produces something tangible. Read as a name number, it favors practice over theory, and a preference for a finished piece of work over an elegant plan that stays on paper.',prompt:'What half-finished piece of work would benefit from an hour of plain effort?'},
    36:{title:'The bound circle',words:'Unity · closeness · shared purpose',story:'Thirty-six is traditionally read as people drawn together by a common aim rather than convenience. As a name number it asks what actually holds your closest circle together, and whether that purpose still fits the people in it.',prompt:'What still holds my closest circle together, and does it still fit?'},
    37:{title:'The signed agreement',words:'Trust · cooperation · formality',story:'Thirty-seven is traditionally read as an alliance made steady by clear terms rather than good feeling alone. Read as a name number, it favors putting an understanding into plain words before it is tested by circumstance.',prompt:'What agreement of mine would hold up better if it were made explicit?'},
    38:{title:'The second wind',words:'Recovery · persistence · renewal',story:'Thirty-eight is traditionally read as strength that returns after a difficult stretch, provided the earlier effort was not wasted. As a name number it favors patience with a slow recovery, and trusting that endurance compounds quietly.',prompt:'What earlier effort of mine is about to pay off if I keep going a little longer?'},
    39:{title:'The gentle release',words:'Ease · letting go · lightness',story:'Thirty-nine is traditionally read as relief that comes from setting an unnecessary burden down. Read as a name number, it asks what you have been carrying out of habit rather than necessity, and what lightness might follow if you put it down.',prompt:'What am I still carrying out of habit rather than need?'},
    40:{title:'The shifting ground',words:'Instability · testing · adaptation',story:'Forty is traditionally read as a foundation still settling, where plans need frequent revision. As a name number it favors holding a plan loosely and treating each adjustment as information rather than as a failure of the original idea.',prompt:'What plan of mine needs revising rather than abandoning?'},
    41:{title:'The blank page',words:'Originality · invention · beginning',story:'Forty-one is traditionally read as a readiness to start from a fresh idea rather than an inherited one. Read as a name number, it favors trusting an unconventional approach and giving it a genuine trial before comparing it to the familiar way.',prompt:'What unconventional idea of mine deserves an actual trial?'},
    42:{title:'The tended garden',words:'Nurture · community · patience',story:'Forty-two is traditionally read as growth that depends on steady, unglamorous tending rather than a single dramatic effort. As a name number it favors small, repeated acts of care toward the people and projects you want to see flourish.',prompt:'What have I been tending well, and what have I left unwatered?'},
    43:{title:'The sudden shift',words:'Upheaval · adjustment · resolve',story:'Forty-three is traditionally read as disruption that arrives faster than expected, testing how quickly you can adjust. Read as a name number, it favors keeping a clear head when circumstances change, rather than waiting for stability to return first.',prompt:'What sudden change am I still resisting instead of adjusting to?'},
    44:{title:'The careful ledger',words:'Discernment · value · accountability',story:'Forty-four is traditionally read as a close accounting of what something actually costs and what it returns. As a name number it favors an honest tally of effort against result, in relationships as much as in any practical undertaking.',prompt:'Where would an honest accounting change what I decide to keep doing?'},
    45:{title:'The many paths',words:'Versatility · adaptability · range',story:'Forty-five is traditionally read as an ability to work well in more than one role or setting. Read as a name number, it favors noticing which of your several capacities the present moment actually calls for, rather than using all of them at once.',prompt:'Which of my several capacities does this particular moment actually need?'},
    46:{title:'The rebuilt bridge',words:'Repair · reconnection · effort',story:'Forty-six is traditionally read as a connection restored through deliberate work rather than time alone. As a name number it asks what repair you have been postponing, and what a first small gesture toward it might look like.',prompt:'What connection of mine needs a first small gesture, not a grand one?'},
    47:{title:'The steady current',words:'Persistence · endurance · momentum',story:'Forty-seven is traditionally read as progress that comes from continuing rather than from any single leap forward. Read as a name number, it favors trusting a slow, steady pace even when the results are not yet visible.',prompt:'What steady effort of mine is working, even though I cannot see it yet?'},
    48:{title:'The wide net',words:'Organization · scale · reach',story:'Forty-eight is traditionally read as an ability to coordinate many moving parts at once. As a name number it favors clear structure over sheer effort, and a willingness to delegate what does not need your direct hand.',prompt:'What could I hand to someone else without the outcome actually suffering?'},
    49:{title:'The rising structure',words:'Vision · method · commitment',story:'Forty-nine is traditionally read as a large aim matched, finally, to a workable method. Read as a name number, it favors converting an ambition into a sequence of ordinary steps that someone could actually follow.',prompt:'What ambition of mine is ready to become a sequence of ordinary steps?'},
    50:{title:'The wisdom gained',words:'Insight · change · perspective',story:'Fifty is traditionally read as understanding distilled from a life of varied experience rather than a single lesson. As a name number it favors looking back at what has actually changed your mind, and trusting that record over untested certainty.',prompt:'What has actually changed my mind, and why did it work?'},
    51:{title:'The clear command',words:'Leadership · clarity · decisiveness',story:'Fifty-one is traditionally read as leadership that comes from a clear head rather than volume or force. Read as a name number, it favors making one decisive call once the essential facts are in, rather than gathering endless further opinions.',prompt:'What decision have I gathered enough information to make right now?'},
    52:{title:'The long practice',words:'Persistence · experiment · renewal',story:'Fifty-two closes the compound series. As a name number it can be read as the patient repetition that turns an experiment into a practice: the same thing done again with more attention each time.',prompt:'Which practice would improve if I repeated it once more with care?'}
  };
  const localToday = () => {const d=new Date();return E.dateKey(d.getFullYear(),d.getMonth()+1,d.getDate());};
  const numberLabel = result => result ? result.master?`${result.value}/${result.root}`:String(result.value) : '—';
  const trail = result => result.steps.join(' → ');
  const dateLabel = value => new Intl.DateTimeFormat(undefined,{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
  const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  function readNumber(result, role, calculation) {
    if(!result) return `<article class="num-reading num-empty"><h5>${roles[role].label} is not calculated</h5><p>No ${role==='soul'?'vowels':'consonants'} were selected in this spelling. Check the name and any Y choices; an empty group does not mean a missing quality.</p></article>`;
    const t=themes[result.value];
    return `<article class="num-reading"><header><div class="num-seal" aria-hidden="true"><span>${result.value}</span>${result.master?`<small>root ${result.root}</small>`:''}</div><div><p class="num-kicker">${roles[role].label} · ${numberLabel(result)}</p><h5>${t.title}</h5><p class="num-keywords">${t.words}</p></div></header><p class="num-role-lens">${roles[role].lens}</p><p>${t.story}</p><div class="num-reading-pair"><section><h6>A useful expression</h6><p>${t.capacity}</p></section><section><h6>Room to grow</h6><p>${t.edge}</p></section></div><div class="num-life-lenses"><section><h6>In connection</h6><p>${t.connection}</p></section><section><h6>In your work</h6><p>${t.work}</p></section><section><h6>A small practice</h6><p>${t.practice}</p></section></div><blockquote>${t.prompt}</blockquote><details class="num-method"><summary>See the calculation</summary>${calculation}</details></article>`;
  }
  function attach(root, parts, previous={}) {
    const birth=E.birthday(E.dateKey(parts.year,parts.month,parts.day));
    const initialToday=localToday(), lastDate='2100-12-31';
    const tabs=['birth','arcs','cycles','name','pair','loshu'];
    const state={tab:tabs.includes(previous?.tab)?previous.tab:'birth',core:['path','birthDay','attitude'].includes(previous?.core)?previous.core:'path',cycleDate:previous?.cycleDate || initialToday,period:['year','month','day'].includes(previous?.period)?previous.period:'year',name:previous?.name || '',yVowels:previous?.yVowels || [],nameRead:Boolean(previous?.nameRead),nameKind:['expression','soul','personality','maturity'].includes(previous?.nameKind)?previous.nameKind:'expression',
arc:[0,1,2,3].includes(previous?.arc)?previous.arc:-1,arcView:['pinnacle','challenge'].includes(previous?.arcView)?previous.arcView:'pinnacle',
partnerDate:E.parseDate(previous?.partnerDate)?previous.partnerDate:'',partnerRead:Boolean(previous?.partnerRead&&E.parseDate(previous?.partnerDate)),pairView:['a','b','together'].includes(previous?.pairView)?previous.pairView:'together',
nameSystem:['pythagorean','chaldean'].includes(previous?.nameSystem)?previous.nameSystem:'pythagorean',
};
    if(!E.parseDate(state.cycleDate)||state.cycleDate<birth.parts.value) state.cycleDate=birth.parts.value;
    const controller=new AbortController(), $=selector=>root.querySelector(selector);
    root.classList.add('numerology-room');
    root.innerHTML=`<header class="num-intro"><div><p class="num-kicker">The numerology studio</p><h4>Numbers with a story.</h4><p>Explore the patterns of a birth date, the rhythm of a year, and the letters of a name. Follow the numbers into a richer conversation with yourself.</p><span class="num-birth-caption">Your birth date · ${dateLabel(birth.parts.value)}</span></div><div class="num-intro-orbit" aria-hidden="true"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span><i>✧</i></div></header>
      <nav class="num-tabs" aria-label="Numerology perspectives">${[['birth','Birth numbers','Your foundation'],['arcs','Life arcs','Pinnacles & challenges'],['cycles','Personal cycles','Year · month · day'],['name','Name reading','Letters & expression'],['pair','Two paths','Two birth dates'],['loshu','Lo Shu','The nine-cell square']].map(([id,label,sub])=>`<button type="button" data-num-tab="${id}" aria-pressed="${state.tab===id}" aria-controls="num-${id}">${label}<small>${sub}</small></button>`).join('')}</nav>
      <section id="num-birth" class="num-view"></section>
      <section id="num-arcs" class="num-view"><div class="num-section-heading"><p class="num-kicker">Four chapters</p><h5>The shape of a life, in four arcs.</h5><p>Pinnacles describe the theme traditionally associated with each chapter; challenges describe the recurring question of the same years. Explore any period, past or future.</p></div><div id="num-arcs-content"></div></section>
      <section id="num-cycles" class="num-view"><div class="num-section-heading"><p class="num-kicker">A changing rhythm</p><h5>Put a moment in perspective.</h5><p>Explore a date, then move through the year and the nine-year cycle around it.</p></div><div class="num-date-controls"><button type="button" data-num-day="-1" aria-label="Previous day">←</button><label for="num-cycle-date" class="sr-only">Date to explore</label><input id="num-cycle-date" type="date" value="${esc(state.cycleDate)}" min="${birth.parts.value}" max="${lastDate}"><button type="button" data-num-day="1" aria-label="Next day">→</button><button type="button" data-num-today>Today</button></div><div id="num-cycle-content"></div></section>
      <section id="num-name" class="num-view"><div class="num-section-heading"><p class="num-kicker">An optional name reading</p><h5>The letters you carry.</h5><p>Explore Expression, Soul Urge, Personality, and a longer-view Maturity number. The traditional starting point is your full name at birth; you can also explore another spelling as a variation.</p></div><div class="num-system-toggle" role="group" aria-label="Name numerology system"><button type="button" data-num-system="pythagorean" aria-pressed="${state.nameSystem==='pythagorean'}">Pythagorean<small>1–9 across A–Z · birth name</small></button><button type="button" data-num-system="chaldean" aria-pressed="${state.nameSystem==='chaldean'}">Chaldean<small>1–8 by sound · the name you use</small></button></div><form id="num-name-form"><label for="num-full-name">Name to explore</label><div class="num-name-entry"><input id="num-full-name" type="text" maxlength="120" value="${esc(state.name)}" placeholder="First, middle and last names…" autocomplete="off" spellcheck="false" aria-describedby="num-name-help"><button type="submit">Read this name <span aria-hidden="true">↗</span></button></div><p id="num-name-help">Include middle names; leave out titles and suffixes. Calculated in this page, with no upload or saved name.</p><fieldset id="num-y-options" hidden><legend>How does each Y sound?</legend><p>Check a Y when it acts as a vowel, as in Lynn. Leave it unchecked when it acts as a consonant, as at the start of Yara. Your choices affect Soul Urge and Personality.</p><div id="num-y-choices"></div></fieldset><p id="num-name-status" role="status"></p></form><div id="num-name-results"></div></section>
      <section id="num-pair" class="num-view"><div class="num-section-heading"><p class="num-kicker">Two people, two numbers</p><h5>Where two paths meet.</h5><p>Compare your Life Path with another person’s: a partner, a friend, a parent, a colleague. This is a conversation between two themes, not a score. The other date stays on this page.</p></div><form id="num-pair-form"><label for="num-pair-date">The other person’s birthday</label><div class="num-name-entry"><input id="num-pair-date" type="date" value="${esc(state.partnerDate)}" min="0001-01-01" max="${initialToday}" required><button type="submit">Compare paths <span aria-hidden="true">↗</span></button></div><p id="num-pair-status" role="status"></p></form><div id="num-pair-results"></div></section>
      <section id="num-loshu" class="num-view">${BirthdayInsights.renderNumbers(parts)}</section>
      <footer class="num-footnote"><p>A symbolic practice for reflection. These readings offer questions and perspectives, rather than measurements of personality or predictions.</p><details class="num-method"><summary>Traditions, methods & sources</summary><p>Birth and name readings use modern Pythagorean conventions. Life Path reduces the month, day and year separately, retaining 11, 22 and 33, then adds and reduces those values. Birth Day shows the original day alongside its reduced interpretation. Attitude adds month and day and always reduces to 1–9.</p><p>Personal cycles use calendar years beginning January 1, with no master numbers retained: birth month + birth day + selected year gives Personal Year; adding the selected month gives Personal Month; adding the day gives Personal Day. Some schools use birthday boundaries instead.</p><p>Name values repeat 1–9 across A–Z. This page adds the full name’s letters before reduction, retaining 11, 22 and 33 at the final reduction; it does not reduce each name separately first. Vowels and consonants are summed separately with the same rule. Maturity adds Life Path and Expression. Accents and common Latin ligatures are transliterated, and the exact A–Z spelling is shown. Other alphabets need a transliteration you choose. Master numbers are paired with their root, not treated as a rank or a measure of worth.</p><p>Chaldean readings use the letter values published by Cheiro (A1 B2 C3 D4 E5 F8 G3 H5 I1 J1 K2 L3 M4 N5 O7 P8 Q1 R2 S3 T4 U6 V6 W6 X5 Y1 Z7; no letter is 9). The compound number is the full sum before reduction; compounds 10–52 are read directly, larger sums are reduced once by adding their digits, and the single-digit root is shown alongside. Chaldean practice traditionally reads the name a person actually uses. No master numbers apply. Vowel and consonant splits belong to the Pythagorean method and are not shown here.</p><p>Lo Shu has its own Chinese cultural and mathematical context. Its modern birthday-digit overlay remains separate from these Pythagorean calculations; its birth-date root reduces master numbers too.</p><p>Calculation references: <a href="https://www.numerology.com/articles/your-numerology-chart/life-path-number-meanings/" target="_blank" rel="noopener">Life Path method</a> · <a href="https://www.worldnumerology.com/do-your-own-reading/" target="_blank" rel="noopener">Pythagorean chart conventions</a> · <a href="https://www.worldnumerology.com/personal-numerology-forecast/" target="_blank" rel="noopener">Calendar-year cycles</a>. All reading text and prompts here are original.</p></details></footer>`;
    function showTab() {
      root.querySelectorAll('[data-num-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.numTab===state.tab)));
      root.querySelectorAll('.num-view').forEach(p=>p.hidden=p.id!==`num-${state.tab}`);
    }
    function coreCalculation(kind) {
      if(kind==='path') return `<ol class="num-calculation">${['Month','Day','Year'].map((label,i)=>`<li><span>${label}</span><strong>${trail(birth.components[i])}</strong></li>`).join('')}<li><span>Add the three results</span><strong>${birth.components.map(x=>x.value).join(' + ')} = ${birth.path.steps[0]}</strong></li><li><span>Life Path</span><strong>${trail(birth.path)}</strong></li></ol><p>11, 22 and 33 are retained at each stage. Your Life Path can therefore differ from the single-digit birth-date root in Lo Shu.</p>`;
      if(kind==='birthDay') return `<p>Day of birth: <strong>${birth.parts.day}</strong>. Reduced reading: <strong>${trail(birth.birthDay)}</strong>.</p><p>The original day is kept visible. This page reads its reduced theme rather than assigning separate meanings to every compound day from 10–31.</p>`;
      return `<p>Birth month ${birth.parts.month} + birth day ${birth.parts.day} = <strong>${trail(birth.attitude)}</strong>.</p><p>Attitude is reduced to a single digit, including when the intermediate sum is 11, 22 or 33.</p>`;
    }
    function renderBirth() {
      $('#num-birth').innerHTML=`<div class="num-core-cards" role="group" aria-label="Explore your birth numbers">${['path','birthDay','attitude'].map(kind=>`<button type="button" data-num-core="${kind}" aria-pressed="${state.core===kind}"><span>${roles[kind].label}</span><strong>${kind==='birthDay'?birth.parts.day:numberLabel(birth[kind])}</strong><small>${kind==='birthDay'&&birth.parts.day!==birth.birthDay.value?`Read through ${numberLabel(birth.birthDay)}`:themes[birth[kind].value].words.split(' · ').slice(-2).join(' · ')}</small></button>`).join('')}</div><div id="num-core-reading">${readNumber(birth[state.core],state.core,coreCalculation(state.core))}</div><section class="num-weave"><p class="num-kicker">Read the numbers together</p><h5>${themes[birth.path.value].title} meets ${themes[birth.attitude.value].words.split(' · ')[0].toLowerCase()}.</h5><p>Your Life Path ${numberLabel(birth.path)} offers the wider theme of <strong>${themes[birth.path.value].words.toLowerCase()}</strong>. Your Attitude ${birth.attitude.value} brings <strong>${themes[birth.attitude.value].words.toLowerCase()}</strong> into the way you approach a moment. Notice where these perspectives support one another and where they invite a different response.</p><p>${birth.path.root===birth.birthDay.root?`Life Path and Birth Day share the root ${birth.path.root}. That repeated theme can be a useful thread to revisit in both a larger question and an ordinary daily choice.`:`Your Birth Day ${birth.parts.day}, read through ${numberLabel(birth.birthDay)}, adds the perspective of ${themes[birth.birthDay.value].words.toLowerCase()}. Let it broaden the reading rather than requiring every number to describe the same part of you.`}</p><blockquote>Which theme feels familiar, which one stretches your view, and what small action could bring them into conversation?</blockquote></section>`;
    }
    const arcModel=E.arcs(birth);
    function ageRange(p) { return p.toAge===null?`age ${p.fromAge} onward`:p.fromAge===0?`birth to age ${p.toAge}`:`ages ${p.fromAge}–${p.toAge}`; }
    function yearRange(p) { return p.toYear===null?`${p.fromYear} →`:`${p.fromYear}–${p.toYear}`; }
    function renderArcs() {
      const now=E.currentArc(arcModel,localToday());
      if(state.arc<0) state.arc=now<0?0:now;
      const p=arcModel.pinnacles[state.arc], c=arcModel.challenges[state.arc];
      const timeline=`<div class="num-arc-timeline" role="group" aria-label="Choose a life period">${arcModel.pinnacles.map((pin,i)=>{const ch=arcModel.challenges[i];return `<button type="button" data-num-arc="${i}" aria-pressed="${state.arc===i}" aria-label="Period ${i+1}, ${ageRange(pin)}, pinnacle ${numberLabel(pin.number)}, challenge ${ch.number}${now===i?', current period':''}"><span>Period ${i+1}${now===i?' · now':''}</span><strong>${numberLabel(pin.number)}</strong><small>Pinnacle</small><em>${ch.number}</em><small>Challenge</small><b>${ageRange(pin)}</b><i>${yearRange(pin)}</i></button>`;}).join('')}</div>`;
      const toggle=`<div class="num-arc-toggle" role="group" aria-label="Read the pinnacle or the challenge">${[['pinnacle','Pinnacle'],['challenge','Challenge']].map(([id,label])=>`<button type="button" data-num-arc-view="${id}" aria-pressed="${state.arcView===id}">${label}</button>`).join('')}</div>`;
      let reading;
      if(state.arcView==='pinnacle') {
        const t=themes[p.number.value];
        reading=`<article class="num-reading"><header><div class="num-seal" aria-hidden="true"><span>${p.number.value}</span>${p.number.master?`<small>root ${p.number.root}</small>`:''}</div><div><p class="num-kicker">Pinnacle ${state.arc+1} · ${ageRange(p)} · ${yearRange(p)}</p><h5>${t.title}</h5><p class="num-keywords">${t.words}</p></div></header><p class="num-role-lens">${arcLens[p.number.value]}</p><p>${t.story}</p><div class="num-reading-pair"><section><h6>A useful expression</h6><p>${t.capacity}</p></section><section><h6>Room to grow</h6><p>${t.edge}</p></section></div><blockquote>${t.prompt}</blockquote><details class="num-method"><summary>See the calculation</summary><p>${p.calculation} → <strong>${trail(p.number)}</strong>. Components use the single-digit month, day and year (${arcModel.components.month}, ${arcModel.components.day}, ${arcModel.components.year}); results keep 11, 22 and 33.</p><p>The first period ends at age 36 − ${birth.path.root} (your Life Path root) = ${arcModel.firstPeriodEnd}; the next two last nine years each.</p></details></article>`;
      } else {
        const t=challengeCopy[c.number];
        reading=`<article class="num-reading"><header><div class="num-seal" aria-hidden="true"><span>${c.number}</span></div><div><p class="num-kicker">Challenge ${state.arc+1} · ${ageRange(c)} · ${yearRange(c)}</p><h5>${t.title}</h5><p class="num-keywords">${t.words}</p></div></header><p class="num-role-lens">A challenge names a recurring question of the period, not a flaw or a prediction. The same question can be met many ways.</p><p>${t.story}</p><blockquote>${t.prompt}</blockquote><details class="num-method"><summary>See the calculation</summary><p>${c.calculation}. Challenges take the difference of single-digit components, so results run 0–8; 0 has its own reading.</p></details></article>`;
      }
      $('#num-arcs-content').innerHTML=timeline+toggle+reading;
    }
    function renderCycles() {
      $('#num-cycle-date').value=state.cycleDate;
      const parsed=E.parseDate(state.cycleDate);
      if(!parsed||state.cycleDate<birth.parts.value||state.cycleDate>lastDate) {
        $('#num-cycle-content').innerHTML=`<p class="num-error" role="status">Choose a valid date from ${dateLabel(birth.parts.value)} through December 31, 2100.</p>`;
        root.querySelectorAll('[data-num-day]').forEach(b=>b.disabled=true);return;
      }
      const c=E.cycles(birth,state.cycleDate),selected=c[state.period],level=['year','month','day'].indexOf(state.period),t=themes[selected.value];
      root.querySelectorAll('[data-num-day]').forEach(b=>b.disabled=b.dataset.numDay==='-1'?state.cycleDate<=birth.parts.value:state.cycleDate>=lastDate);
      const calculations={year:`${birth.parts.month} + ${birth.parts.day} + ${c.date.year} = ${trail(c.year)}`,month:`Personal Year ${c.year.value} + month ${c.date.month} = ${trail(c.month)}`,day:`Personal Month ${c.month.value} + day ${c.date.day} = ${trail(c.day)}`};
      $('#num-cycle-content').innerHTML=`<p class="num-date-caption" role="status">Exploring ${dateLabel(state.cycleDate)} · calendar-year method</p><div class="num-cycle-cards" role="group" aria-label="Explore a personal cycle">${['year','month','day'].map(kind=>`<button type="button" data-num-period="${kind}" aria-pressed="${state.period===kind}"><span>Personal ${kind}</span><strong>${c[kind].value}</strong><small>${kind==='year'?c.date.year:kind==='month'?monthNames[c.date.month-1]:`${c.date.day} ${monthNames[c.date.month-1].slice(0,3)}`}</small></button>`).join('')}</div><article class="num-cycle-reading"><p class="num-kicker">Personal ${state.period} ${selected.value}</p><h5>${t.title}</h5><p>${cycleCopy[selected.value][level]}</p><p class="num-cycle-context">${state.period==='year'?'The year offers a broad reflective theme. Your month and day numbers add shorter perspectives within it.':state.period==='month'?`This month sits within Personal Year ${c.year.value}, whose theme is ${themes[c.year.value].words.toLowerCase()}. Look for a way the two can support one practical intention.`:`This day sits within Personal Month ${c.month.value} and Personal Year ${c.year.value}. Keep its theme small enough to try in the life you are actually living today.`}</p><blockquote>${t.prompt}</blockquote><details class="num-method"><summary>See the cycle calculation</summary><ol class="num-calculation">${['year','month','day'].map(kind=>`<li><span>${kind[0].toUpperCase()+kind.slice(1)}</span><strong>${calculations[kind]}</strong></li>`).join('')}</ol><p>These cycles always reduce to 1–9. The birth year is not used. Year boundaries are January 1; this page does not use birthday-to-birthday cycles.</p></details></article><section class="num-cycle-overview"><div class="num-overview-heading"><h5>Your nine-year sequence</h5><p>Choose a year to explore its place in the cycle.</p></div><div class="num-years" role="group" aria-label="Nine-year cycle">${c.years.map(y=>`<button type="button" data-num-year="${y.year}" aria-pressed="${y.year===c.date.year}" ${y.year<birth.parts.year||y.year>2100?'disabled':''}><span>${y.year}</span><strong>${y.number}</strong><small>${['Begin','Connect','Express','Build','Explore','Care','Reflect','Organize','Complete'][y.number-1]}</small></button>`).join('')}</div></section><section class="num-cycle-overview"><div class="num-overview-heading"><h5>Twelve months of ${c.date.year}</h5><p>A smaller rhythm within Personal Year ${c.year.value}.</p></div><div class="num-months" role="group" aria-label="Personal months">${c.months.map(m=>`<button type="button" data-num-month="${m.month}" aria-pressed="${m.month===c.date.month}" ${c.date.year===birth.parts.year&&m.month<birth.parts.month?'disabled':''}><span>${monthNames[m.month-1]}</span><strong>${m.number}</strong><small>${themes[m.number].words.split(' · ')[0]}</small></button>`).join('')}</div></section>`;
    }
    function renderYChoices() {
      const n=E.normalizeName(state.name),ys=n.ys || [];
      $('#num-y-options').hidden=!ys.length||state.nameSystem==='chaldean';
      $('#num-y-choices').innerHTML=ys.map(y=>`<label><input type="checkbox" data-num-y="${y.index}" ${state.yVowels.includes(y.index)?'checked':''}>Y in ${esc(y.word)} · letter ${y.index+1} of the name is a vowel</label>`).join('');
    }
    function renderName() {
      if(!state.nameRead) {
        $('#num-name-results').innerHTML='<div class="num-name-invitation"><span aria-hidden="true">A · B · C <i>↓</i> 1 · 2 · 3</span><h5>A name, seen another way.</h5><p>When you are ready, enter a name to see its numbers, explore each perspective, and follow every letter through the calculation.</p></div>';return;
      }
      const n=E.nameProfile(state.name,state.yVowels,birth,state.nameSystem);
      if(n.status!=='ready') {$('#num-name-status').textContent=n.message;$('#num-name-results').innerHTML='';return;}
      if(n.system==='chaldean') {
        const copy=n.reading.readAs>9?compoundCopy[n.reading.readAs]:themes[n.reading.readAs];
        const readingNote=n.reading.readAs===n.compound?'':n.reading.readAs>9?`Compound ${n.compound} is above 52, so it is reduced once (${n.compound} → ${n.reading.readAs}) and read as compound ${n.reading.readAs}.`:`Compound ${n.compound} reduces to ${n.reading.readAs}, which is read as a single digit.`;
        $('#num-name-status').textContent=`Chaldean reading ready · calculated spelling: ${n.normalized}.`;
        $('#num-name-results').innerHTML=`<div class="num-name-cards num-name-cards-chaldean" role="group" aria-label="Your Chaldean name number"><div class="num-compound-card"><span>Name number</span><strong>${n.compound}</strong><small>Compound · root ${n.reading.root}</small></div></div><section class="num-letter-study"><div class="num-overview-heading"><h5>Every letter, by sound.</h5><p>Chaldean values run 1–8. Exact spelling: <strong>${esc(n.normalized)}</strong></p></div><div class="num-letter-words" aria-label="Letter values">${n.words.map(w=>`<div class="num-letter-word">${n.letters.filter(x=>x.wordIndex===w.wordIndex).map(x=>`<span class="num-letter" aria-label="${x.letter}: ${x.value}"><b>${x.letter}</b><small>${x.value}</small></span>`).join('')}</div>`).join('')}</div><table class="num-word-table"><caption>Each word on its own</caption><thead><tr><th scope="col">Word</th><th scope="col">Compound</th><th scope="col">Root</th></tr></thead><tbody>${n.words.map(w=>`<tr><th scope="row">${esc(w.word)}</th><td>${w.compound}</td><td>${w.root}</td></tr>`).join('')}</tbody></table><p class="num-letter-totals">All letters = ${n.compound}${readingNote?' · '+readingNote:''}</p></section><article class="num-reading"><header><div class="num-seal" aria-hidden="true"><span>${n.reading.readAs}</span><small>root ${n.reading.root}</small></div><div><p class="num-kicker">Compound ${n.reading.readAs}${n.reading.readAs>9?'':' · single digit'}</p><h5>${copy.title}</h5><p class="num-keywords">${copy.words}</p></div></header><p class="num-role-lens">Chaldean tradition reads the name you actually use day to day. Try the spelling people call you by, then a formal version, and notice what changes.</p><p>${copy.story}</p><blockquote>${copy.prompt}</blockquote><details class="num-method"><summary>See the calculation</summary><p>${n.letters.map(x=>`${x.letter} (${x.value})`).join(' + ')} = <strong>${n.compound}</strong>; digit sum ${n.reading.root}.</p></details></article>`;
        return;
      }
      $('#num-name-status').textContent=`Reading ready · calculated spelling: ${n.normalized}.`;
      const kind=state.nameKind, selected=n[kind];
      const group=kind==='soul'?n.letters.filter(x=>x.vowel):kind==='personality'?n.letters.filter(x=>!x.vowel):n.letters;
      const calculation=kind==='maturity'?`<p>Life Path ${numberLabel(birth.path)} + Expression ${numberLabel(n.expression)}: <strong>${birth.path.value} + ${n.expression.value} = ${trail(n.maturity)}</strong>.</p>`:`<p>${kind==='expression'?'All letters':kind==='soul'?'Vowels':'Consonants'}: ${group.map(x=>`${x.letter} (${x.value})`).join(' + ') || 'None'}${selected?` = <strong>${trail(selected)}</strong>`:''}.</p><p>The whole group is added before reduction. Master numbers 11, 22 and 33 are retained at the final reduction.</p>`;
      $('#num-name-results').innerHTML=`<div class="num-name-cards" role="group" aria-label="Explore your name numbers">${['expression','soul','personality','maturity'].map(key=>`<button type="button" data-num-name-kind="${key}" aria-pressed="${kind===key}"><span>${roles[key].label}</span><strong>${numberLabel(n[key])}</strong><small>${{expression:'All letters',soul:'Vowels',personality:'Consonants',maturity:'Life Path + Expression'}[key]}</small></button>`).join('')}</div><section class="num-letter-study"><div class="num-overview-heading"><h5>Every letter, accounted for.</h5><p>${kind==='maturity'?'The name’s Expression joins your Life Path in the Maturity reading.':`Highlighted letters contribute to ${roles[kind].label}.`} Exact spelling: <strong>${esc(n.normalized)}</strong></p></div><div class="num-letter-words" aria-label="Letter values">${[...new Set(n.letters.map(x=>x.wordIndex))].map(wordIndex=>`<div class="num-letter-word">${n.letters.filter(x=>x.wordIndex===wordIndex).map(x=>`<span class="num-letter${kind==='soul'&&!x.vowel||kind==='personality'&&x.vowel?' is-muted':''}" aria-label="${x.letter}: ${x.value}, ${x.vowel?'vowel':'consonant'}"><b>${x.letter}</b><small>${x.value}</small></span>`).join('')}</div>`).join('')}</div><p class="num-letter-totals">All letters ${n.totals.expression} = vowels ${n.totals.soul} + consonants ${n.totals.personality}</p></section>${readNumber(selected,kind,calculation)}<section class="num-weave"><p class="num-kicker">Name & birth date together</p><h5>Intention into expression.</h5><p>Life Path ${numberLabel(birth.path)} invites you to revisit <strong>${themes[birth.path.value].words.toLowerCase()}</strong>. Expression ${numberLabel(n.expression)} brings <strong>${themes[n.expression.value].words.toLowerCase()}</strong> into the way you contribute. Consider one situation in which you could make room for both perspectives.</p>${n.soul&&n.personality?`<p>Soul Urge ${numberLabel(n.soul)} asks what feels meaningful inwardly; Personality ${numberLabel(n.personality)} explores outward expression. ${n.soul.root===n.personality.root?'They share a root here. Use that repeated theme to ask where your choices feel congruent with what matters to you.':'Their different themes can open a useful question: what would help your outward choices express more of what matters to you inwardly?'}</p>`:''}<blockquote>What feels true to your experience, and what would you put into your own words?</blockquote></section>`;
    }
    function personCard(label, b, key) {
      return `<button type="button" data-num-pair-view="${key}" aria-pressed="${state.pairView===key}"><span>${label}</span><strong>${numberLabel(b.path)}</strong><small>Life Path · ${themes[b.path.value].title}</small></button>`;
    }
    function renderPair() {
      if(!state.partnerRead) {
        $('#num-pair-results').innerHTML='<div class="num-name-invitation"><span aria-hidden="true">9 <i>·</i> 1</span><h5>Two dates, side by side.</h5><p>Enter another person’s birthday to see both Life Paths, how their traditional groupings relate, and the number the pair makes together.</p></div>';return;
      }
      const parsed=E.parseDate(state.partnerDate);
      if(!parsed||state.partnerDate>localToday()) {$('#num-pair-status').textContent='Choose a valid birthday on or before today.';$('#num-pair-results').innerHTML='';return;}
      const other=E.birthday(state.partnerDate), model=E.pair(birth,other,localToday());
      $('#num-pair-status').textContent=`Comparing ${dateLabel(birth.parts.value)} with ${dateLabel(state.partnerDate)}.`;
      const cards=`<div class="num-pair-cards" role="group" aria-label="Choose a view">${personCard('Your path',model.a,'a')}<button type="button" data-num-pair-view="together" aria-pressed="${state.pairView==='together'}"><span>Together</span><strong>${numberLabel(model.pairNumber)}</strong><small>The pair’s number</small></button>${personCard('Their path',model.b,'b')}</div>`;
      let body;
      if(state.pairView!=='together') {
        const person=model[state.pairView], r=relating[person.path.value], t=themes[person.path.value], who=state.pairView==='a'?'You':'They';
        body=`<article class="num-reading"><header><div class="num-seal" aria-hidden="true"><span>${person.path.value}</span>${person.path.master?`<small>root ${person.path.root}</small>`:''}</div><div><p class="num-kicker">${who==='You'?'Your':'Their'} Life Path · ${numberLabel(person.path)}</p><h5>${r.title}</h5><p class="num-keywords">${t.words}</p></div></header><p>${r.story}</p><p class="num-role-lens">Birth Day ${who==='You'?birth.parts.day:parsed.day} and Attitude ${numberLabel(person.attitude)} add everyday texture; Personal Year ${person.year.value} is the current calendar-year theme.</p><blockquote>${r.prompt}</blockquote></article>`;
      } else {
        const t=themes[model.pairNumber.value];
        const concordNote=model.sameRoot?`Both Life Paths share the root ${model.a.path.root}. A shared number can feel like instant recognition and can also mean the same blind spot twice; the question is who notices first.`:model.concord.same?`Both numbers belong to ${concordCopy[model.concord.a]}. Numbers in the same concord are traditionally read as speaking a similar language, which makes agreement easy and difference easy to overlook.`:`Your number belongs to ${concordCopy[model.concord.a]}; theirs to ${concordCopy[model.concord.b]}. Different concords are traditionally read as different first languages: the same situation is approached from different directions, which is a source of both friction and range.`;
        const yearNote={same:`You are both in Personal Year ${model.a.year.value} this calendar year, so the same theme is asking each of you for a response.`,adjacent:`Your Personal Years (${model.a.year.value} and ${model.b.year.value}) are adjacent in the nine-year cycle: one of you is a step ahead in a rhythm the other is about to enter.`,apart:`Your Personal Years (${model.a.year.value} and ${model.b.year.value}) sit in different parts of the nine-year cycle, so this year’s questions may differ for each of you.`}[model.yearRelation];
        body=`<article class="num-reading"><header><div class="num-seal" aria-hidden="true"><span>${model.pairNumber.value}</span>${model.pairNumber.master?`<small>root ${model.pairNumber.root}</small>`:''}</div><div><p class="num-kicker">The pair’s number · ${numberLabel(model.pairNumber)}</p><h5>${t.title}</h5><p class="num-keywords">${t.words}</p></div></header><p class="num-role-lens">Adding two Life Paths gives a number to read as the theme the two of you make together, not a verdict on the relationship.</p><p>${t.story}</p><div class="num-reading-pair"><section><h6>Shared ground</h6><p>${concordNote}</p></section><section><h6>This year</h6><p>${yearNote}</p></section></div><blockquote>${t.connection}</blockquote><details class="num-method"><summary>See the calculation</summary><p>Life Path ${model.a.path.value} + Life Path ${model.b.path.value} = ${trail(model.pairNumber)}. Concords are evaluated on roots (11 → 2, 22 → 4, 33 → 6). Personal Years use the calendar-year method.</p></details></article>`;
      }
      $('#num-pair-results').innerHTML=cards+body;
    }
    root.addEventListener('click', event=>{
      const button=event.target.closest('button');if(!button)return;const d=button.dataset;
      if(d.numTab){state.tab=d.numTab;showTab();return;}
      if(d.numArc){state.arc=Number(d.numArc);renderArcs();$(`[data-num-arc="${state.arc}"]`).focus({preventScroll:true});return;}
      if(d.numArcView){state.arcView=d.numArcView;renderArcs();$(`[data-num-arc-view="${state.arcView}"]`).focus({preventScroll:true});return;}
      if(d.numCore){state.core=d.numCore;renderBirth();$(`[data-num-core="${state.core}"]`).focus({preventScroll:true});return;}
      if(d.numNameKind){state.nameKind=d.numNameKind;renderName();$(`[data-num-name-kind="${state.nameKind}"]`).focus({preventScroll:true});return;}
      if(d.numPeriod){state.period=d.numPeriod;renderCycles();$(`[data-num-period="${state.period}"]`).focus({preventScroll:true});return;}
      if(d.numPairView){state.pairView=d.numPairView;renderPair();$(`[data-num-pair-view="${state.pairView}"]`).focus({preventScroll:true});return;}
      if(d.numSystem){state.nameSystem=d.numSystem;root.querySelectorAll('[data-num-system]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.numSystem===state.nameSystem)));renderYChoices();renderName();$(`[data-num-system="${state.nameSystem}"]`).focus({preventScroll:true});return;}
      let focus='';
      if('numToday' in d){state.cycleDate=localToday();state.period='day';focus='[data-num-today]';}
      if(d.numDay){const date=new Date(`${state.cycleDate}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+Number(d.numDay));state.cycleDate=date.toISOString().slice(0,10);focus=`[data-num-day="${d.numDay}"]`;}
      if(d.numYear){const p=E.parseDate(state.cycleDate);state.cycleDate=E.dateInMonth(state.cycleDate,Number(d.numYear),p.month,birth.parts.value,lastDate);state.period='year';focus=`[data-num-year="${d.numYear}"]`;}
      if(d.numMonth){const p=E.parseDate(state.cycleDate);state.cycleDate=E.dateInMonth(state.cycleDate,p.year,Number(d.numMonth),birth.parts.value,lastDate);state.period='month';focus=`[data-num-month="${d.numMonth}"]`;}
      if(focus){renderCycles();$(focus)?.focus({preventScroll:true});}
    },{signal:controller.signal});
    root.addEventListener('change',event=>{
      if(event.target.id==='num-cycle-date'){state.cycleDate=event.target.value;renderCycles();}
      if(event.target.matches('[data-num-y]')) {state.yVowels=[...root.querySelectorAll('[data-num-y]:checked')].map(x=>Number(x.dataset.numY));if(state.nameRead)renderName();}
    },{signal:controller.signal});
    $('#num-full-name').addEventListener('input',event=>{state.name=event.target.value;state.nameRead=false;state.yVowels=[];renderYChoices();$('#num-name-status').textContent=state.name?'Choose Read this name when you are ready.':'';renderName();},{signal:controller.signal});
    $('#num-name-form').addEventListener('submit',event=>{event.preventDefault();state.name=$('#num-full-name').value;state.nameRead=true;renderName();},{signal:controller.signal});
    $('#num-pair-form').addEventListener('submit',event=>{event.preventDefault();state.partnerDate=$('#num-pair-date').value;state.partnerRead=true;renderPair();},{signal:controller.signal});
    $('#num-pair-date').addEventListener('input',event=>{state.partnerDate=event.target.value;state.partnerRead=false;$('#num-pair-status').textContent=state.partnerDate?'Choose Compare paths when you are ready.':'';renderPair();},{signal:controller.signal});
    renderBirth();renderArcs();renderCycles();renderYChoices();renderName();renderPair();showTab();
    return {getState:()=>({...state,yVowels:[...state.yVowels]}),destroy:()=>controller.abort()};
  }
  return {attach};
})();
