# Generated by Django 5.2.6 on 2026-09-10 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tarot-daily', 'Tarot daily card'), ('tarot-spread', 'Tarot spread'), ('lenormand', 'Lenormand'), ('oracle', 'Ishtar Reflection Oracle'), ('runes', 'Runes'), ('geomancy', 'Geomancy')], max_length=20)),
                ('deck', models.CharField(blank=True, max_length=40)),
                ('layout', models.CharField(blank=True, max_length=40)),
                ('question', models.CharField(blank=True, max_length=240)),
                ('focus', models.CharField(blank=True, max_length=40)),
                ('payload', models.JSONField()),
                ('note', models.TextField(blank=True, max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='readings_re_user_id_1105d9_idx')],
            },
        ),
    ]
