# Generated by Django 5.2.6 on 2026-09-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='kind',
            field=models.CharField(choices=[('tarot-daily', 'Tarot daily card'), ('tarot-spread', 'Tarot spread'), ('lenormand', 'Lenormand'), ('oracle', 'Ishtar Reflection Oracle'), ('runes', 'Runes'), ('geomancy', 'Geomancy'), ('iching', 'I Ching')], max_length=20),
        ),
    ]
