# Generated by Django 5.2.6 on 2026-09-13 14:25

from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    Reading = apps.get_model('readings', 'Reading')
    Reading.objects.filter(kind__startswith='tarot').update(category='tarot')
    Reading.objects.exclude(kind__startswith='tarot').update(category='divination')


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_reading_kind_iching'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='category',
            field=models.CharField(choices=[('tarot', 'tarot'), ('sky', 'sky'), ('charts', 'charts'), ('eastern', 'eastern'), ('numerology', 'numerology'), ('divination', 'divination')], default='tarot', max_length=12),
        ),
        migrations.AddField(
            model_name='reading',
            name='summary',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='reading',
            name='kind',
            field=models.CharField(choices=[('tarot-daily', 'Daily card'), ('tarot-spread', 'Tarot spread'), ('lenormand', 'Lenormand'), ('oracle', 'Ishtar Reflection Oracle'), ('runes', 'Runes'), ('geomancy', 'Geomancy'), ('iching', 'I Ching'), ('natal', 'Birth chart'), ('solar-return', 'Solar return'), ('lunar-return', 'Lunar return'), ('progressed', 'Progressed chart'), ('synastry', 'Synastry'), ('horary', 'Horary chart'), ('jyotish', 'Jyotish chart'), ('bazi', 'Four Pillars'), ('numerology', 'Numerology')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['user', 'category', '-created_at'], name='readings_re_user_id_c6aa8d_idx'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
