# Generated by Django 5.2.6 on 2026-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_reading_kind_c4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='kind',
            field=models.CharField(choices=[('tarot-daily', 'Daily card'), ('tarot-spread', 'Tarot spread'), ('transit-calendar', 'Transit calendar'), ('lenormand', 'Lenormand'), ('oracle', 'Ishtar Reflection Oracle'), ('runes', 'Runes'), ('geomancy', 'Geomancy'), ('iching', 'I Ching'), ('grand-tableau', 'Grand Tableau'), ('geomancy-houses', 'Geomantic house chart'), ('cartomancy', 'Playing cards'), ('natal', 'Birth chart'), ('solar-return', 'Solar return'), ('lunar-return', 'Lunar return'), ('progressed', 'Progressed chart'), ('synastry', 'Synastry'), ('composite', 'Composite chart'), ('davison', 'Davison chart'), ('horary', 'Horary chart'), ('jyotish', 'Jyotish chart'), ('bazi', 'Four Pillars'), ('numerology', 'Numerology')], max_length=32),
        ),
    ]
