# Generated by Django 5.2.6 on 2026-09-10 03:24

import newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('consent_at', models.DateTimeField()),
                ('consent_version', models.CharField(max_length=40)),
                ('consent_text', models.TextField()),
                ('unsubscribe_token', models.CharField(default=newsletter.models.new_token, max_length=43, unique=True)),
            ],
        ),
    ]
