# Generated by Django 5.2.6 on 2026-09-10 01:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.SlugField(max_length=40)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe')], default='manual', max_length=10)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='Stripe subscription id once billing exists.', max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'feature'], name='accounts_en_user_id_17c661_idx')],
            },
        ),
    ]
